import type { ScenarioTemplate } from './index';

export const demoWindowsUpdates: ScenarioTemplate = {
  name: 'Demo — Force Windows Updates',
  description: 'Check for and install pending Windows updates, reboot if needed.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    REBOOT_IF_NEEDED: 'true',
  },
  timeoutSeconds: 3600,
  steps: [
    {
      name: 'Scan and install updates',
      description: 'Use the Windows Update COM API to search for, download, and install pending updates. Schedules a reboot if required.',
      checkScript: null,
      resolveScript: {
        name: 'Install Windows updates',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$ErrorActionPreference = "Stop"',
          '',
          '$session  = New-Object -ComObject Microsoft.Update.Session',
          '$searcher = $session.CreateUpdateSearcher()',
          '',
          'Write-Host "Searching for updates..."',
          '$result = $searcher.Search("IsInstalled=0 AND IsHidden=0")',
          '',
          'if ($result.Updates.Count -eq 0) {',
          '    Write-Host "No pending updates found"',
          '    exit 0',
          '}',
          '',
          'Write-Host "$($result.Updates.Count) update(s) found"',
          '',
          '# Download',
          '$downloader = $session.CreateUpdateDownloader()',
          '$downloader.Updates = $result.Updates',
          '$downloader.Download() | Out-Null',
          '',
          '# Install',
          '$installer = $session.CreateUpdateInstaller()',
          '$installer.Updates = $result.Updates',
          '$installResult = $installer.Install()',
          '',
          'Write-Host "Install result: $($installResult.ResultCode)"',
          '',
          'if ($installResult.RebootRequired -and $env:REBOOT_IF_NEEDED -eq "true") {',
          '    Write-Host "Reboot required — scheduling in 5 minutes"',
          '    shutdown /r /t 300 /c "Reboot scheduled by Obliance after Windows Updates"',
          '}',
          '',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 3600,
      retryCount: 0,
    },
  ],
};
