import type { ScenarioTemplate } from './index';

export const deployObliviewWindows: ScenarioTemplate = {
  name: 'Deploy Obliview Agent — Windows',
  description: 'Installs and configures the Obliview remote viewing agent on Windows devices. Downloads the MSI installer, performs a silent install, and verifies the service is running.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
  },
  timeoutSeconds: 900,
  steps: [
    // ── Step 1: Check if Obliview is installed, install if not ──────────────
    {
      name: 'Install Obliview agent',
      description: 'Checks whether the ObliviewAgent service exists. If not, downloads and installs the MSI silently.',
      checkScript: {
        name: 'Check Obliview installed (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service ObliviewAgent -ErrorAction SilentlyContinue',
          'if ($svc) { Write-Host "ObliviewAgent service found"; exit 0 }',
          'else { Write-Host "ObliviewAgent service not found"; exit 1 }',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Obliview (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$ErrorActionPreference = "Stop"',
          '',
          '$serverUrl = "{{SERVER_URL}}"',
          '$apiKey   = "{{API_KEY}}"',
          '',
          'if (-not $serverUrl) { Write-Error "SERVER_URL variable is required"; exit 1 }',
          'if (-not $apiKey)   { Write-Error "API_KEY variable is required"; exit 1 }',
          '',
          '$msiPath = Join-Path $env:TEMP "obliview-agent.msi"',
          '',
          '# Download installer',
          'try {',
          '    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
          '    $wc = New-Object System.Net.WebClient',
          '    $wc.Headers.Add("X-Api-Key", $apiKey)',
          '    $wc.DownloadFile("$serverUrl/api/agent/installer/obliview-windows.msi", $msiPath)',
          '} catch {',
          '    # Fallback for older systems: use Invoke-WebRequest',
          '    Invoke-WebRequest -Uri "$serverUrl/api/agent/installer/obliview-windows.msi" `',
          '        -Headers @{"X-Api-Key" = $apiKey} `',
          '        -OutFile $msiPath -UseBasicParsing',
          '}',
          '',
          'if (-not (Test-Path $msiPath)) { Write-Error "Download failed"; exit 1 }',
          '',
          '# Silent install',
          '$args = "/i `"$msiPath`" SERVERURL=`"$serverUrl`" APIKEY=`"$apiKey`" /quiet /norestart /l*v `"$env:TEMP\\obliview-install.log`""',
          '$proc = Start-Process msiexec -ArgumentList $args -Wait -PassThru',
          '',
          '# Retry on mutex error 1618',
          '$retries = 0',
          'while ($proc.ExitCode -eq 1618 -and $retries -lt 5) {',
          '    $retries++',
          '    Write-Host "MSI mutex busy, retry $retries/5..."',
          '    Start-Sleep -Seconds 15',
          '    $proc = Start-Process msiexec -ArgumentList $args -Wait -PassThru',
          '}',
          '',
          'Remove-Item $msiPath -ErrorAction SilentlyContinue',
          '',
          'if ($proc.ExitCode -ne 0) {',
          '    Write-Error "MSI install failed with exit code $($proc.ExitCode)"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Obliview agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Obliview service running',
      description: 'Confirms the ObliviewAgent service is in Running state after installation.',
      checkScript: {
        name: 'Check Obliview running (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service ObliviewAgent -ErrorAction SilentlyContinue',
          'if ($svc -and $svc.Status -eq "Running") {',
          '    Write-Host "ObliviewAgent is running"',
          '    exit 0',
          '}',
          '',
          '# Try starting it',
          'if ($svc) {',
          '    Start-Service ObliviewAgent -ErrorAction SilentlyContinue',
          '    Start-Sleep -Seconds 5',
          '    $svc.Refresh()',
          '    if ($svc.Status -eq "Running") { Write-Host "ObliviewAgent started"; exit 0 }',
          '}',
          '',
          'Write-Host "ObliviewAgent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },
  ],
};
