import type { ScenarioTemplate } from './index';

export const deployOblimapUnix: ScenarioTemplate = {
  name: 'Deploy Oblimap Agent — Linux / macOS',
  description: 'Installs the Oblimap network discovery and topology agent on Linux and macOS devices. Deploys the agent, verifies it is running, and triggers an initial network probe.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
    PROBE_SUBNET: '',
  },
  timeoutSeconds: 1200,
  steps: [
    // ── Step 1: Check if Oblimap is installed, install if not ───────────────
    {
      name: 'Install Oblimap agent',
      description: 'Checks whether the Oblimap agent service exists. If not, downloads and runs the installer script.',
      checkScript: {
        name: 'Check Oblimap installed (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet oblimap-agent 2>/dev/null; then',
          '      echo "oblimap-agent service is active"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/oblimap-agent ]; then',
          '      echo "oblimap-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.oblimap.agent >/dev/null 2>&1; then',
          '      echo "com.oblimap.agent service found"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/oblimap-agent ]; then',
          '      echo "oblimap-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Oblimap agent not found"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Oblimap (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'resolve',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'SERVER_URL="{{SERVER_URL}}"',
          'API_KEY="{{API_KEY}}"',
          '',
          'if [ -z "$SERVER_URL" ]; then echo "ERROR: SERVER_URL is required" >&2; exit 1; fi',
          'if [ -z "$API_KEY" ]; then echo "ERROR: API_KEY is required" >&2; exit 1; fi',
          '',
          'OS="$(uname -s)"',
          '',
          'case "$OS" in',
          '  Linux)',
          '    echo "Installing Oblimap agent on Linux..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/oblimap-linux" | sudo bash',
          '    ;;',
          '  Darwin)',
          '    echo "Installing Oblimap agent on macOS..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/oblimap-macos" | sudo bash',
          '    ;;',
          '  *)',
          '    echo "Unsupported platform: $OS" >&2',
          '    exit 1',
          '    ;;',
          'esac',
          '',
          'echo "Oblimap agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Oblimap service running',
      description: 'Confirms the Oblimap agent service is running after installation.',
      checkScript: {
        name: 'Check Oblimap running (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet oblimap-agent 2>/dev/null; then',
          '      echo "oblimap-agent is running"',
          '      exit 0',
          '    fi',
          '    sudo systemctl start oblimap-agent 2>/dev/null || true',
          '    sleep 3',
          '    if systemctl is-active --quiet oblimap-agent 2>/dev/null; then',
          '      echo "oblimap-agent started successfully"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.oblimap.agent >/dev/null 2>&1; then',
          '      echo "com.oblimap.agent is running"',
          '      exit 0',
          '    fi',
          '    sudo launchctl load /Library/LaunchDaemons/com.oblimap.agent.plist 2>/dev/null || true',
          '    sleep 3',
          '    if launchctl list com.oblimap.agent >/dev/null 2>&1; then',
          '      echo "com.oblimap.agent started"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Oblimap agent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },

    // ── Step 3: Run initial network probe ──────────────────────────────────
    {
      name: 'Run initial network probe',
      description: 'Triggers an initial network discovery scan. If PROBE_SUBNET is set, scans that subnet; otherwise performs auto-discovery of local subnets.',
      checkScript: {
        name: 'Check Oblimap probe status (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          '',
          'STATUS_FILE="/var/lib/oblimap-agent/probe-status.json"',
          '',
          'if [ -f "$STATUS_FILE" ]; then',
          '    if command -v jq >/dev/null 2>&1; then',
          '        if jq -e ".lastProbeSuccess" "$STATUS_FILE" >/dev/null 2>&1; then',
          '            echo "Initial probe already completed"',
          '            exit 0',
          '        fi',
          '    elif grep -q "lastProbeSuccess.*true" "$STATUS_FILE" 2>/dev/null; then',
          '        echo "Initial probe already completed"',
          '        exit 0',
          '    fi',
          'fi',
          '',
          'echo "No successful probe found"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Run Oblimap probe (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'resolve',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'PROBE_SUBNET="{{PROBE_SUBNET}}"',
          'OBLIMAP_CLI="/usr/local/bin/oblimap-agent"',
          '',
          'if [ ! -x "$OBLIMAP_CLI" ]; then',
          '    echo "Oblimap agent binary not found at $OBLIMAP_CLI" >&2',
          '    exit 1',
          'fi',
          '',
          'if [ -n "$PROBE_SUBNET" ]; then',
          '    echo "Running probe on subnet: $PROBE_SUBNET"',
          '    "$OBLIMAP_CLI" probe --subnet "$PROBE_SUBNET" --timeout 120',
          'else',
          '    echo "Running auto-discovery probe..."',
          '    "$OBLIMAP_CLI" probe --auto-discover --timeout 120',
          'fi',
          '',
          'echo "Network probe completed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 180,
      retryCount: 1,
    },
  ],
};
