import type { ScenarioTemplate } from './index';

export const deployObliguardWindows: ScenarioTemplate = {
  name: 'Deploy Obliguard Agent — Windows',
  description: 'Installs and configures the Obliguard endpoint protection agent on Windows devices. Deploys the agent, verifies it is running, and confirms the security policy is applied.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
    POLICY_ID: '',
  },
  timeoutSeconds: 1200,
  steps: [
    // ── Step 1: Check if Obliguard is installed, install if not ─────────────
    {
      name: 'Install Obliguard agent',
      description: 'Checks whether the ObliguardAgent service exists. If not, downloads and installs the MSI silently.',
      checkScript: {
        name: 'Check Obliguard installed (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service ObliguardAgent -ErrorAction SilentlyContinue',
          'if ($svc) { Write-Host "ObliguardAgent service found"; exit 0 }',
          'else { Write-Host "ObliguardAgent service not found"; exit 1 }',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Obliguard (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$ErrorActionPreference = "Stop"',
          '',
          '$serverUrl = "{{SERVER_URL}}"',
          '$apiKey   = "{{API_KEY}}"',
          '$policyId = "{{POLICY_ID}}"',
          '',
          'if (-not $serverUrl) { Write-Error "SERVER_URL variable is required"; exit 1 }',
          'if (-not $apiKey)   { Write-Error "API_KEY variable is required"; exit 1 }',
          '',
          '$msiPath = Join-Path $env:TEMP "obliguard-agent.msi"',
          '',
          '# Download installer',
          'try {',
          '    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
          '    $wc = New-Object System.Net.WebClient',
          '    $wc.Headers.Add("X-Api-Key", $apiKey)',
          '    $wc.DownloadFile("$serverUrl/api/agent/installer/obliguard-windows.msi", $msiPath)',
          '} catch {',
          '    Invoke-WebRequest -Uri "$serverUrl/api/agent/installer/obliguard-windows.msi" `',
          '        -Headers @{"X-Api-Key" = $apiKey} `',
          '        -OutFile $msiPath -UseBasicParsing',
          '}',
          '',
          'if (-not (Test-Path $msiPath)) { Write-Error "Download failed"; exit 1 }',
          '',
          '# Build MSI arguments',
          '$msiArgs = "/i `"$msiPath`" SERVERURL=`"$serverUrl`" APIKEY=`"$apiKey`""',
          'if ($policyId) { $msiArgs += " POLICYID=`"$policyId`"" }',
          '$msiArgs += " /quiet /norestart /l*v `"$env:TEMP\\obliguard-install.log`""',
          '',
          '$proc = Start-Process msiexec -ArgumentList $msiArgs -Wait -PassThru',
          '',
          '# Retry on mutex error 1618',
          '$retries = 0',
          'while ($proc.ExitCode -eq 1618 -and $retries -lt 5) {',
          '    $retries++',
          '    Write-Host "MSI mutex busy, retry $retries/5..."',
          '    Start-Sleep -Seconds 15',
          '    $proc = Start-Process msiexec -ArgumentList $msiArgs -Wait -PassThru',
          '}',
          '',
          'Remove-Item $msiPath -ErrorAction SilentlyContinue',
          '',
          'if ($proc.ExitCode -ne 0) {',
          '    Write-Error "MSI install failed with exit code $($proc.ExitCode)"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Obliguard agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Obliguard service running',
      description: 'Confirms the ObliguardAgent service is in Running state after installation.',
      checkScript: {
        name: 'Check Obliguard running (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service ObliguardAgent -ErrorAction SilentlyContinue',
          'if ($svc -and $svc.Status -eq "Running") {',
          '    Write-Host "ObliguardAgent is running"',
          '    exit 0',
          '}',
          '',
          '# Try starting it',
          'if ($svc) {',
          '    Start-Service ObliguardAgent -ErrorAction SilentlyContinue',
          '    Start-Sleep -Seconds 5',
          '    $svc.Refresh()',
          '    if ($svc.Status -eq "Running") { Write-Host "ObliguardAgent started"; exit 0 }',
          '}',
          '',
          'Write-Host "ObliguardAgent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },

    // ── Step 3: Verify security policy applied ─────────────────────────────
    {
      name: 'Verify security policy applied',
      description: 'Checks that the Obliguard agent has received and applied its security policy from the server.',
      checkScript: {
        name: 'Check Obliguard policy (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$configPath = "$env:ProgramData\\ObliguardAgent\\policy.json"',
          '',
          'if (-not (Test-Path $configPath)) {',
          '    Write-Host "Policy file not found — agent may not have synced yet"',
          '    exit 1',
          '}',
          '',
          'try {',
          '    $policy = Get-Content $configPath -Raw | ConvertFrom-Json',
          '    if ($policy.appliedAt) {',
          '        Write-Host "Policy applied at $($policy.appliedAt)"',
          '        exit 0',
          '    }',
          '    Write-Host "Policy file exists but not yet applied"',
          '    exit 1',
          '} catch {',
          '    Write-Host "Failed to parse policy file: $_"',
          '    exit 1',
          '}',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Force Obliguard policy sync (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$obliguardCli = "$env:ProgramFiles\\ObliguardAgent\\obliguard-agent.exe"',
          '',
          'if (-not (Test-Path $obliguardCli)) {',
          '    Write-Error "Obliguard agent binary not found"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Forcing policy sync..."',
          '& $obliguardCli policy --sync --timeout 60',
          '',
          'if ($LASTEXITCODE -ne 0) {',
          '    Write-Error "Policy sync failed with exit code $LASTEXITCODE"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Policy sync completed"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 120,
      retryCount: 2,
    },
  ],
};
