import type { ScenarioTemplate } from './index';

export const deployObliviewUnix: ScenarioTemplate = {
  name: 'Deploy Obliview Agent — Linux / macOS',
  description: 'Installs and configures the Obliview remote viewing agent on Linux and macOS devices. Uses the appropriate installer for the detected platform.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
  },
  timeoutSeconds: 900,
  steps: [
    // ── Step 1: Check if Obliview is installed, install if not ──────────────
    {
      name: 'Install Obliview agent',
      description: 'Checks whether the Obliview agent service exists. If not, downloads and runs the installer script.',
      checkScript: {
        name: 'Check Obliview installed (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet obliview-agent 2>/dev/null; then',
          '      echo "obliview-agent service is active"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/obliview-agent ]; then',
          '      echo "obliview-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.obliview.agent >/dev/null 2>&1; then',
          '      echo "com.obliview.agent service found"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/obliview-agent ]; then',
          '      echo "obliview-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Obliview agent not found"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Obliview (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'resolve',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'SERVER_URL="{{SERVER_URL}}"',
          'API_KEY="{{API_KEY}}"',
          '',
          'if [ -z "$SERVER_URL" ]; then echo "ERROR: SERVER_URL is required" >&2; exit 1; fi',
          'if [ -z "$API_KEY" ]; then echo "ERROR: API_KEY is required" >&2; exit 1; fi',
          '',
          'OS="$(uname -s)"',
          '',
          'case "$OS" in',
          '  Linux)',
          '    echo "Installing Obliview agent on Linux..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/obliview-linux" | sudo bash',
          '    ;;',
          '  Darwin)',
          '    echo "Installing Obliview agent on macOS..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/obliview-macos" | sudo bash',
          '    ;;',
          '  *)',
          '    echo "Unsupported platform: $OS" >&2',
          '    exit 1',
          '    ;;',
          'esac',
          '',
          'echo "Obliview agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Obliview service running',
      description: 'Confirms the Obliview agent service is running after installation.',
      checkScript: {
        name: 'Check Obliview running (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet obliview-agent 2>/dev/null; then',
          '      echo "obliview-agent is running"',
          '      exit 0',
          '    fi',
          '    # Attempt to start',
          '    sudo systemctl start obliview-agent 2>/dev/null || true',
          '    sleep 3',
          '    if systemctl is-active --quiet obliview-agent 2>/dev/null; then',
          '      echo "obliview-agent started successfully"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.obliview.agent >/dev/null 2>&1; then',
          '      echo "com.obliview.agent is running"',
          '      exit 0',
          '    fi',
          '    # Attempt to load',
          '    sudo launchctl load /Library/LaunchDaemons/com.obliview.agent.plist 2>/dev/null || true',
          '    sleep 3',
          '    if launchctl list com.obliview.agent >/dev/null 2>&1; then',
          '      echo "com.obliview.agent started"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Obliview agent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },
  ],
};
