import type { ScenarioTemplate } from './index';

export const deployObliguardUnix: ScenarioTemplate = {
  name: 'Deploy Obliguard Agent — Linux / macOS',
  description: 'Installs and configures the Obliguard endpoint protection agent on Linux and macOS devices. Deploys the agent, verifies it is running, and confirms the security policy is applied.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
    POLICY_ID: '',
  },
  timeoutSeconds: 1200,
  steps: [
    // ── Step 1: Check if Obliguard is installed, install if not ─────────────
    {
      name: 'Install Obliguard agent',
      description: 'Checks whether the Obliguard agent service exists. If not, downloads and runs the installer script.',
      checkScript: {
        name: 'Check Obliguard installed (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet obliguard-agent 2>/dev/null; then',
          '      echo "obliguard-agent service is active"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/obliguard-agent ]; then',
          '      echo "obliguard-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.obliguard.agent >/dev/null 2>&1; then',
          '      echo "com.obliguard.agent service found"',
          '      exit 0',
          '    elif [ -f /usr/local/bin/obliguard-agent ]; then',
          '      echo "obliguard-agent binary found"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Obliguard agent not found"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Obliguard (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'resolve',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'SERVER_URL="{{SERVER_URL}}"',
          'API_KEY="{{API_KEY}}"',
          'POLICY_ID="{{POLICY_ID}}"',
          '',
          'if [ -z "$SERVER_URL" ]; then echo "ERROR: SERVER_URL is required" >&2; exit 1; fi',
          'if [ -z "$API_KEY" ]; then echo "ERROR: API_KEY is required" >&2; exit 1; fi',
          '',
          'OS="$(uname -s)"',
          '',
          '# Build query string with optional policy',
          'QS="key=$API_KEY"',
          'if [ -n "$POLICY_ID" ]; then QS="$QS&policy=$POLICY_ID"; fi',
          '',
          'case "$OS" in',
          '  Linux)',
          '    echo "Installing Obliguard agent on Linux..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/obliguard-linux?$QS" | sudo bash',
          '    ;;',
          '  Darwin)',
          '    echo "Installing Obliguard agent on macOS..."',
          '    curl -fsSL -H "X-Api-Key: $API_KEY" \\',
          '      "$SERVER_URL/api/agent/installer/obliguard-macos?$QS" | sudo bash',
          '    ;;',
          '  *)',
          '    echo "Unsupported platform: $OS" >&2',
          '    exit 1',
          '    ;;',
          'esac',
          '',
          'echo "Obliguard agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Obliguard service running',
      description: 'Confirms the Obliguard agent service is running after installation.',
      checkScript: {
        name: 'Check Obliguard running (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          '',
          'case "$(uname -s)" in',
          '  Linux)',
          '    if systemctl is-active --quiet obliguard-agent 2>/dev/null; then',
          '      echo "obliguard-agent is running"',
          '      exit 0',
          '    fi',
          '    sudo systemctl start obliguard-agent 2>/dev/null || true',
          '    sleep 3',
          '    if systemctl is-active --quiet obliguard-agent 2>/dev/null; then',
          '      echo "obliguard-agent started successfully"',
          '      exit 0',
          '    fi',
          '    ;;',
          '  Darwin)',
          '    if launchctl list com.obliguard.agent >/dev/null 2>&1; then',
          '      echo "com.obliguard.agent is running"',
          '      exit 0',
          '    fi',
          '    sudo launchctl load /Library/LaunchDaemons/com.obliguard.agent.plist 2>/dev/null || true',
          '    sleep 3',
          '    if launchctl list com.obliguard.agent >/dev/null 2>&1; then',
          '      echo "com.obliguard.agent started"',
          '      exit 0',
          '    fi',
          '    ;;',
          'esac',
          '',
          'echo "Obliguard agent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },

    // ── Step 3: Verify security policy applied ─────────────────────────────
    {
      name: 'Verify security policy applied',
      description: 'Checks that the Obliguard agent has received and applied its security policy from the server.',
      checkScript: {
        name: 'Check Obliguard policy (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'check',
        content: [
          '#!/bin/bash',
          '',
          'POLICY_FILE="/var/lib/obliguard-agent/policy.json"',
          '',
          'if [ ! -f "$POLICY_FILE" ]; then',
          '    echo "Policy file not found — agent may not have synced yet"',
          '    exit 1',
          'fi',
          '',
          'if command -v jq >/dev/null 2>&1; then',
          '    if jq -e ".appliedAt" "$POLICY_FILE" >/dev/null 2>&1; then',
          '        APPLIED=$(jq -r ".appliedAt" "$POLICY_FILE")',
          '        echo "Policy applied at $APPLIED"',
          '        exit 0',
          '    fi',
          'elif grep -q \'"appliedAt"\' "$POLICY_FILE" 2>/dev/null; then',
          '    echo "Policy appears to be applied"',
          '    exit 0',
          'fi',
          '',
          'echo "Policy not yet applied"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Force Obliguard policy sync (Unix)',
        platform: 'all',
        runtime: 'bash',
        purpose: 'resolve',
        content: [
          '#!/bin/bash',
          'set -e',
          '',
          'OBLIGUARD_CLI="/usr/local/bin/obliguard-agent"',
          '',
          'if [ ! -x "$OBLIGUARD_CLI" ]; then',
          '    echo "Obliguard agent binary not found" >&2',
          '    exit 1',
          'fi',
          '',
          'echo "Forcing policy sync..."',
          '"$OBLIGUARD_CLI" policy --sync --timeout 60',
          '',
          'echo "Policy sync completed"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 120,
      retryCount: 2,
    },
  ],
};
