import type { ScenarioTemplate } from './index';

export const deployOblimapWindows: ScenarioTemplate = {
  name: 'Deploy Oblimap Agent — Windows',
  description: 'Installs the Oblimap network discovery and topology agent on Windows devices. Deploys the agent, verifies it is running, and triggers an initial network probe.',
  triggerType: 'manual',
  triggerConfig: {},
  targetType: 'device',
  variables: {
    SERVER_URL: '',
    API_KEY: '',
    PROBE_SUBNET: '',
  },
  timeoutSeconds: 1200,
  steps: [
    // ── Step 1: Check if Oblimap is installed, install if not ───────────────
    {
      name: 'Install Oblimap agent',
      description: 'Checks whether the OblimapAgent service exists. If not, downloads and installs the MSI silently.',
      checkScript: {
        name: 'Check Oblimap installed (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service OblimapAgent -ErrorAction SilentlyContinue',
          'if ($svc) { Write-Host "OblimapAgent service found"; exit 0 }',
          'else { Write-Host "OblimapAgent service not found"; exit 1 }',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Install Oblimap (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$ErrorActionPreference = "Stop"',
          '',
          '$serverUrl = "{{SERVER_URL}}"',
          '$apiKey   = "{{API_KEY}}"',
          '',
          'if (-not $serverUrl) { Write-Error "SERVER_URL variable is required"; exit 1 }',
          'if (-not $apiKey)   { Write-Error "API_KEY variable is required"; exit 1 }',
          '',
          '$msiPath = Join-Path $env:TEMP "oblimap-agent.msi"',
          '',
          '# Download installer',
          'try {',
          '    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12',
          '    $wc = New-Object System.Net.WebClient',
          '    $wc.Headers.Add("X-Api-Key", $apiKey)',
          '    $wc.DownloadFile("$serverUrl/api/agent/installer/oblimap-windows.msi", $msiPath)',
          '} catch {',
          '    Invoke-WebRequest -Uri "$serverUrl/api/agent/installer/oblimap-windows.msi" `',
          '        -Headers @{"X-Api-Key" = $apiKey} `',
          '        -OutFile $msiPath -UseBasicParsing',
          '}',
          '',
          'if (-not (Test-Path $msiPath)) { Write-Error "Download failed"; exit 1 }',
          '',
          '# Silent install',
          '$args = "/i `"$msiPath`" SERVERURL=`"$serverUrl`" APIKEY=`"$apiKey`" /quiet /norestart /l*v `"$env:TEMP\\oblimap-install.log`""',
          '$proc = Start-Process msiexec -ArgumentList $args -Wait -PassThru',
          '',
          '# Retry on mutex error 1618',
          '$retries = 0',
          'while ($proc.ExitCode -eq 1618 -and $retries -lt 5) {',
          '    $retries++',
          '    Write-Host "MSI mutex busy, retry $retries/5..."',
          '    Start-Sleep -Seconds 15',
          '    $proc = Start-Process msiexec -ArgumentList $args -Wait -PassThru',
          '}',
          '',
          'Remove-Item $msiPath -ErrorAction SilentlyContinue',
          '',
          'if ($proc.ExitCode -ne 0) {',
          '    Write-Error "MSI install failed with exit code $($proc.ExitCode)"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Oblimap agent installed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 300,
      retryCount: 1,
    },

    // ── Step 2: Verify service is running ──────────────────────────────────
    {
      name: 'Verify Oblimap service running',
      description: 'Confirms the OblimapAgent service is in Running state after installation.',
      checkScript: {
        name: 'Check Oblimap running (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '$svc = Get-Service OblimapAgent -ErrorAction SilentlyContinue',
          'if ($svc -and $svc.Status -eq "Running") {',
          '    Write-Host "OblimapAgent is running"',
          '    exit 0',
          '}',
          '',
          '# Try starting it',
          'if ($svc) {',
          '    Start-Service OblimapAgent -ErrorAction SilentlyContinue',
          '    Start-Sleep -Seconds 5',
          '    $svc.Refresh()',
          '    if ($svc.Status -eq "Running") { Write-Host "OblimapAgent started"; exit 0 }',
          '}',
          '',
          'Write-Host "OblimapAgent is not running"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: null,
      timeoutSeconds: 60,
      retryCount: 2,
    },

    // ── Step 3: Run initial network probe ──────────────────────────────────
    {
      name: 'Run initial network probe',
      description: 'Triggers an initial network discovery scan. If PROBE_SUBNET is set, scans that subnet; otherwise performs auto-discovery of local subnets.',
      checkScript: {
        name: 'Check Oblimap probe config (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'check',
        content: [
          '# Check if a probe has already been completed',
          '$configPath = "$env:ProgramData\\OblimapAgent\\probe-status.json"',
          'if (Test-Path $configPath) {',
          '    $status = Get-Content $configPath -Raw | ConvertFrom-Json',
          '    if ($status.lastProbeSuccess) {',
          '        Write-Host "Initial probe already completed"',
          '        exit 0',
          '    }',
          '}',
          'Write-Host "No successful probe found"',
          'exit 1',
        ].join('\n'),
      },
      resolveScript: {
        name: 'Run Oblimap probe (Windows)',
        platform: 'windows',
        runtime: 'powershell',
        purpose: 'resolve',
        content: [
          '$ErrorActionPreference = "Stop"',
          '',
          '$probeSubnet = "{{PROBE_SUBNET}}"',
          '$oblimapCli = "$env:ProgramFiles\\OblimapAgent\\oblimap-agent.exe"',
          '',
          'if (-not (Test-Path $oblimapCli)) {',
          '    Write-Error "Oblimap agent binary not found at $oblimapCli"',
          '    exit 1',
          '}',
          '',
          'if ($probeSubnet) {',
          '    Write-Host "Running probe on subnet: $probeSubnet"',
          '    & $oblimapCli probe --subnet "$probeSubnet" --timeout 120',
          '} else {',
          '    Write-Host "Running auto-discovery probe..."',
          '    & $oblimapCli probe --auto-discover --timeout 120',
          '}',
          '',
          'if ($LASTEXITCODE -ne 0) {',
          '    Write-Error "Probe failed with exit code $LASTEXITCODE"',
          '    exit 1',
          '}',
          '',
          'Write-Host "Network probe completed successfully"',
          'exit 0',
        ].join('\n'),
      },
      timeoutSeconds: 180,
      retryCount: 1,
    },
  ],
};
