package tools.obli.proofs

import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase

/** Proof 3: Room entities / DAO generated by KSP2 (v1.1 offline cache, design doc §10.4). */
@Entity(tableName = "device_snapshot", primaryKeys = ["serverId", "deviceId"])
data class DeviceSnapshot(
    val serverId: String,
    val deviceId: Long,
    val name: String,
    val status: String,
    val fetchedAt: Long,
)

@Entity(tableName = "note")
data class Note(@PrimaryKey(autoGenerate = true) val id: Long = 0, val text: String)

@Dao
interface DeviceSnapshotDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(rows: List<DeviceSnapshot>)

    @Query("SELECT * FROM device_snapshot WHERE serverId = :serverId ORDER BY name")
    suspend fun forServer(serverId: String): List<DeviceSnapshot>

    @Query("DELETE FROM device_snapshot WHERE serverId = :serverId")
    suspend fun purgeServer(serverId: String)
}

@Database(entities = [DeviceSnapshot::class, Note::class], version = 1, exportSchema = false)
abstract class ProofDatabase : RoomDatabase() {
    abstract fun devices(): DeviceSnapshotDao
}
