import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const hipaaRules: ComplianceRule[] = [

  // ─── §164.308 Garanties administratives ──────────────────────────────────────

  r('hipaa-308-a-1-ii-B', {
    name: 'Analyse de risque — Windows Defender actif (évaluation des vulnérabilités) [§164.308(a)(1)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WinDefend',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-Service -Name 'WinDefend' -StartupType Automatic; Start-Service -Name 'WinDefend'",
  }),
  r('hipaa-308-a-1-ii-D', {
    name: 'Politiques documentées — Windows Update activé (réduction des risques) [§164.308(a)(1)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name 'NoAutoUpdate' -Value 0 -Type DWord",
  }),
  r('hipaa-308-a-2', {
    name: 'Accès autorisés seulement — UAC activé [§164.308(a)(2)]',
    category: 'Administrative Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name 'EnableLUA' -Value 1 -Type DWord",
  }),
  r('hipaa-308-a-3-ii-A', {
    name: 'Vérification du personnel — journal des connexions activé [§164.308(a)(3)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-308-a-3-ii-C', {
    name: 'Procédures de fin d\'emploi — comptes inactifs désactivés [§164.308(a)(3)(ii)(C)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Disable-LocalUser",
  }),
  r('hipaa-308-a-4-ii-A', {
    name: 'Moindre privilège — membres du groupe Administrators limités [§164.308(a)(4)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group "Administrators" | Measure-Object).Count',
    expected: '3',
    operator: 'lt',
    severity: 'high',
  }),
  r('hipaa-308-a-4-ii-B', {
    name: 'Demandes d\'accès — compte Administrateur intégré désactivé [§164.308(a)(4)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Disable-LocalUser -Name 'Administrator'",
  }),
  r('hipaa-308-a-5-ii-B', {
    name: 'Protection anti-malware — Defender antivirus activé [§164.308(a)(5)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-MpPreference -DisableRealtimeMonitoring $false; Start-Service -Name 'WinDefend'",
  }),
  r('hipaa-308-a-5-ii-B-2', {
    name: 'Protection en temps réel — Defender protection en temps réel active [§164.308(a)(5)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-MpPreference -DisableRealtimeMonitoring $false",
  }),
  r('hipaa-308-a-5-ii-C', {
    name: 'Surveillance des connexions — audit des connexions activé [§164.308(a)(5)(ii)(C)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-308-a-5-ii-D', {
    name: 'Gestion des mots de passe — longueur minimum 12 caractères [§164.308(a)(5)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "$inf = \"$env:TEMP\\secpol_hipaa308d.inf\"; $db = \"$env:TEMP\\secpol_hipaa308d.sdb\"; secedit /export /cfg $inf /quiet; $v = (Select-String -Path $inf -Pattern '^MinimumPasswordLength\\s*=\\s*(\\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value }); Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue; $v",
    expected: '12',
    operator: 'gt',
    severity: 'critical',
    remediationScript: "$inf = \"$env:TEMP\\secpol_hipaa308d.inf\"; $db = \"$env:TEMP\\secpol_hipaa308d.sdb\"; secedit /export /cfg $inf /quiet; (Get-Content $inf) -replace '^(MinimumPasswordLength\\s*=\\s*).*', '${1}12' | Set-Content $inf; secedit /configure /db $db /cfg $inf /areas SECURITYPOLICY /quiet; Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue",
  }),
  r('hipaa-308-a-5-ii-D-2', {
    name: 'Gestion des mots de passe — complexité requise activée [§164.308(a)(5)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa" -Name "PasswordComplexity" -ErrorAction SilentlyContinue).PasswordComplexity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name 'PasswordComplexity' -Value 1 -Type DWord",
  }),
  r('hipaa-308-a-6-ii', {
    name: 'Réponse aux incidents — journal des événements système activé [§164.308(a)(6)(ii)]',
    category: 'Administrative Safeguards',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-Service -Name 'EventLog' -StartupType Automatic; Start-Service -Name 'EventLog'",
  }),
  r('hipaa-308-a-7-ii-A', {
    name: 'Plan de sauvegarde — service de sauvegarde Windows configuré [§164.308(a)(7)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wbengine -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
    remediationScript: "Set-Service -Name 'wbengine' -StartupType Manual",
  }),
  r('hipaa-308-a-8', {
    name: 'Révision des activités — taille du journal de sécurité ≥ 192 Mo [§164.308(a)(8)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
    remediationScript: "wevtutil sl Security /ms:201326592",
  }),

  // ─── §164.310 Garanties physiques ─────────────────────────────────────────────

  r('hipaa-310-a-2-ii', {
    name: 'Journaux d\'accès physique — audit d\'ouverture de session activé [§164.310(a)(2)(ii)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-310-b-1', {
    name: 'Utilisation des postes — verrouillage automatique de session configuré [§164.310(b)]',
    category: 'Physical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKCU:\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'ScreenSaveTimeOut' -Value '900'",
  }),
  r('hipaa-310-b-2', {
    name: 'Postes de travail — économiseur d\'écran protégé par mot de passe [§164.310(b)]',
    category: 'Physical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKCU:\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'ScreenSaverIsSecure' -Value '1'",
  }),
  r('hipaa-310-c-2-i', {
    name: 'Disposition des médias — BitLocker activé (chiffrement avant réutilisation) [§164.310(c)(2)(i)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Get-BitLockerVolume -EA SilentlyContinue | Where-Object { $_.ProtectionStatus -ne 'On' -and $_.VolumeType -ne 'Unknown' } | ForEach-Object { Enable-BitLocker -MountPoint $_.MountPoint -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -SkipHardwareTest -EA SilentlyContinue }",
  }),
  r('hipaa-310-c-2-ii', {
    name: 'Réutilisation des médias — méthode de chiffrement BitLocker AES 256 bits [§164.310(c)(2)(ii)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).EncryptionMethod',
    expected: 'Aes256',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── §164.312 Garanties techniques ────────────────────────────────────────────

  r('hipaa-312-a-1', {
    name: 'Contrôles d\'accès techniques — UAC activé [§164.312(a)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name 'EnableLUA' -Value 1 -Type DWord",
  }),
  r('hipaa-312-a-2-i', {
    name: 'ID unique par utilisateur — compte Invité désactivé (pas de comptes partagés) [§164.312(a)(2)(i)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Disable-LocalUser -Name 'Guest'",
  }),
  r('hipaa-312-a-2-iii', {
    name: 'Déconnexion automatique — délai d\'inactivité ≤ 15 minutes [§164.312(a)(2)(iii)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKCU:\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'ScreenSaveTimeOut' -Value '900'",
  }),
  r('hipaa-312-a-2-iv', {
    name: 'Chiffrement des ePHI — BitLocker actif sur tous les lecteurs [§164.312(a)(2)(iv)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Get-BitLockerVolume -EA SilentlyContinue | Where-Object { $_.ProtectionStatus -ne 'On' -and $_.VolumeType -ne 'Unknown' } | ForEach-Object { Enable-BitLocker -MountPoint $_.MountPoint -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -SkipHardwareTest -EA SilentlyContinue }",
  }),
  r('hipaa-312-b', {
    name: 'Mécanismes d\'audit — base d\'audit activée [§164.312(b)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name 'AuditBaseObjects' -Value 1 -Type DWord",
  }),
  r('hipaa-312-b-2', {
    name: 'Audit d\'accès aux objets — activé (Success and Failure) [§164.312(b)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-312-d', {
    name: 'Authentification des utilisateurs — UAC actif, authentification requise [§164.312(d)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name 'EnableLUA' -Value 1 -Type DWord",
  }),
  r('hipaa-312-e-1-tls10', {
    name: 'Chiffrement en transit — TLS 1.0 désactivé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name 'Enabled' -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name 'DisabledByDefault' -Value 1 -Type DWord",
  }),
  r('hipaa-312-e-1-tls11', {
    name: 'Chiffrement en transit — TLS 1.1 désactivé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name 'Enabled' -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name 'DisabledByDefault' -Value 1 -Type DWord",
  }),
  r('hipaa-312-e-1-tls12', {
    name: 'Chiffrement en transit — TLS 1.2 activé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Name 'Enabled' -Value 1 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Name 'DisabledByDefault' -Value 0 -Type DWord",
  }),

  // ─── Contrôles techniques Windows spécifiques HIPAA ─────────────────────────

  r('hipaa-tech-1', {
    name: 'BitLocker — chiffrement des ePHI au repos activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Get-BitLockerVolume -EA SilentlyContinue | Where-Object { $_.ProtectionStatus -ne 'On' -and $_.VolumeType -ne 'Unknown' } | ForEach-Object { Enable-BitLocker -MountPoint $_.MountPoint -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -SkipHardwareTest -EA SilentlyContinue }",
  }),
  r('hipaa-tech-2', {
    name: 'Pare-feu Windows — activé sur tous les profils [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile | Where-Object { $_.Enabled -ne $true }).Count',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True",
  }),
  r('hipaa-tech-3', {
    name: 'Antivirus/Defender — activé et à jour [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-MpPreference -DisableRealtimeMonitoring $false; Start-Service -Name 'WinDefend'",
  }),
  r('hipaa-tech-4', {
    name: 'Journalisation des événements de sécurité — activée [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "wevtutil sl Security /e:true",
  }),
  r('hipaa-tech-5', {
    name: 'Taille du journal de sécurité — ≥ 192 Mo [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
    remediationScript: "wevtutil sl Security /ms:201326592",
  }),
  r('hipaa-tech-6', {
    name: 'Verrouillage automatique de session — ≤ 15 minutes [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKCU:\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'ScreenSaveTimeOut' -Value '900'",
  }),
  r('hipaa-tech-7', {
    name: 'Mot de passe écran de veille — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKCU:\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\Control Panel\\Desktop' -Name 'ScreenSaverIsSecure' -Value '1'",
  }),
  r('hipaa-tech-8', {
    name: 'UAC — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name 'EnableLUA' -Value 1 -Type DWord",
  }),
  r('hipaa-tech-9', {
    name: 'Windows Update automatique — configuré [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '3',
    operator: 'gt',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name 'AUOptions' -Value 4 -Type DWord",
  }),
  r('hipaa-tech-10', {
    name: 'TLS 1.0 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name 'Enabled' -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name 'DisabledByDefault' -Value 1 -Type DWord",
  }),
  r('hipaa-tech-11', {
    name: 'TLS 1.1 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name 'Enabled' -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name 'DisabledByDefault' -Value 1 -Type DWord",
  }),
  r('hipaa-tech-12', {
    name: 'Audit des connexions — réussies et échouées activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-tech-13', {
    name: 'Audit de la gestion des comptes — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-tech-14', {
    name: 'PowerShell Script Block Logging — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Name 'EnableScriptBlockLogging' -Value 1 -Type DWord",
  }),
  r('hipaa-tech-15', {
    name: 'Accès RDP — NLA requis [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -Name 'UserAuthentication' -Value 1 -Type DWord",
  }),
  r('hipaa-tech-16', {
    name: 'Compte administrateur local — désactivé ou renommé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Disable-LocalUser -Name 'Administrator'",
  }),
  r('hipaa-tech-17', {
    name: 'Compte invité local — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Disable-LocalUser -Name 'Guest'",
  }),
  r('hipaa-tech-18', {
    name: 'SMBv1 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force",
  }),
  r('hipaa-tech-19', {
    name: 'Stratégie de mot de passe — longueur minimum 12 caractères [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "$inf = \"$env:TEMP\\secpol_tech19.inf\"; $db = \"$env:TEMP\\secpol_tech19.sdb\"; secedit /export /cfg $inf /quiet; $v = (Select-String -Path $inf -Pattern '^MinimumPasswordLength\\s*=\\s*(\\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value }); Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue; $v",
    expected: '12',
    operator: 'gt',
    severity: 'critical',
    remediationScript: "$inf = \"$env:TEMP\\secpol_tech19.inf\"; $db = \"$env:TEMP\\secpol_tech19.sdb\"; secedit /export /cfg $inf /quiet; (Get-Content $inf) -replace '^(MinimumPasswordLength\\s*=\\s*).*', '${1}12' | Set-Content $inf; secedit /configure /db $db /cfg $inf /areas SECURITYPOLICY /quiet; Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue",
  }),
  r('hipaa-tech-20', {
    name: 'Stratégie de verrouillage de compte — seuil ≤ 5 tentatives [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "$inf = \"$env:TEMP\\secpol_tech20.inf\"; $db = \"$env:TEMP\\secpol_tech20.sdb\"; secedit /export /cfg $inf /quiet; $v = (Select-String -Path $inf -Pattern '^LockoutBadCount\\s*=\\s*(\\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value }); Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue; $v",
    expected: '5',
    operator: 'lt',
    severity: 'critical',
    remediationScript: "$inf = \"$env:TEMP\\secpol_tech20.inf\"; $db = \"$env:TEMP\\secpol_tech20.sdb\"; secedit /export /cfg $inf /quiet; (Get-Content $inf) -replace '^(LockoutBadCount\\s*=\\s*).*', '${1}5' | Set-Content $inf; secedit /configure /db $db /cfg $inf /areas SECURITYPOLICY /quiet; Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue",
  }),

  // ─── Contrôles Windows complémentaires HIPAA ──────────────────────────────────

  r('hipaa-win-01', {
    name: 'TLS 1.2 — activé côté serveur (chiffrement des transmissions ePHI) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Name 'Enabled' -Value 1 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server' -Name 'DisabledByDefault' -Value 0 -Type DWord",
  }),
  r('hipaa-win-02', {
    name: 'SMBv2 — protocole de partage sécurisé activé [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB2Protocol',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-SmbServerConfiguration -EnableSMB2Protocol $true -Force",
  }),
  r('hipaa-win-03', {
    name: 'Signature SMB — requise côté serveur (intégrité des transmissions) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).RequireSecuritySignature',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-SmbServerConfiguration -RequireSecuritySignature $true -Force",
  }),
  r('hipaa-win-04', {
    name: 'Chiffrement SMB — activé pour les partages sensibles [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EncryptData',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-SmbServerConfiguration -EncryptData $true -Force",
  }),
  r('hipaa-win-05', {
    name: 'NTLMv2 — niveau de compatibilité LAN Manager ≥ 3 [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '3',
    operator: 'gt',
    severity: 'critical',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name 'LmCompatibilityLevel' -Value 5 -Type DWord",
  }),
  r('hipaa-win-06', {
    name: 'WDigest — stockage des mots de passe en clair désactivé [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest|UseLogonCredential',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: "New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest' -Name 'UseLogonCredential' -Value 0 -Type DWord",
  }),
  r('hipaa-win-07', {
    name: 'LSA — protection du processus activée (protection des ePHI en mémoire) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name 'RunAsPPL' -Value 1 -Type DWord",
  }),
  r('hipaa-win-08', {
    name: 'Audit des créations de processus — activé [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('hipaa-win-09', {
    name: 'Audit des modifications de stratégie — activé (traçabilité des changements) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-win-10', {
    name: 'Audit d\'accès aux objets — système de fichiers (traçabilité des accès ePHI) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('hipaa-win-11', {
    name: 'Historique des mots de passe — 5 derniers minimum [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "$inf = \"$env:TEMP\\secpol_win11.inf\"; $db = \"$env:TEMP\\secpol_win11.sdb\"; secedit /export /cfg $inf /quiet; $v = (Select-String -Path $inf -Pattern '^PasswordHistorySize\\s*=\\s*(\\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value }); Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue; $v",
    expected: '5',
    operator: 'gt',
    severity: 'high',
    remediationScript: "$inf = \"$env:TEMP\\secpol_win11.inf\"; $db = \"$env:TEMP\\secpol_win11.sdb\"; secedit /export /cfg $inf /quiet; (Get-Content $inf) -replace '^(PasswordHistorySize\\s*=\\s*).*', '${1}5' | Set-Content $inf; secedit /configure /db $db /cfg $inf /areas SECURITYPOLICY /quiet; Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue",
  }),
  r('hipaa-win-12', {
    name: 'Stratégie de verrouillage — durée ≥ 30 minutes [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "$inf = \"$env:TEMP\\secpol_win12.inf\"; $db = \"$env:TEMP\\secpol_win12.sdb\"; secedit /export /cfg $inf /quiet; $v = (Select-String -Path $inf -Pattern '^LockoutDuration\\s*=\\s*(\\d+)' | ForEach-Object { $_.Matches[0].Groups[1].Value }); Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue; $v",
    expected: '30',
    operator: 'gt',
    severity: 'high',
    remediationScript: "$inf = \"$env:TEMP\\secpol_win12.inf\"; $db = \"$env:TEMP\\secpol_win12.sdb\"; secedit /export /cfg $inf /quiet; (Get-Content $inf) -replace '^(LockoutDuration\\s*=\\s*).*', '${1}30' | Set-Content $inf; secedit /configure /db $db /cfg $inf /areas SECURITYPOLICY /quiet; Remove-Item $inf,$db -Force -ErrorAction SilentlyContinue",
  }),
  r('hipaa-win-13', {
    name: 'DEP — Data Execution Prevention activée (protection contre l\'exécution de code malveillant) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(bcdedit /enum {current} | Select-String "nx").ToString()',
    expected: 'AlwaysOn',
    operator: 'contains',
    severity: 'high',
    remediationScript: "bcdedit /set {current} nx AlwaysOn",
  }),
  r('hipaa-win-14', {
    name: 'Windows Defender — protection contre les exploits activée [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).BehaviorMonitorEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: "Set-MpPreference -DisableBehaviorMonitoring $false",
  }),
  r('hipaa-win-15', {
    name: 'Secure Boot — activé (intégrité du démarrage du système) [HIPAA Win]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Confirm-SecureBootUEFI -ErrorAction SilentlyContinue)',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),

];
