import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const hipaaRules: ComplianceRule[] = [

  // ─── §164.308 Garanties administratives ──────────────────────────────────────

  r('hipaa-308-a-1-ii-B', {
    name: 'Analyse de risque — Windows Defender actif (évaluation des vulnérabilités) [§164.308(a)(1)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WinDefend',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-1-ii-D', {
    name: 'Politiques documentées — Windows Update activé (réduction des risques) [§164.308(a)(1)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-2', {
    name: 'Accès autorisés seulement — UAC activé [§164.308(a)(2)]',
    category: 'Administrative Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-3-ii-A', {
    name: 'Vérification du personnel — journal des connexions activé [§164.308(a)(3)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-308-a-3-ii-C', {
    name: 'Procédures de fin d\'emploi — comptes inactifs désactivés [§164.308(a)(3)(ii)(C)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-308-a-4-ii-A', {
    name: 'Moindre privilège — membres du groupe Administrators limités [§164.308(a)(4)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group "Administrators" | Measure-Object).Count',
    expected: '3',
    operator: 'lt',
    severity: 'high',
  }),
  r('hipaa-308-a-4-ii-B', {
    name: 'Demandes d\'accès — compte Administrateur intégré désactivé [§164.308(a)(4)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-308-a-5-ii-B', {
    name: 'Protection anti-malware — Defender antivirus activé [§164.308(a)(5)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-5-ii-B-2', {
    name: 'Protection en temps réel — Defender protection en temps réel active [§164.308(a)(5)(ii)(B)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-5-ii-C', {
    name: 'Surveillance des connexions — audit des connexions activé [§164.308(a)(5)(ii)(C)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-308-a-5-ii-D', {
    name: 'Gestion des mots de passe — longueur minimum 12 caractères [§164.308(a)(5)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Minimum password length").ToString().Split(":")[-1].Trim()',
    expected: '12',
    operator: 'gt',
    severity: 'critical',
  }),
  r('hipaa-308-a-5-ii-D-2', {
    name: 'Gestion des mots de passe — complexité requise activée [§164.308(a)(5)(ii)(D)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa" -Name "PasswordComplexity" -ErrorAction SilentlyContinue).PasswordComplexity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-308-a-6-ii', {
    name: 'Réponse aux incidents — journal des événements système activé [§164.308(a)(6)(ii)]',
    category: 'Administrative Safeguards',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-308-a-7-ii-A', {
    name: 'Plan de sauvegarde — service de sauvegarde Windows configuré [§164.308(a)(7)(ii)(A)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wbengine -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
  }),
  r('hipaa-308-a-8', {
    name: 'Révision des activités — taille du journal de sécurité ≥ 192 Mo [§164.308(a)(8)]',
    category: 'Administrative Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
  }),

  // ─── §164.310 Garanties physiques ─────────────────────────────────────────────

  r('hipaa-310-a-2-ii', {
    name: 'Journaux d\'accès physique — audit d\'ouverture de session activé [§164.310(a)(2)(ii)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-310-b-1', {
    name: 'Utilisation des postes — verrouillage automatique de session configuré [§164.310(b)]',
    category: 'Physical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
  }),
  r('hipaa-310-b-2', {
    name: 'Postes de travail — économiseur d\'écran protégé par mot de passe [§164.310(b)]',
    category: 'Physical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-310-c-2-i', {
    name: 'Disposition des médias — BitLocker activé (chiffrement avant réutilisation) [§164.310(c)(2)(i)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-310-c-2-ii', {
    name: 'Réutilisation des médias — méthode de chiffrement BitLocker AES 256 bits [§164.310(c)(2)(ii)]',
    category: 'Physical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).EncryptionMethod',
    expected: 'Aes256',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── §164.312 Garanties techniques ────────────────────────────────────────────

  r('hipaa-312-a-1', {
    name: 'Contrôles d\'accès techniques — UAC activé [§164.312(a)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-a-2-i', {
    name: 'ID unique par utilisateur — compte Invité désactivé (pas de comptes partagés) [§164.312(a)(2)(i)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-a-2-iii', {
    name: 'Déconnexion automatique — délai d\'inactivité ≤ 15 minutes [§164.312(a)(2)(iii)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
  }),
  r('hipaa-312-a-2-iv', {
    name: 'Chiffrement des ePHI — BitLocker actif sur le lecteur système [§164.312(a)(2)(iv)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-b', {
    name: 'Mécanismes d\'audit — base d\'audit activée [§164.312(b)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-312-b-2', {
    name: 'Audit d\'accès aux objets — activé (Success and Failure) [§164.312(b)]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"File System" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-312-d', {
    name: 'Authentification des utilisateurs — UAC actif, authentification requise [§164.312(d)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-e-1-tls10', {
    name: 'Chiffrement en transit — TLS 1.0 désactivé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-e-1-tls11', {
    name: 'Chiffrement en transit — TLS 1.1 désactivé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-312-e-1-tls12', {
    name: 'Chiffrement en transit — TLS 1.2 activé [§164.312(e)(1)]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),

  // ─── Contrôles techniques Windows spécifiques HIPAA ─────────────────────────

  r('hipaa-tech-1', {
    name: 'BitLocker — chiffrement des ePHI au repos activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-2', {
    name: 'Pare-feu Windows — activé sur tous les profils [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile | Where-Object { $_.Enabled -ne $true }).Count',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-3', {
    name: 'Antivirus/Defender — activé et à jour [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-4', {
    name: 'Journalisation des événements de sécurité — activée [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-5', {
    name: 'Taille du journal de sécurité — ≥ 192 Mo [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
  }),
  r('hipaa-tech-6', {
    name: 'Verrouillage automatique de session — ≤ 15 minutes [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
  }),
  r('hipaa-tech-7', {
    name: 'Mot de passe écran de veille — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-tech-8', {
    name: 'UAC — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-9', {
    name: 'Windows Update automatique — configuré [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '3',
    operator: 'gt',
    severity: 'high',
  }),
  r('hipaa-tech-10', {
    name: 'TLS 1.0 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-11', {
    name: 'TLS 1.1 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-12', {
    name: 'Audit des connexions — réussies et échouées activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-13', {
    name: 'Audit de la gestion des comptes — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-tech-14', {
    name: 'PowerShell Script Block Logging — activé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-tech-15', {
    name: 'Accès RDP — NLA requis [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-16', {
    name: 'Compte administrateur local — désactivé ou renommé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-tech-17', {
    name: 'Compte invité local — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('hipaa-tech-18', {
    name: 'SMBv1 — désactivé [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('hipaa-tech-19', {
    name: 'Stratégie de mot de passe — longueur minimum 12 caractères [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Minimum password length").ToString().Split(":")[-1].Trim()',
    expected: '12',
    operator: 'gt',
    severity: 'critical',
  }),
  r('hipaa-tech-20', {
    name: 'Stratégie de verrouillage de compte — seuil ≤ 5 tentatives [HIPAA Tech]',
    category: 'Technical Safeguards',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Lockout threshold").ToString().Split(":")[-1].Trim()',
    expected: '5',
    operator: 'lt',
    severity: 'critical',
  }),

];
