import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const linuxBaselineRules: ComplianceRule[] = [

  // ── FILESYSTEM / PARTITIONS ──────────────────────────────────────────────────

  r('lsb-001', {
    name: 'Système de fichiers — /tmp monté avec noexec',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep ' /tmp ' | grep -q noexec && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Ubuntu 22.04',
  }),

  r('lsb-002', {
    name: 'Système de fichiers — /tmp monté avec nosuid',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep ' /tmp ' | grep -q nosuid && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-003', {
    name: 'Système de fichiers — /tmp monté avec nodev',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep ' /tmp ' | grep -q nodev && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-004', {
    name: 'Système de fichiers — /var/tmp monté avec noexec, nosuid et nodev',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep ' /var/tmp ' | grep -qE 'noexec' && mount | grep ' /var/tmp ' | grep -qE 'nosuid' && mount | grep ' /var/tmp ' | grep -qE 'nodev' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-005', {
    name: 'Système de fichiers — /dev/shm monté avec noexec',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep '/dev/shm' | grep -q noexec && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-006', {
    name: 'Système de fichiers — bit sticky sur les répertoires accessibles en écriture par tous',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'find / -xdev -type d -perm -0002 -not -perm -1000 2>/dev/null | wc -l',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-007', {
    name: "Système de fichiers — aucun fichier sans propriétaire",
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'find / -xdev \\( -nouser -o -nogroup \\) 2>/dev/null | wc -l',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-008', {
    name: 'Système de fichiers — /home monté sur une partition dédiée',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep -q ' /home ' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-009', {
    name: 'Système de fichiers — /var monté sur une partition dédiée',
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "mount | grep -q ' /var ' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-010', {
    name: "Intégrité — AIDE (contrôle d'intégrité) installé",
    category: 'Filesystem',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'command -v aide &>/dev/null && echo true || echo false',
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  // ── SERVICES DÉSACTIVÉS ──────────────────────────────────────────────────────

  r('lsb-011', {
    name: 'Services — xinetd désactivé ou non installé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled xinetd 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'moderate',
  }),

  r('lsb-012', {
    name: 'Services — serveur Telnet (telnetd) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled telnetd 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'critical',
  }),

  r('lsb-013', {
    name: 'Services — rsh / rlogin / rexec désactivés',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled rsh.socket rlogin.socket rexec.socket 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'critical',
  }),

  r('lsb-014', {
    name: 'Services — ypbind (NIS) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled ypbind 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'high',
  }),

  r('lsb-015', {
    name: 'Services — serveur TFTP désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled tftp 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'high',
  }),

  r('lsb-016', {
    name: 'Services — talk / ntalk désactivés',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled talk ntalk 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-017', {
    name: 'Services — chargen désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled chargen.socket chargen-dgram 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-018', {
    name: 'Services — daytime désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled daytime.socket daytime-dgram 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-019', {
    name: 'Services — echo service désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled echo.socket echo-dgram 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-020', {
    name: 'Services — discard service désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled discard.socket discard-dgram 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-021', {
    name: 'Services — time service désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled time.socket time-dgram 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-022', {
    name: 'Services — avahi-daemon (mDNS) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled avahi-daemon 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'moderate',
  }),

  r('lsb-023', {
    name: 'Services — CUPS (impression) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled cups 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-024', {
    name: 'Services — dhcpd (serveur DHCP) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled dhcpd isc-dhcp-server 2>/dev/null | grep -q enabled && echo enabled || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'moderate',
  }),

  r('lsb-025', {
    name: 'Services — slapd (serveur LDAP) désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled slapd 2>/dev/null || echo disabled",
    expected: 'enabled',
    operator: 'neq',
    severity: 'moderate',
  }),

  // ── RÉSEAU / SYSCTL ──────────────────────────────────────────────────────────

  r('lsb-026', {
    name: 'Réseau — transfert IPv4 (ip_forward) désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.ip_forward',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-027', {
    name: 'Réseau — envoi de redirections ICMP désactivé (all)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.all.send_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-028', {
    name: 'Réseau — envoi de redirections ICMP désactivé (default)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.default.send_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-029', {
    name: "Réseau — acceptation de redirections ICMP désactivée (all)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.all.accept_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-030', {
    name: "Réseau — acceptation de redirections ICMP désactivée (default)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.default.accept_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-031', {
    name: "Réseau — redirections sécurisées désactivées (all)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.all.secure_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-032', {
    name: "Réseau — redirections sécurisées désactivées (default)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.default.secure_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-033', {
    name: 'Réseau — journalisation des paquets martiens activée (all)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.all.log_martians',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-034', {
    name: 'Réseau — journalisation des paquets martiens activée (default)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.default.log_martians',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-035', {
    name: 'Réseau — ignore ping broadcast activé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.icmp_echo_ignore_broadcasts',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-036', {
    name: 'Réseau — ignore des réponses ICMP erronées activé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.icmp_ignore_bogus_error_responses',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-037', {
    name: 'Réseau — filtrage chemin inverse activé (all)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.all.rp_filter',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-038', {
    name: 'Réseau — filtrage chemin inverse activé (default)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.conf.default.rp_filter',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-039', {
    name: 'Réseau — cookies SYN TCP activés (protection SYN flood)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.tcp_syncookies',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-040', {
    name: "Réseau IPv6 — redirections désactivées (all)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv6.conf.all.accept_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-041', {
    name: "Réseau IPv6 — redirections désactivées (default)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv6.conf.default.accept_redirects',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-042', {
    name: "Réseau IPv6 — acceptation des annonces routeur désactivée (all)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv6.conf.all.accept_ra',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-043', {
    name: "Réseau IPv6 — acceptation des annonces routeur désactivée (default)",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv6.conf.default.accept_ra',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-044', {
    name: 'Noyau — ASLR activé (randomize_va_space = 2)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n kernel.randomize_va_space',
    expected: '2',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-045', {
    name: 'Noyau — vidage mémoire SUID interdit (suid_dumpable = 0)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n fs.suid_dumpable',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  // ── PARE-FEU ────────────────────────────────────────────────────────────────

  r('lsb-046', {
    name: 'Pare-feu — UFW activé (Ubuntu/Debian)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "ufw status | grep -q 'Status: active' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-047', {
    name: 'Pare-feu — UFW politique par défaut : refuser le trafic entrant',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "ufw status verbose 2>/dev/null | grep 'Default:' | grep -q 'deny (incoming)' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-048', {
    name: 'Pare-feu — firewalld actif (RHEL/Rocky)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'systemctl is-active firewalld 2>/dev/null',
    expected: 'active',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-049', {
    name: 'Pare-feu — au moins un pare-feu actif (iptables ou nftables)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "(iptables -L -n 2>/dev/null | grep -qv 'Chain INPUT (policy ACCEPT)' || nft list ruleset 2>/dev/null | grep -q 'type filter') && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-050', {
    name: 'Pare-feu — politique par défaut DROP (firewalld)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "firewall-cmd --get-default-zone 2>/dev/null | grep -qE 'drop|block' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  // ── SSH ─────────────────────────────────────────────────────────────────────

  r('lsb-051', {
    name: 'SSH — connexion root interdite (PermitRootLogin no)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'permitrootlogin' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-052', {
    name: "SSH — authentification par mot de passe désactivée",
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'passwordauthentication' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-053', {
    name: 'SSH — mots de passe vides interdits (PermitEmptyPasswords no)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'permitemptypasswords' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-054', {
    name: 'SSH — nombre maximal de tentatives ≤ 4 (MaxAuthTries)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'maxauthtries' | awk '{print $2}'",
    expected: '4',
    operator: 'lt',
    severity: 'high',
  }),

  r('lsb-055', {
    name: 'SSH — intervalle de maintien de connexion ≤ 300 s (ClientAliveInterval)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'clientaliveinterval' | awk '{print $2}'",
    expected: '300',
    operator: 'lt',
    severity: 'moderate',
  }),

  r('lsb-056', {
    name: 'SSH — nombre de keepalives ≤ 3 (ClientAliveCountMax)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'clientalivecountmax' | awk '{print $2}'",
    expected: '3',
    operator: 'lt',
    severity: 'moderate',
  }),

  r('lsb-057', {
    name: 'SSH — délai de grâce de connexion ≤ 60 s (LoginGraceTime)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'logingracetime' | awk '{print $2}'",
    expected: '60',
    operator: 'lt',
    severity: 'moderate',
  }),

  r('lsb-058', {
    name: 'SSH — transfert TCP désactivé (AllowTcpForwarding no)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'allowtcpforwarding' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-059', {
    name: 'SSH — redirection X11 désactivée (X11Forwarding no)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'x11forwarding' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-060', {
    name: 'SSH — fichiers .rhosts ignorés (IgnoreRhosts yes)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'ignorerhosts' | awk '{print $2}'",
    expected: 'yes',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-061', {
    name: 'SSH — authentification basée hôte désactivée (HostbasedAuthentication no)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'hostbasedauthentication' | awk '{print $2}'",
    expected: 'no',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-062', {
    name: 'SSH — bannière de connexion configurée (Banner)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i '^banner' | awk '{print $2}'",
    expected: 'none',
    operator: 'neq',
    severity: 'moderate',
  }),

  r('lsb-063', {
    name: 'SSH — algorithmes MAC sans MD5',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i '^macs'",
    expected: 'md5',
    operator: 'not_contains',
    severity: 'high',
  }),

  r('lsb-064', {
    name: 'SSH — chiffrements sans arcfour',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i '^ciphers'",
    expected: 'arcfour',
    operator: 'not_contains',
    severity: 'high',
  }),

  r('lsb-065', {
    name: "SSH — algorithmes d'échange de clés sans Diffie-Hellman group1",
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i '^kexalgorithms'",
    expected: 'diffie-hellman-group1',
    operator: 'not_contains',
    severity: 'high',
  }),

  r('lsb-066', {
    name: 'SSH — nombre de sessions simultanées ≤ 10 (MaxSessions)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'maxsessions' | awk '{print $2}'",
    expected: '10',
    operator: 'lt',
    severity: 'low',
  }),

  r('lsb-067', {
    name: 'SSH — niveau de journalisation INFO ou VERBOSE (LogLevel)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'loglevel' | awk '{print $2}'",
    expected: 'QUIET',
    operator: 'neq',
    severity: 'moderate',
  }),

  r('lsb-068', {
    name: 'SSH — vérification stricte des permissions activée (StrictModes yes)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'strictmodes' | awk '{print $2}'",
    expected: 'yes',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-069', {
    name: 'SSH — intégration PAM activée (UsePAM yes)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i 'usepam' | awk '{print $2}'",
    expected: 'yes',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-070', {
    name: 'SSH — version OpenSSH ≥ 8.0 (pas de protocoles hérités)',
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "ssh -V 2>&1 | grep -oP 'OpenSSH_\\K[0-9]+'",
    expected: '7',
    operator: 'gt',
    severity: 'high',
  }),

  // ── PAM / POLITIQUE DE MOTS DE PASSE ────────────────────────────────────────

  r('lsb-071', {
    name: 'PAM — pam_pwquality configuré pour la complexité des mots de passe',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -q 'pam_pwquality' /etc/pam.d/common-password 2>/dev/null || grep -q 'pam_pwquality' /etc/pam.d/system-auth 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-072', {
    name: 'Mots de passe — longueur minimale ≥ 14 caractères (minlen)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'minlen\\s*=' /etc/security/pwquality.conf 2>/dev/null | grep -oP 'minlen\\s*=\\s*\\K\\d+'",
    expected: '14',
    operator: 'gt',
    severity: 'high',
  }),

  r('lsb-073', {
    name: "Mots de passe — historique ≥ 5 (remember)",
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'remember\\s*=' /etc/pam.d/common-password /etc/pam.d/system-auth 2>/dev/null | grep -oP 'remember=\\K\\d+' | head -1",
    expected: '4',
    operator: 'gt',
    severity: 'moderate',
  }),

  r('lsb-074', {
    name: 'Mots de passe — exigence de chiffres (dcredit)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'dcredit\\s*=\\s*-' /etc/security/pwquality.conf 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-075', {
    name: 'Mots de passe — exigence de majuscules (ucredit)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'ucredit\\s*=\\s*-' /etc/security/pwquality.conf 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-076', {
    name: 'Mots de passe — exigence de minuscules (lcredit)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'lcredit\\s*=\\s*-' /etc/security/pwquality.conf 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-077', {
    name: 'Mots de passe — exigence de caractères spéciaux (ocredit)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'ocredit\\s*=\\s*-' /etc/security/pwquality.conf 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-078', {
    name: "Mots de passe — durée maximale ≤ 90 jours (PASS_MAX_DAYS)",
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'PASS_MAX_DAYS' /etc/login.defs | awk '{print $2}'",
    expected: '90',
    operator: 'lt',
    severity: 'high',
  }),

  r('lsb-079', {
    name: "Mots de passe — durée minimale ≥ 1 jour (PASS_MIN_DAYS)",
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'PASS_MIN_DAYS' /etc/login.defs | awk '{print $2}'",
    expected: '0',
    operator: 'gt',
    severity: 'moderate',
  }),

  r('lsb-080', {
    name: "Mots de passe — avertissement d'expiration ≥ 7 jours (PASS_WARN_AGE)",
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'PASS_WARN_AGE' /etc/login.defs | awk '{print $2}'",
    expected: '6',
    operator: 'gt',
    severity: 'low',
  }),

  r('lsb-081', {
    name: 'Comptes — verrouillage en cas de tentatives échouées (pam_faillock)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -q 'pam_faillock\\|pam_tally2' /etc/pam.d/system-auth /etc/pam.d/password-auth 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-082', {
    name: 'Comptes — seuil de verrouillage ≤ 5 tentatives (deny)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'deny\\s*=' /etc/security/faillock.conf 2>/dev/null | grep -oP 'deny\\s*=\\s*\\K\\d+'",
    expected: '5',
    operator: 'lt',
    severity: 'high',
  }),

  r('lsb-083', {
    name: 'Comptes — durée de déverrouillage ≥ 900 s (unlock_time)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'unlock_time\\s*=' /etc/security/faillock.conf 2>/dev/null | grep -oP 'unlock_time=\\K\\d+'",
    expected: '900',
    operator: 'gt',
    severity: 'moderate',
  }),

  r('lsb-084', {
    name: 'Comptes — compte root verrouillé',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "passwd -S root 2>/dev/null | awk '{print $2}'",
    expected: 'L',
    operator: 'contains',
    severity: 'critical',
  }),

  r('lsb-085', {
    name: 'Comptes — umask par défaut restrictif (027 ou plus strict)',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'UMASK\\s+0[012]7' /etc/login.defs && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ── AUDITD ───────────────────────────────────────────────────────────────────

  r('lsb-086', {
    name: 'Audit — auditd installé et actif',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'systemctl is-active auditd',
    expected: 'active',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-087', {
    name: "Audit — journal d'audit non vide",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%s' /var/log/audit/audit.log 2>/dev/null || echo 0",
    expected: '0',
    operator: 'gt',
    severity: 'high',
  }),

  r('lsb-088', {
    name: "Audit — action sur fichier journal plein : conserver (max_log_file_action)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'max_log_file_action\\s*=\\s*keep_logs' /etc/audit/auditd.conf && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-089', {
    name: "Audit — alerte par e-mail en cas d'espace faible (space_left_action = email)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'space_left_action\\s*=\\s*email' /etc/audit/auditd.conf && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-090', {
    name: "Audit — e-mail d'alerte envoyé à root (action_mail_acct)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'action_mail_acct\\s*=\\s*root' /etc/audit/auditd.conf && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-091', {
    name: "Audit — arrêt système si espace critique (admin_space_left_action = halt)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'admin_space_left_action\\s*=\\s*halt' /etc/audit/auditd.conf && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-092', {
    name: 'Audit — règles sur les modifications de date/heure (adjtimex, settimeofday)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'adjtimex\\|settimeofday' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-093', {
    name: 'Audit — règles sur les modifications des comptes (passwd, group, shadow)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'passwd\\|group\\|gshadow' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-094', {
    name: "Audit — règles sur les modifications de l'environnement réseau (hostname, domainname)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'sethostname\\|setdomainname' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-095', {
    name: 'Audit — règles sur les modifications de politique MAC (SELinux/AppArmor)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'selinux\\|apparmor' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-096', {
    name: 'Audit — règles sur les événements de connexion/déconnexion',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'faillog\\|btmp\\|wtmp\\|lastlog' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-097', {
    name: 'Audit — règles sur la suppression de fichiers (unlink, rename)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q 'unlink\\|rename' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-098', {
    name: 'Audit — règles sur les modifications sudoers',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q '/etc/sudoers' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-099', {
    name: "Audit — configuration immuable (les règles ne peuvent pas être modifiées à l'exécution)",
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -s 2>/dev/null | grep -q 'enabled 2' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-100', {
    name: 'Audit — règles sur les appels sudo/su',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "auditctl -l 2>/dev/null | grep -q '/usr/bin/sudo\\|/bin/su' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  // ── CONFIGURATION SYSTÈME ────────────────────────────────────────────────────

  r('lsb-101', {
    name: "Cron — accès restreint via /etc/cron.allow",
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'test -f /etc/cron.allow && echo true || echo false',
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-102', {
    name: "Cron — répertoire /etc/cron.d avec permissions restrictives",
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a %U' /etc/cron.d 2>/dev/null | grep -qE '^[67]00 root' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-103', {
    name: 'Élévation de privilèges — su restreint au groupe wheel (pam_wheel)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -q 'pam_wheel' /etc/pam.d/su && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-104', {
    name: 'Élévation de privilèges — sudo installé',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "command -v sudo &>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-105', {
    name: 'Sudo — requiretty configuré',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'Defaults.*requiretty' /etc/sudoers /etc/sudoers.d/* 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-106', {
    name: 'Sudo — use_pty configuré (pseudo-terminal obligatoire)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'Defaults.*use_pty' /etc/sudoers /etc/sudoers.d/* 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-107', {
    name: 'Synchronisation — NTP (chrony ou ntpd) configuré et actif',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-active chronyd ntpd 2>/dev/null | grep -q active && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-108', {
    name: 'Synchronisation — chrony synchronisé avec une source de référence',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "chronyc tracking 2>/dev/null | grep -q 'Reference' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'low',
  }),

  r('lsb-109', {
    name: 'Accès réseau — /etc/hosts.allow configuré (TCP wrappers)',
    category: 'System',
    checkType: 'file',
    targetPlatform: 'linux',
    target: '/etc/hosts.allow',
    expected: null,
    operator: 'exists',
    severity: 'low',
  }),

  r('lsb-110', {
    name: "Noyau — chargement de modules restreint (modules_disabled)",
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n kernel.modules_disabled 2>/dev/null',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ── PERMISSIONS / FICHIERS SENSIBLES ─────────────────────────────────────────

  r('lsb-111', {
    name: 'Permissions — /etc/passwd : 644',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/passwd",
    expected: '644',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-112', {
    name: 'Permissions — /etc/shadow : 000 ou 640',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/shadow | grep -qE '^(000|640)$' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-113', {
    name: 'Permissions — /etc/group : 644',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/group",
    expected: '644',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-114', {
    name: 'Permissions — /etc/gshadow : 000',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/gshadow",
    expected: '000',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-115', {
    name: 'Permissions — /etc/passwd- (sauvegarde) : ≤ 644',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/passwd- 2>/dev/null | grep -qE '^[0-6][0-4][0-4]$' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-116', {
    name: 'Permissions — /etc/shadow- (sauvegarde) : ≤ 640',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/shadow- 2>/dev/null | grep -qE '^[0-6][0-4][0-0]$' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-117', {
    name: 'Permissions — /boot/grub2/grub.cfg ou /boot/grub/grub.cfg : 600',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /boot/grub2/grub.cfg /boot/grub/grub.cfg 2>/dev/null | grep -q '600' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-118', {
    name: 'Permissions — aucun fichier accessible en écriture par tous',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'find / -xdev -type f -perm -0002 2>/dev/null | wc -l',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-119', {
    name: 'Permissions — nombre de fichiers SUID (audit)',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'find / -xdev -type f -perm -4000 2>/dev/null | wc -l',
    expected: '20',
    operator: 'lt',
    severity: 'moderate',
  }),

  r('lsb-120', {
    name: 'Bannière — /etc/motd configuré',
    category: 'File Permissions',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'test -s /etc/motd && echo true || echo false',
    expected: 'true',
    operator: 'eq',
    severity: 'low',
  }),

  // ── JOURNALISATION ───────────────────────────────────────────────────────────

  r('lsb-121', {
    name: 'Journalisation — rsyslog ou syslog-ng actif',
    category: 'Logging',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-active rsyslog syslog-ng 2>/dev/null | grep -q active && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-122', {
    name: 'Journalisation — serveur de logs distant configuré',
    category: 'Logging',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei '^\\s*\\*\\.\\*\\s+@@?' /etc/rsyslog.conf /etc/rsyslog.d/*.conf 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-123', {
    name: 'Journalisation — journald avec stockage persistant activé',
    category: 'Logging',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -Ei 'Storage\\s*=\\s*persistent' /etc/systemd/journald.conf && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-124', {
    name: 'Journalisation — rotation des logs configurée (/etc/logrotate.conf)',
    category: 'Logging',
    checkType: 'file',
    targetPlatform: 'linux',
    target: '/etc/logrotate.conf',
    expected: null,
    operator: 'exists',
    severity: 'moderate',
  }),

  r('lsb-125', {
    name: "Journalisation — fichier d'authentification présent (auth.log ou secure)",
    category: 'Logging',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'test -f /var/log/auth.log -o -f /var/log/secure && echo true || echo false',
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  // ── RÈGLES COMPLÉMENTAIRES ───────────────────────────────────────────────────

  r('lsb-126', {
    name: 'SELinux / AppArmor — contrôle obligatoire des accès actif',
    category: 'MAC',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "(getenforce 2>/dev/null | grep -qiE 'Enforcing|Permissive' || aa-status 2>/dev/null | grep -q 'profiles are in enforce') && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-127', {
    name: 'SELinux — mode enforcing actif',
    category: 'MAC',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "getenforce 2>/dev/null",
    expected: 'Enforcing',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-128', {
    name: 'Mises à jour — vérification automatique des paquets activée',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-active apt-daily.timer dnf-automatic.timer 2>/dev/null | grep -q active && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-129', {
    name: 'Mises à jour — paquets de sécurité en attente',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "apt-get --just-print upgrade 2>/dev/null | grep -c '^Inst' || dnf check-update --security -q 2>/dev/null | wc -l",
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-130', {
    name: 'Réseau — protocole IPv6 désactivé si non utilisé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null',
    expected: '1',
    operator: 'eq',
    severity: 'low',
  }),

  r('lsb-131', {
    name: 'Réseau — TCP timestamps désactivés',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.tcp_timestamps',
    expected: '0',
    operator: 'eq',
    severity: 'low',
  }),

  r('lsb-132', {
    name: 'Comptes — aucun compte avec UID 0 sauf root',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "awk -F: '($3 == 0 && $1 != \"root\") {print $1}' /etc/passwd | wc -l",
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-133', {
    name: 'Comptes — aucun compte sans mot de passe',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "awk -F: '($2 == \"\" || $2 == \"!\") {print $1}' /etc/shadow 2>/dev/null | wc -l",
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),

  r('lsb-134', {
    name: "Comptes — fichier /etc/sudoers avec permissions 440",
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "stat -c '%a' /etc/sudoers",
    expected: '440',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-135', {
    name: "Réseau — port SSH non standard (recommandé différent de 22)",
    category: 'SSH',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "sshd -T 2>/dev/null | grep -i '^port' | awk '{print $2}'",
    expected: '22',
    operator: 'neq',
    severity: 'low',
  }),

  r('lsb-136', {
    name: "Noyau — protection ExecShield (NX bit) actif",
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -q 'nx' /proc/cpuinfo && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-137', {
    name: "Réseau — VPN ou tunnel chiffré configuré",
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "ip link show | grep -qE 'tun|wg|ipsec|vpn' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'low',
  }),

  r('lsb-138', {
    name: 'Audit — auditd activé au démarrage (enabled-on-boot)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "systemctl is-enabled auditd 2>/dev/null",
    expected: 'enabled',
    operator: 'eq',
    severity: 'high',
  }),

  r('lsb-139', {
    name: 'PAM — module pam_umask configuré',
    category: 'Password Policy',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "grep -q 'pam_umask' /etc/pam.d/common-session /etc/pam.d/system-auth 2>/dev/null && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'low',
  }),

  r('lsb-140', {
    name: 'Noyau — protection contre les liens symboliques (protected_symlinks)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n fs.protected_symlinks 2>/dev/null',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-141', {
    name: 'Noyau — protection contre les liens physiques (protected_hardlinks)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n fs.protected_hardlinks 2>/dev/null',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-142', {
    name: 'Noyau — accès aux messages dmesg restreint (dmesg_restrict)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n kernel.dmesg_restrict 2>/dev/null',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  r('lsb-143', {
    name: 'Noyau — espace de noms des PID restreint (kptr_restrict)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n kernel.kptr_restrict 2>/dev/null',
    expected: '1',
    operator: 'gt',
    severity: 'moderate',
  }),

  r('lsb-144', {
    name: 'Réseau — protection contre les attaques SYN flood (tcp_max_syn_backlog)',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'linux',
    target: 'sysctl -n net.ipv4.tcp_max_syn_backlog 2>/dev/null',
    expected: '1024',
    operator: 'gt',
    severity: 'moderate',
  }),

  r('lsb-145', {
    name: 'Chiffrement — LUKS activé sur les partitions de données sensibles',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'linux',
    target: "lsblk -f 2>/dev/null | grep -q 'crypto_LUKS' && echo true || echo false",
    expected: 'true',
    operator: 'eq',
    severity: 'high',
  }),

];
