import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const nistSP800171Rules: ComplianceRule[] = [

  // =========================================================================
  // 3.1 - Access Control (AC) - 22 contrôles
  // =========================================================================

  // 3.1.1 - Limiter l'accès système aux utilisateurs autorisés
  r('nist-AC-001', {
    name: 'Contrôle d\'accès — Compte Invité désactivé [3.1.1]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name Guest -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-LocalUser -Name Guest',
  }),
  r('nist-AC-002', {
    name: 'Contrôle d\'accès — Verrouillage de compte configuré [3.1.1]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(([adsi]\'WinNT://localhost\').MaxBadPasswordsAllowed.Value)',
    expected: '11',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'LockoutBadCount\\s*=\\s*\\d+\',\'LockoutBadCount = 10\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),

  // 3.1.2 - Limiter l'accès aux types de transactions et fonctions autorisés
  r('nist-AC-003', {
    name: 'Contrôle d\'accès — Contrôle de compte utilisateur (UAC) activé [3.1.2]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'EnableLUA\' -Value 1 -Type DWord',
  }),
  r('nist-AC-004', {
    name: 'Contrôle d\'accès — Installation de logiciels restreinte aux administrateurs [3.1.2]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer|DisableMSI',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Installer\' -Name \'DisableMSI\' -Value 1 -Type DWord',
  }),

  // 3.1.3 - Contrôler les flux d'informations CUI
  r('nist-AC-005', {
    name: 'Contrôle d\'accès — Pare-feu Windows profil Domaine activé [3.1.3]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -Enabled True',
  }),
  r('nist-AC-006', {
    name: 'Contrôle d\'accès — Pare-feu Windows profil Privé activé [3.1.3]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Private -Enabled True',
  }),
  r('nist-AC-007', {
    name: 'Contrôle d\'accès — Pare-feu Windows profil Public activé [3.1.3]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -Enabled True',
  }),

  // 3.1.4 - Séparer les responsabilités des individus
  r('nist-AC-008', {
    name: 'Contrôle d\'accès — Compte Administrateur intégré désactivé [3.1.4]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name Administrator -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-LocalUser -Name Administrator',
  }),

  // 3.1.5 - Appliquer le principe du moindre privilège
  r('nist-AC-009', {
    name: 'Contrôle d\'accès — Nombre d\'administrateurs locaux limité [3.1.5]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group Administrators).Count',
    expected: '4',
    operator: 'lt',
    severity: 'moderate',
    // No auto-remediation: cannot safely decide which admin accounts to remove
  }),

  // 3.1.6 - Utiliser des comptes non privilégiés pour les activités non privilégiées
  r('nist-AC-010', {
    name: 'Contrôle d\'accès — Invite d\'élévation UAC pour les administrateurs [3.1.6]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'ConsentPromptBehaviorAdmin\' -Value 2 -Type DWord',
  }),

  // 3.1.7 - Empêcher les utilisateurs non privilégiés d'exécuter des fonctions privilégiées
  r('nist-AC-011', {
    name: 'Contrôle d\'accès — LSA en mode processus protégé (PPL) [3.1.7]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'RunAsPPL\' -Value 1 -Type DWord',
  }),

  // 3.1.8 - Limiter les tentatives de connexion infructueuses
  r('nist-AC-012', {
    name: 'Contrôle d\'accès — Seuil de verrouillage de compte ≤ 5 tentatives [3.1.8]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(([adsi]\'WinNT://localhost\').MaxBadPasswordsAllowed.Value)',
    expected: '6',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'LockoutBadCount\\s*=\\s*\\d+\',\'LockoutBadCount = 5\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),

  // 3.1.9 - Afficher les avis de confidentialité et de sécurité
  r('nist-AC-013', {
    name: 'Contrôle d\'accès — Texte de mention légale à la connexion configuré [3.1.9]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'LegalNoticeText\' -Value \'This system is for authorized use only. By using this system, you consent to monitoring and auditing.\' -Type String',
  }),
  r('nist-AC-014', {
    name: 'Contrôle d\'accès — Titre de mention légale à la connexion configuré [3.1.9]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'LegalNoticeCaption\' -Value \'Security Notice\' -Type String',
  }),

  // 3.1.10 - Verrouillage de session après inactivité
  r('nist-AC-015', {
    name: 'Contrôle d\'accès — Économiseur d\'écran activé [3.1.10]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaveActive',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Name \'ScreenSaveActive\' -Value \'1\' -Type String',
  }),
  r('nist-AC-016', {
    name: 'Contrôle d\'accès — Délai d\'inactivité économiseur d\'écran ≤ 900 secondes [3.1.10]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '901',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Name \'ScreenSaveTimeOut\' -Value \'900\' -Type String',
  }),
  r('nist-AC-017', {
    name: 'Contrôle d\'accès — Mot de passe requis à la reprise de l\'économiseur d\'écran [3.1.10]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\' -Name \'ScreenSaverIsSecure\' -Value \'1\' -Type String',
  }),
  r('nist-AC-018', {
    name: 'Contrôle d\'accès — Délai d\'inactivité RDP ≤ 900 000 ms [3.1.10]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MaxIdleTime',
    expected: '900001',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Name \'MaxIdleTime\' -Value 900000 -Type DWord',
  }),

  // 3.1.11 - Terminer les sessions après conditions définies
  r('nist-AC-019', {
    name: 'Contrôle d\'accès — Délai de déconnexion RDP ≤ 86 400 000 ms [3.1.11]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MaxDisconnectionTime',
    expected: '86400001',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Name \'MaxDisconnectionTime\' -Value 86400000 -Type DWord',
  }),

  // 3.1.12 - Surveiller les sessions d'accès à distance
  r('nist-AC-020', {
    name: 'Contrôle d\'accès — Transcription PowerShell activée [3.1.12]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription|EnableTranscripting',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription\' -Name \'EnableTranscripting\' -Value 1 -Type DWord',
  }),

  // 3.1.13 - Mécanismes cryptographiques pour l'accès à distance
  r('nist-AC-021', {
    name: 'Contrôle d\'accès — Couche de sécurité RDP configurée sur TLS [3.1.13]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Name \'SecurityLayer\' -Value 2 -Type DWord',
  }),
  r('nist-AC-022', {
    name: 'Contrôle d\'accès — WinRM refuse le trafic non chiffré [3.1.13]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowUnencryptedTraffic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client\' -Name \'AllowUnencryptedTraffic\' -Value 0 -Type DWord',
  }),

  // 3.1.14 - Routage via points d'accès gérés
  r('nist-AC-023', {
    name: 'Contrôle d\'accès — Authentification au niveau réseau (NLA) RDP requise [3.1.14]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\' -Name \'UserAuthentication\' -Value 1 -Type DWord',
  }),

  // 3.1.15 - Autoriser l'exécution à distance de commandes privilégiées
  r('nist-AC-024', {
    name: 'Contrôle d\'accès — Authentification basique WinRM désactivée [3.1.15]',
    category: 'Contrôle d\'accès',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|AllowBasic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service\' -Name \'AllowBasic\' -Value 0 -Type DWord',
  }),

  // 3.1.18-20 - Contrôler les appareils mobiles / chiffrement / CUI
  r('nist-AC-025', {
    name: 'Contrôle d\'accès — BitLocker activé sur tous les lecteurs [3.1.18]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint C: -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Enable-BitLocker -MountPoint C: -EncryptionMethod XtsAes256 -UsedSpaceOnly -SkipHardwareTest -RecoveryPasswordProtector',
  }),

  // 3.1.21 - Limiter l'utilisation du Bluetooth
  r('nist-AC-026', {
    name: 'Contrôle d\'accès — Service Bluetooth désactivé [3.1.21]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name bthserv -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service -Name bthserv -Force -ErrorAction SilentlyContinue; Set-Service -Name bthserv -StartupType Disabled',
  }),

  // 3.1.22 - Contrôler le CUI publié sur des systèmes accessibles publiquement
  r('nist-AC-027', {
    name: 'Contrôle d\'accès — Serveur web IIS non actif [3.1.22]',
    category: 'Contrôle d\'accès',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name W3SVC -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Stop-Service -Name W3SVC -Force -ErrorAction SilentlyContinue; Set-Service -Name W3SVC -StartupType Disabled -ErrorAction SilentlyContinue',
  }),

  // =========================================================================
  // 3.2 - Sensibilisation et Formation (AT) - 3 contrôles
  // =========================================================================

  r('nist-AT-001', {
    name: 'Sensibilisation — Journalisation des événements de verrouillage de poste [3.2.1]',
    category: 'Sensibilisation et Formation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-EventLog -LogName Security -InstanceId 4800 -Newest 1 -ErrorAction SilentlyContinue) -ne $null',
    expected: 'True',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921C-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('nist-AT-002', {
    name: 'Sensibilisation — Journalisation des blocs de script PowerShell activée [3.2.2]',
    category: 'Sensibilisation et Formation',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Name \'EnableScriptBlockLogging\' -Value 1 -Type DWord',
  }),
  r('nist-AT-003', {
    name: 'Sensibilisation — Accès contrôlé aux dossiers (Defender) activé [3.2.3]',
    category: 'Sensibilisation et Formation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableControlledFolderAccess',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -EnableControlledFolderAccess Enabled',
  }),

  // =========================================================================
  // 3.3 - Audit et Responsabilité (AU) - 9 contrôles
  // =========================================================================

  r('nist-AU-001', {
    name: 'Audit — Audit des événements de connexion activé (succès) [3.3.1]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('nist-AU-002', {
    name: 'Audit — Audit d\'accès au système de fichiers activé [3.3.1]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('nist-AU-003', {
    name: 'Audit — Audit de la gestion des comptes utilisateurs activé [3.3.1]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('nist-AU-004', {
    name: 'Audit — Ligne de commande incluse dans les événements de création de processus [3.3.2]',
    category: 'Audit et Responsabilité',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit|ProcessCreationIncludeCmdLine_Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit\' -Name \'ProcessCreationIncludeCmdLine_Enabled\' -Value 1 -Type DWord',
  }),
  r('nist-AU-005', {
    name: 'Audit — Taille maximale du journal de sécurité ≥ 196 608 Ko [3.3.3]',
    category: 'Audit et Responsabilité',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security|MaxSize',
    expected: '196607',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security\' -Name \'MaxSize\' -Value 201326592 -Type DWord',
  }),
  r('nist-AU-006', {
    name: 'Audit — Transfert d\'événements (SIEM/collecte) configuré [3.3.5]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListProvider "Microsoft-Windows-EventCollector" -ErrorAction SilentlyContinue) -ne $null',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    // No auto-remediation: event forwarding requires site-specific SIEM configuration
  }),
  r('nist-AU-007', {
    name: 'Audit — Synchronisation horaire NTP (pas d\'horloge CMOS locale) [3.3.7]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(w32tm /query /status 2>&1 | Select-String \'Source\').ToString()',
    expected: 'Local CMOS Clock',
    operator: 'not_contains',
    severity: 'moderate',
    remediationScript: 'w32tm /config /manualpeerlist:"time.windows.com" /syncfromflags:manual /reliable:yes /update; Restart-Service w32time; w32tm /resync',
  }),
  r('nist-AU-008', {
    name: 'Audit — Accès au journal de sécurité restreint aux comptes autorisés [3.3.8]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Acl "$env:SystemRoot\\System32\\winevt\\Logs\\Security.evtx").Access | Where-Object {$_.IdentityReference -notmatch \'NT AUTHORITY|SYSTEM|Administrators\'} | Measure-Object | Select-Object -ExpandProperty Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    // No auto-remediation: removing ACL entries requires knowing which specific entries to remove
  }),
  r('nist-AU-009', {
    name: 'Audit — Droit de gestion des audits et journaux de sécurité limité aux administrateurs [3.3.9]',
    category: 'Audit et Responsabilité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(secedit /export /area USER_RIGHTS /cfg "$env:TEMP\\rights.cfg" | Out-Null); (Get-Content "$env:TEMP\\rights.cfg" | Where-Object {$_ -match \'SeSecurityPrivilege\'})',
    expected: 'Administrators',
    operator: 'contains',
    severity: 'high',
    // No auto-remediation: modifying user rights assignments requires secedit import with a custom template
  }),

  // =========================================================================
  // 3.4 - Gestion de Configuration (CM) - 9 contrôles
  // =========================================================================

  r('nist-CM-001', {
    name: 'Configuration — LAPS (solution de mot de passe administrateur local) configuré [3.4.1]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\GPExtensions\\{D76B9641-3288-4f75-942D-087DE603E3EA}" -ErrorAction SilentlyContinue) -ne $null',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    // No auto-remediation: LAPS requires AD infrastructure and MSI installation
  }),
  r('nist-CM-002', {
    name: 'Configuration — AppLocker ou WDAC configuré [3.4.2]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-AppLockerPolicy -Effective -ErrorAction SilentlyContinue).RuleCollections.Count',
    expected: '0',
    operator: 'gt',
    severity: 'high',
    // No auto-remediation: AppLocker/WDAC policies are organization-specific
  }),
  r('nist-CM-003', {
    name: 'Configuration — Protection en temps réel Windows Defender activée [3.4.4]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('nist-CM-004', {
    name: 'Configuration — Service Application Identity (AppLocker) en cours d\'exécution [3.4.5]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name AppIDSvc -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name AppIDSvc -StartupType Automatic; Start-Service -Name AppIDSvc',
  }),
  r('nist-CM-005', {
    name: 'Configuration — SMBv1 désactivé [3.4.6]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration -Property EnableSMB1Protocol).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force',
  }),
  r('nist-CM-006', {
    name: 'Configuration — LLMNR désactivé [3.4.6]',
    category: 'Gestion de Configuration',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient|EnableMulticast',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient\' -Name \'EnableMulticast\' -Value 0 -Type DWord',
  }),
  r('nist-CM-007', {
    name: 'Configuration — NetBIOS désactivé sur toutes les interfaces [3.4.6]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object {$_.TcpipNetbiosOptions -ne 2} | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object {$_.TcpipNetbiosOptions -ne $null} | ForEach-Object { $_.SetTcpipNetbios(2) | Out-Null }',
  }),
  r('nist-CM-008', {
    name: 'Configuration — Spouleur d\'impression désactivé [3.4.7]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name Spooler -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service -Name Spooler -Force -ErrorAction SilentlyContinue; Set-Service -Name Spooler -StartupType Disabled',
  }),
  r('nist-CM-009', {
    name: 'Configuration — Client Telnet désactivé [3.4.7]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WindowsOptionalFeature -Online -FeatureName TelnetClient -ErrorAction SilentlyContinue).State',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Disable-WindowsOptionalFeature -Online -FeatureName TelnetClient -NoRestart -ErrorAction SilentlyContinue',
  }),
  r('nist-CM-010', {
    name: 'Configuration — Protection contre les applications potentiellement indésirables (PUA) activée [3.4.8]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).PUAProtection',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -PUAProtection Enabled',
  }),
  r('nist-CM-011', {
    name: 'Configuration — Service Registre distant désactivé [3.4.9]',
    category: 'Gestion de Configuration',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name RemoteRegistry -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service -Name RemoteRegistry -Force -ErrorAction SilentlyContinue; Set-Service -Name RemoteRegistry -StartupType Disabled',
  }),

  // =========================================================================
  // 3.5 - Identification et Authentification (IA) - 11 contrôles
  // =========================================================================

  r('nist-IA-001', {
    name: 'Identification — Accès anonyme au SAM restreint [3.5.1]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymousSAM',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'RestrictAnonymousSAM\' -Value 1 -Type DWord',
  }),
  r('nist-IA-002', {
    name: 'Identification — Complexité du mot de passe activée [3.5.2]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(secedit /export /cfg "$env:TEMP\\secpol.cfg" | Out-Null); (Get-Content "$env:TEMP\\secpol.cfg" | Where-Object {$_ -match \'PasswordComplexity\'}).Split(\'=\')[1].Trim()',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'PasswordComplexity\\s*=\\s*0\',\'PasswordComplexity = 1\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-003', {
    name: 'Identification — Longueur minimale du mot de passe ≥ 14 caractères [3.5.2]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(([adsi]\'WinNT://localhost\').minPasswordLength.Value)',
    expected: '14',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'MinimumPasswordLength\\s*=\\s*\\d+\',\'MinimumPasswordLength = 14\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-004', {
    name: 'Identification — Credential Guard (virtualisation) activé [3.5.3]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\' -Name \'EnableVirtualizationBasedSecurity\' -Value 1 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\' -Name \'RequirePlatformSecurityFeatures\' -Value 1 -Type DWord',
  }),
  r('nist-IA-005', {
    name: 'Identification — Niveau de compatibilité LM configuré sur NTLMv2 uniquement [3.5.4]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '5',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'LmCompatibilityLevel\' -Value 5 -Type DWord',
  }),
  r('nist-IA-006', {
    name: 'Identification — Stockage des hachages LM désactivé [3.5.4]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|NoLMHash',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'NoLMHash\' -Value 1 -Type DWord',
  }),
  r('nist-IA-007', {
    name: 'Identification — Historique des mots de passe ≥ 24 [3.5.5]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(([adsi]\'WinNT://localhost\').PasswordHistoryLength.Value)',
    expected: '23',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'PasswordHistorySize\\s*=\\s*\\d+\',\'PasswordHistorySize = 24\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-008', {
    name: 'Identification — Âge maximal du mot de passe ≤ 60 jours [3.5.6]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '([math]::Round((([adsi]\'WinNT://localhost\').maxPasswordAge.Value) / 86400))',
    expected: '61',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'MaximumPasswordAge\\s*=\\s*\\d+\',\'MaximumPasswordAge = 60\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-009', {
    name: 'Identification — Âge minimal du mot de passe ≥ 1 jour [3.5.6]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '([math]::Round((([adsi]\'WinNT://localhost\').minPasswordAge.Value) / 86400))',
    expected: '0',
    operator: 'gt',
    severity: 'low',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'MinimumPasswordAge\\s*=\\s*\\d+\',\'MinimumPasswordAge = 1\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-010', {
    name: 'Identification — WDigest désactivé (pas de stockage en clair) [3.5.7]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest|UseLogonCredential',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest\' -Name \'UseLogonCredential\' -Value 0 -Type DWord',
  }),
  r('nist-IA-011', {
    name: 'Identification — Chiffrement réversible des mots de passe désactivé [3.5.10]',
    category: 'Identification et Authentification',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(secedit /export /cfg "$env:TEMP\\secpol.cfg" | Out-Null); (Get-Content "$env:TEMP\\secpol.cfg" | Where-Object {$_ -match \'ClearTextPassword\'}).Split(\'=\')[1].Trim()',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'secedit /export /cfg "$env:TEMP\\secpol_rem.cfg"; (Get-Content "$env:TEMP\\secpol_rem.cfg") -replace \'ClearTextPassword\\s*=\\s*1\',\'ClearTextPassword = 0\' | Set-Content "$env:TEMP\\secpol_rem.cfg"; secedit /configure /db "$env:TEMP\\secpol_rem.sdb" /cfg "$env:TEMP\\secpol_rem.cfg" /areas SECURITYPOLICY; Remove-Item "$env:TEMP\\secpol_rem.cfg","$env:TEMP\\secpol_rem.sdb" -ErrorAction SilentlyContinue',
  }),
  r('nist-IA-012', {
    name: 'Identification — Saisie automatique des mots de passe dans le navigateur désactivée [3.5.11]',
    category: 'Identification et Authentification',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Internet Explorer\\Main|FormSuggest Passwords',
    expected: 'no',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Internet Explorer\\Main\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Internet Explorer\\Main\' -Name \'FormSuggest Passwords\' -Value \'no\' -Type String',
  }),

  // =========================================================================
  // 3.6 - Réponse aux Incidents (IR) - 3 contrôles
  // =========================================================================

  r('nist-IR-001', {
    name: 'Réponse aux incidents — Service Journal d\'événements en cours d\'exécution [3.6.1]',
    category: 'Réponse aux Incidents',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name EventLog -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name EventLog -StartupType Automatic; Start-Service -Name EventLog',
  }),
  r('nist-IR-002', {
    name: 'Réponse aux incidents — Taille du journal de sécurité ≥ 196 608 Ko [3.6.1]',
    category: 'Réponse aux Incidents',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security|MaxSize',
    expected: '196607',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security\' -Name \'MaxSize\' -Value 201326592 -Type DWord',
  }),
  r('nist-IR-003', {
    name: 'Réponse aux incidents — Rapport d\'erreurs Windows non désactivé [3.6.2]',
    category: 'Réponse aux Incidents',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting|Disabled',
    expected: '1',
    operator: 'neq',
    severity: 'low',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\Windows Error Reporting\' -Name \'Disabled\' -Value 0 -Type DWord',
  }),

  // =========================================================================
  // 3.7 - Maintenance (MA) - 6 contrôles
  // =========================================================================

  r('nist-MA-001', {
    name: 'Maintenance — Service Windows Update non désactivé [3.7.1]',
    category: 'Maintenance',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name wuauserv -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-Service -Name wuauserv -StartupType Automatic; Start-Service -Name wuauserv -ErrorAction SilentlyContinue',
  }),
  r('nist-MA-002', {
    name: 'Maintenance — Lecture automatique désactivée (supports amovibles) [3.7.4]',
    category: 'Maintenance',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\' -Name \'NoDriveTypeAutoRun\' -Value 255 -Type DWord',
  }),
  r('nist-MA-003', {
    name: 'Maintenance — Assistance à distance désactivée [3.7.6]',
    category: 'Maintenance',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Remote Assistance|fAllowToGetHelp',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Remote Assistance\' -Name \'fAllowToGetHelp\' -Value 0 -Type DWord',
  }),

  // =========================================================================
  // 3.8 - Protection des Supports (MP) - 9 contrôles
  // =========================================================================

  r('nist-MP-001', {
    name: 'Protection des supports — BitLocker activé sur tous les lecteurs [3.8.1]',
    category: 'Protection des Supports',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint C: -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Enable-BitLocker -MountPoint C: -EncryptionMethod XtsAes256 -UsedSpaceOnly -SkipHardwareTest -RecoveryPasswordProtector',
  }),
  r('nist-MP-002', {
    name: 'Protection des supports — Stockage USB restreint [3.8.5]',
    category: 'Protection des Supports',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR|Start',
    expected: '4',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR\' -Name \'Start\' -Value 4 -Type DWord',
  }),
  r('nist-MP-003', {
    name: 'Protection des supports — BitLocker To Go requis pour supports amovibles [3.8.6]',
    category: 'Protection des Supports',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\FVE|RDVRequireEncryption',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE\' -Name \'RDVRequireEncryption\' -Value 1 -Type DWord',
  }),
  r('nist-MP-004', {
    name: 'Protection des supports — Supports amovibles refusés [3.8.7]',
    category: 'Protection des Supports',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\RemovableStorageDevices|Deny_All',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\RemovableStorageDevices\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\RemovableStorageDevices\' -Name \'Deny_All\' -Value 1 -Type DWord',
  }),
  r('nist-MP-005', {
    name: 'Protection des supports — Installation de périphériques amovibles restreinte [3.8.8]',
    category: 'Protection des Supports',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceInstall\\Restrictions|DenyRemovableDevices',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceInstall\\Restrictions\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DeviceInstall\\Restrictions\' -Name \'DenyRemovableDevices\' -Value 1 -Type DWord',
  }),
  r('nist-MP-006', {
    name: 'Protection des supports — Service de cliché instantané de volume (VSS) actif [3.8.9]',
    category: 'Protection des Supports',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name VSS -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name VSS -StartupType Automatic; Start-Service -Name VSS',
  }),

  // =========================================================================
  // 3.9 - Sécurité du Personnel (PS) - 2 contrôles
  // =========================================================================

  r('nist-PS-001', {
    name: 'Personnel — Compte Administrateur intégré renommé ou désactivé [3.9.1]',
    category: 'Sécurité du Personnel',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name Administrator -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-LocalUser -Name Administrator',
  }),
  r('nist-PS-002', {
    name: 'Personnel — Aucun compte actif inactif depuis plus de 90 jours [3.9.2]',
    category: 'Sécurité du Personnel',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object {$_.Enabled -and $_.LastLogon -ne $null -and $_.LastLogon -lt (Get-Date).AddDays(-90)} | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Get-LocalUser | Where-Object {$_.Enabled -and $_.LastLogon -ne $null -and $_.LastLogon -lt (Get-Date).AddDays(-90)} | ForEach-Object { Disable-LocalUser -Name $_.Name }',
  }),

  // =========================================================================
  // 3.10 - Protection Physique (PE) - 6 contrôles
  // =========================================================================

  r('nist-PE-001', {
    name: 'Protection physique — Démarrage sécurisé (Secure Boot) activé [3.10.5]',
    category: 'Protection Physique',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'Confirm-SecureBootUEFI -ErrorAction SilentlyContinue',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    // No auto-remediation: Secure Boot must be enabled in BIOS/UEFI firmware
  }),
  r('nist-PE-002', {
    name: 'Protection physique — TPM présent et activé [3.10.5]',
    category: 'Protection Physique',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Tpm -ErrorAction SilentlyContinue).TpmPresent',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    // No auto-remediation: TPM is a hardware component enabled in BIOS/UEFI
  }),

  // =========================================================================
  // 3.11 - Évaluation des Risques (RA) - 3 contrôles
  // =========================================================================

  r('nist-RA-001', {
    name: 'Évaluation des risques — Signatures Defender à jour (≤ 7 jours) [3.11.1]',
    category: 'Évaluation des Risques',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntispywareSignatureAge',
    expected: '8',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Update-MpSignature',
  }),
  r('nist-RA-002', {
    name: 'Évaluation des risques — Mises à jour automatiques Windows configurées [3.11.2]',
    category: 'Évaluation des Risques',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '4',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Name \'AUOptions\' -Value 4 -Type DWord',
  }),
  r('nist-RA-003', {
    name: 'Évaluation des risques — Aucun redémarrage en attente [3.11.3]',
    category: 'Évaluation des Risques',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update\\RebootRequired" -ErrorAction SilentlyContinue) -eq $null',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    // No auto-remediation: rebooting a system is disruptive and requires planned maintenance
  }),

  // =========================================================================
  // 3.12 - Évaluation de la Sécurité (CA) - 4 contrôles
  // =========================================================================

  r('nist-CA-001', {
    name: 'Évaluation de la sécurité — Centre de sécurité Windows en cours d\'exécution [3.12.1]',
    category: 'Évaluation de la Sécurité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name wscsvc -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Service -Name wscsvc -StartupType Automatic; Start-Service -Name wscsvc',
  }),
  r('nist-CA-002', {
    name: 'Évaluation de la sécurité — Windows Defender en cours d\'exécution [3.12.3]',
    category: 'Évaluation de la Sécurité',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name WinDefend -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name WinDefend -StartupType Automatic; Start-Service -Name WinDefend',
  }),

  // =========================================================================
  // 3.13 - Protection des Systèmes et Communications (SC) - 16 contrôles
  // =========================================================================

  r('nist-SC-001', {
    name: 'Communications — Accès contrôlé aux dossiers Defender activé [3.13.4]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableControlledFolderAccess',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -EnableControlledFolderAccess Enabled',
  }),
  r('nist-SC-002', {
    name: 'Communications — Pare-feu bloque les connexions entrantes par défaut [3.13.6]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile | Where-Object {$_.DefaultInboundAction -ne \'Block\'} | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain,Private,Public -DefaultInboundAction Block',
  }),
  r('nist-SC-003', {
    name: 'Communications — TLS 1.0 serveur désactivé [3.13.8]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('nist-SC-004', {
    name: 'Communications — TLS 1.1 serveur désactivé [3.13.8]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('nist-SC-005', {
    name: 'Communications — SSL 2.0 serveur désactivé [3.13.8]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('nist-SC-006', {
    name: 'Communications — SSL 3.0 serveur désactivé [3.13.8]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('nist-SC-007', {
    name: 'Communications — Délai d\'inactivité des sessions réseau ≤ 15 minutes [3.13.9]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|AutoDisconnect',
    expected: '16',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters\' -Name \'AutoDisconnect\' -Value 15 -Type DWord',
  }),
  r('nist-SC-008', {
    name: 'Communications — Aucun certificat expiré dans le magasin racine [3.13.10]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ChildItem Cert:\\LocalMachine\\Root | Where-Object {$_.NotAfter -lt (Get-Date)} | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Get-ChildItem Cert:\\LocalMachine\\Root | Where-Object {$_.NotAfter -lt (Get-Date)} | ForEach-Object { Remove-Item "Cert:\\LocalMachine\\Root\\$($_.Thumbprint)" -Force }',
  }),
  r('nist-SC-009', {
    name: 'Communications — BitLocker configuré avec AES-256 XTS [3.13.11]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\FVE|EncryptionMethodWithXtsOs',
    expected: '7',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\FVE\' -Name \'EncryptionMethodWithXtsOs\' -Value 7 -Type DWord',
  }),
  r('nist-SC-010', {
    name: 'Communications — ActiveX désactivé dans la zone Internet [3.13.13]',
    category: 'Protection des Systèmes et Communications',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Zones\\3|1200',
    expected: '3',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Zones\\3\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Zones\\3\' -Name \'1200\' -Value 3 -Type DWord',
  }),

  // =========================================================================
  // 3.14 - Intégrité des Systèmes et des Informations (SI) - 7 contrôles
  // =========================================================================

  r('nist-SI-001', {
    name: 'Intégrité — Signatures antivirus à jour (≤ 7 jours) [3.14.1]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '8',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Update-MpSignature',
  }),
  r('nist-SI-002', {
    name: 'Intégrité — Protection en temps réel Defender activée [3.14.2]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('nist-SI-003', {
    name: 'Intégrité — Rapport Defender (MAPS) activé [3.14.2]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).MAPSReporting',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -MAPSReporting Advanced',
  }),
  r('nist-SI-004', {
    name: 'Intégrité — Mise à jour automatique des signatures Defender configurée [3.14.4]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).SignatureScheduleDay',
    expected: '8',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -SignatureScheduleDay 0',
  }),
  r('nist-SI-005', {
    name: 'Intégrité — Analyse planifiée Defender configurée [3.14.5]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).ScanScheduleDay',
    expected: '8',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -ScanScheduleDay 0',
  }),
  r('nist-SI-006', {
    name: 'Intégrité — Règles de réduction de la surface d\'attaque (ASR) activées [3.14.6]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR|ExploitGuard_ASR_Rules',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR\' -Name \'ExploitGuard_ASR_Rules\' -Value 1 -Type DWord',
  }),
  r('nist-SI-007', {
    name: 'Intégrité — Protection réseau Defender activée [3.14.6]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableNetworkProtection',
    expected: '0',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -EnableNetworkProtection Enabled',
  }),
  r('nist-SI-008', {
    name: 'Intégrité — Taille du journal de sécurité ≥ 196 608 Ko [3.14.7]',
    category: 'Intégrité des Systèmes et des Informations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-EventLog -List | Where-Object {$_.LogDisplayName -eq \'Security\'}).MaximumKilobytes',
    expected: '196607',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: 'Limit-EventLog -LogName Security -MaximumSize 200MB',
  }),
];
