import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const pciDSSv4Rules: ComplianceRule[] = [

  // ─── EXIGENCE 1 — Contrôles de sécurité réseau ───────────────────────────────

  r('pci-1-1-1', {
    name: 'Pare-feu — Profil Domain activé (Req 1.1.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -Enabled True',
  }),
  r('pci-1-1-2', {
    name: 'Pare-feu — Profil Private activé (Req 1.1.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Private -Enabled True',
  }),
  r('pci-1-1-3', {
    name: 'Pare-feu — Profil Public activé (Req 1.1.3)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -Enabled True',
  }),
  r('pci-1-2-1', {
    name: 'Pare-feu — Action par défaut trafic entrant Domain: bloquer (Req 1.2.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).DefaultInboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -DefaultInboundAction Block',
  }),
  r('pci-1-2-2', {
    name: 'Pare-feu — Action par défaut trafic entrant Public: bloquer (Req 1.2.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).DefaultInboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -DefaultInboundAction Block',
  }),
  r('pci-1-2-3', {
    name: 'Pare-feu — Action par défaut trafic sortant Domain: autoriser (Req 1.2.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).DefaultOutboundAction',
    expected: 'Allow',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -DefaultOutboundAction Allow',
  }),
  r('pci-1-2-4', {
    name: 'Pare-feu — Nombre de profils actifs (tous les profils couverts) (Req 1.2.3)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -All | Where-Object { $_.Enabled -eq $true }).Count',
    expected: '3',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain,Private,Public -Enabled True',
  }),
  r('pci-1-2-5', {
    name: 'Pare-feu — Journalisation des connexions refusées activée (Req 1.2.5)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -LogBlocked True',
  }),
  r('pci-1-3-1', {
    name: 'Service pare-feu Windows — actif (Req 1.3.1)',
    category: 'Network Security Controls',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'MpsSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name MpsSvc -StartupType Automatic; Start-Service -Name MpsSvc',
  }),
  r('pci-1-4-1', {
    name: 'IPSec — service agent activé (NSC entre réseaux) (Req 1.4.1)',
    category: 'Network Security Controls',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'PolicyAgent',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name PolicyAgent -StartupType Automatic; Start-Service -Name PolicyAgent',
  }),
  r('pci-1-4-4', {
    name: 'Partage réseau — découverte réseau désactivée sur profil public (Req 1.4.4)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).NotifyOnListen',
    expected: 'False',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -NotifyOnListen False',
  }),
  r('pci-1-5-1', {
    name: 'Accès distant (RDP) — NLA requis pour contrôles dispositifs distants (Req 1.5.1)',
    category: 'Network Security Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp\' -Name \'UserAuthentication\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 2 — Configurations sécurisées ──────────────────────────────────

  r('pci-2-1-1', {
    name: 'Compte Administrateur local — désactivé ou renommé (Req 2.1.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-LocalUser -Name "Administrator"',
  }),
  r('pci-2-1-2', {
    name: 'Compte Invité local — désactivé (Req 2.1.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-LocalUser -Name "Guest"',
  }),
  r('pci-2-2-1', {
    name: 'UAC — Contrôle de compte d\'utilisateur activé (Req 2.2.1)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'EnableLUA\' -Value 1 -Type DWord',
  }),
  r('pci-2-2-2', {
    name: 'UAC — Niveau d\'invite pour administrateurs (Req 2.2.2)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '0',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'ConsentPromptBehaviorAdmin\' -Value 2 -Type DWord',
  }),
  r('pci-2-2-3', {
    name: 'SMBv1 — protocole non sécurisé désactivé (Req 2.2.3)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force',
  }),
  r('pci-2-2-4', {
    name: 'SMBv2 — protocole sécurisé activé (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB2Protocol',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-SmbServerConfiguration -EnableSMB2Protocol $true -Force',
  }),
  r('pci-2-2-5', {
    name: 'Telnet — service désactivé (protocole non sécurisé) (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WindowsOptionalFeature -Online -FeatureName TelnetClient -ErrorAction SilentlyContinue).State',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-WindowsOptionalFeature -Online -FeatureName TelnetClient -NoRestart',
  }),
  r('pci-2-2-6', {
    name: 'AutoRun — désactivé pour les supports amovibles (Req 2.2.6)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\' -Name \'NoDriveTypeAutoRun\' -Value 255 -Type DWord',
  }),
  r('pci-2-2-7', {
    name: 'Chiffrement des accès non-console — RDP chiffrement fort (Req 2.2.7)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|MinEncryptionLevel',
    expected: '3',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp\' -Name \'MinEncryptionLevel\' -Value 3 -Type DWord',
  }),
  r('pci-2-3-1', {
    name: 'SNMP — service désactivé si inutilisé (Req 2.3.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service SNMP -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service -Name SNMP -Force -ErrorAction SilentlyContinue; Set-Service -Name SNMP -StartupType Disabled -ErrorAction SilentlyContinue',
  }),

  // ─── EXIGENCE 3 — Protection des données de compte stockées ──────────────────

  r('pci-3-5-1', {
    name: 'BitLocker — chiffrement du lecteur système activé (Req 3.5.1)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Enable-BitLocker -MountPoint $env:SystemDrive -EncryptionMethod Aes256 -RecoveryPasswordProtector -SkipHardwareTest',
  }),
  r('pci-3-5-1-1', {
    name: 'BitLocker — méthode de chiffrement AES 256 bits (Req 3.5.1.1)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).EncryptionMethod',
    expected: 'Aes256',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-3-7-1', {
    name: 'Service de cryptographie Windows — actif (gestion des clés) (Req 3.7.1)',
    category: 'Stored Account Data Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'CryptSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Service -Name CryptSvc -StartupType Automatic; Start-Service -Name CryptSvc',
  }),
  r('pci-3-7-3', {
    name: 'Magasin de certificats — service de stockage sécurisé des clés actif (Req 3.7.3)',
    category: 'Stored Account Data Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'KeyIso',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name KeyIso -StartupType Automatic; Start-Service -Name KeyIso',
  }),

  // ─── EXIGENCE 4 — Chiffrement des transmissions ───────────────────────────────

  r('pci-4-2-1-tls10', {
    name: 'TLS 1.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-2-1-tls11', {
    name: 'TLS 1.1 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-2-1-tls12', {
    name: 'TLS 1.2 — activé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server\' -Name \'Enabled\' -Value 1 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server\' -Name \'DisabledByDefault\' -Value 0 -Type DWord',
  }),
  r('pci-4-2-1-ssl2', {
    name: 'SSL 2.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-2-1-ssl3', {
    name: 'SSL 3.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-2-1-rc4', {
    name: 'RC4 — chiffrement faible désactivé (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128\' -Name \'Enabled\' -Value 0 -Type DWord',
  }),
  r('pci-4-2-1-1', {
    name: 'Service HTTP.sys — certificats TLS valides requis (Req 4.2.1.1)',
    category: 'Transmission Encryption',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'HTTP',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Start-Service -Name HTTP -ErrorAction SilentlyContinue',
  }),

  // ─── EXIGENCE 5 — Protection contre les malwares ──────────────────────────────

  r('pci-5-2-1', {
    name: 'Windows Defender Antivirus — service actif (Req 5.2.1)',
    category: 'Malware Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WinDefend',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name WinDefend -StartupType Automatic; Start-Service -Name WinDefend',
  }),
  r('pci-5-2-2', {
    name: 'Windows Defender — antivirus activé (Req 5.2.2)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('pci-5-2-3', {
    name: 'Windows Defender — protection en temps réel activée (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('pci-5-3-1', {
    name: 'Windows Defender — définitions à jour (Req 5.3.1)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '7',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Update-MpSignature -ErrorAction SilentlyContinue',
  }),
  r('pci-5-3-2', {
    name: 'Windows Defender — protection contre altération activée (Req 5.3.2)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender\\Features|TamperProtection',
    expected: '5',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-3-3', {
    name: 'Windows Defender — antivirus non désactivé (Req 5.3.2)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender|DisableAntiSpyware',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\' -Name \'DisableAntiSpyware\' -Value 0 -Type DWord',
  }),
  r('pci-5-3-4', {
    name: 'Windows Defender — protection réseau activée (Req 5.3.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableNetworkProtection',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -EnableNetworkProtection Enabled',
  }),
  r('pci-5-4-1', {
    name: 'Windows Defender SmartScreen — activé (anti-phishing) (Req 5.4.1)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Name \'EnableSmartScreen\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 6 — Développement et maintenance sécurisés ─────────────────────

  r('pci-6-3-3', {
    name: 'Windows Update — correctifs automatiques activés (Req 6.3.3)',
    category: 'Secure Development',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Name \'NoAutoUpdate\' -Value 0 -Type DWord',
  }),
  r('pci-6-3-3-b', {
    name: 'Windows Update — options de mise à jour automatique configurées (Req 6.3.3)',
    category: 'Secure Development',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '3',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU\' -Name \'AUOptions\' -Value 3 -Type DWord',
  }),
  r('pci-6-5-1', {
    name: 'Service Windows Update — actif (Req 6.5.1)',
    category: 'Secure Development',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'wuauserv',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Service -Name wuauserv -StartupType Automatic; Start-Service -Name wuauserv',
  }),

  // ─── EXIGENCE 7 — Restriction de l\'accès aux composants système ──────────────

  r('pci-7-2-1', {
    name: 'UAC — accès basé sur le besoin d\'en connaître appliqué (Req 7.2.1)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'EnableLUA\' -Value 1 -Type DWord',
  }),
  r('pci-7-2-2', {
    name: 'Moindre privilège — membres du groupe Administrators limités (Req 7.2.2)',
    category: 'Access Restriction',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group "Administrators" | Measure-Object).Count',
    expected: '3',
    operator: 'lt',
    severity: 'moderate',
  }),
  r('pci-7-2-3', {
    name: 'UAC — élévation de privilèges requiert consentement (Req 7.2.3)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'ConsentPromptBehaviorAdmin\' -Value 2 -Type DWord',
  }),
  r('pci-7-3-1', {
    name: 'Credential Guard — protection des secrets d\'accès (Req 7.3.1)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\' -Name \'EnableVirtualizationBasedSecurity\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 8 — Identification et authentification des utilisateurs ─────────

  r('pci-8-2-5', {
    name: 'Comptes inactifs — désactivés (contrôle via stratégie) (Req 8.2.5)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Disable-LocalUser',
  }),
  r('pci-8-2-6', {
    name: 'Délai d\'inactivité — verrouillage écran ≤ 15 minutes (Req 8.2.6)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\Control Panel\\Desktop\' -Name \'ScreenSaveTimeOut\' -Value \'900\'',
  }),
  r('pci-8-2-6-b', {
    name: 'Économiseur d\'écran — protégé par mot de passe (Req 8.2.6)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\Control Panel\\Desktop\' -Name \'ScreenSaverIsSecure\' -Value \'1\'',
  }),
  r('pci-8-3-4', {
    name: 'Stratégie de verrouillage — seuil de tentatives invalides (Req 8.3.4)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^LockoutBadCount\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '10',
    operator: 'lt',
    severity: 'critical',
    remediationScript: 'net accounts /lockoutthreshold:5',
  }),
  r('pci-8-3-5', {
    name: 'Stratégie de mot de passe — longueur minimum 12 caractères (Req 8.3.5)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^MinimumPasswordLength\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '12',
    operator: 'gt',
    severity: 'critical',
    remediationScript: 'net accounts /minpwlen:12',
  }),
  r('pci-8-3-6', {
    name: 'Stratégie de mot de passe — complexité requise activée (Req 8.3.6)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa" -Name "PasswordComplexity" -ErrorAction SilentlyContinue).PasswordComplexity',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-8-3-7', {
    name: 'Stratégie de mot de passe — historique (4 derniers minimum) (Req 8.3.7)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^PasswordHistorySize\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '4',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'net accounts /uniquepw:5',
  }),
  r('pci-8-3-9', {
    name: 'Stratégie de mot de passe — expiration max 90 jours (Req 8.3.9)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^MaximumPasswordAge\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '90',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'net accounts /maxpwage:90',
  }),
  r('pci-8-4-1', {
    name: 'NLA (MFA réseau) — requis pour RDP (Req 8.4.1)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp\' -Name \'UserAuthentication\' -Value 1 -Type DWord',
  }),
  r('pci-8-6-2', {
    name: 'PowerShell Script Block Logging — mots de passe hardcodés détectables (Req 8.6.2)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Name \'EnableScriptBlockLogging\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 9 — Restriction de l\'accès physique ───────────────────────────

  r('pci-9-5-1', {
    name: 'Verrouillage physique — verrouillage de session requis (protection POS) (Req 9.5.1)',
    category: 'Physical Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\' -Name \'EnableLUA\' -Value 1 -Type DWord',
  }),
  r('pci-9-4-2', {
    name: 'Journal des accès physiques — audit d\'ouverture de session activé (Req 9.4.2)',
    category: 'Physical Access',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),

  // ─── EXIGENCE 10 — Journalisation et surveillance ────────────────────────────

  r('pci-10-2-1', {
    name: 'Journal de sécurité Windows — activé (Req 10.2.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: '$log = Get-WinEvent -ListLog Security; $log.IsEnabled = $true; $log.SaveChanges()',
  }),
  r('pci-10-2-1-1', {
    name: 'Audit — accès aux données (Object Access) activé (Req 10.2.1.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-2', {
    name: 'Audit — actions administratives (Privilege Use) activé (Req 10.2.1.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-3', {
    name: 'Audit — accès au journal d\'audit activé (Req 10.2.1.3)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-4', {
    name: 'Audit — tentatives d\'accès invalides activé (Req 10.2.1.4)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-5', {
    name: 'Audit — utilisation des mécanismes d\'identification (Req 10.2.1.5)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-6', {
    name: 'Audit — démarrage/arrêt des journaux d\'audit (Req 10.2.1.6)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9211-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9211-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-2-1-7', {
    name: 'Audit — création et suppression d\'objets système (Req 10.2.1.7)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('pci-10-3-1', {
    name: 'Journal de sécurité — taille minimale 192 Mo (Req 10.3.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
    remediationScript: '$log = Get-WinEvent -ListLog Security; $log.MaximumSizeInBytes = 201326592; $log.SaveChanges()',
  }),
  r('pci-10-3-2', {
    name: 'Journal des événements — politique de rétention configurée (Req 10.3.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).LogMode',
    expected: 'Circular',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: '$log = Get-WinEvent -ListLog Security; $log.LogMode = "AutoBackup"; $log.SaveChanges()',
  }),
  r('pci-10-5-1', {
    name: 'Journal des applications — taille minimale 100 Mo (Req 10.5.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Application).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: '$log = Get-WinEvent -ListLog Application; $log.MaximumSizeInBytes = 104857600; $log.SaveChanges()',
  }),
  r('pci-10-6-1', {
    name: 'Synchronisation NTP — service de temps Windows actif (Req 10.6.1)',
    category: 'Logging and Monitoring',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'W32Time',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Service -Name W32Time -StartupType Automatic; Start-Service -Name W32Time',
  }),
  r('pci-10-6-1-b', {
    name: 'Synchronisation NTP — source de temps configurée (Req 10.6.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(w32tm /query /source)',
    expected: 'Local CMOS Clock',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'w32tm /config /manualpeerlist:"time.windows.com" /syncfromflags:manual /reliable:YES /update; Restart-Service -Name W32Time',
  }),
  r('pci-10-7-1', {
    name: 'Windows Event Log — service actif (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name EventLog -StartupType Automatic; Start-Service -Name EventLog',
  }),
  r('pci-10-7-1-b', {
    name: 'PowerShell Script Block Logging — activé (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging\' -Name \'EnableScriptBlockLogging\' -Value 1 -Type DWord',
  }),
  r('pci-10-7-1-c', {
    name: 'Audit — modification de stratégie d\'audit activé (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'AuditBaseObjects\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 11 — Tests de sécurité réguliers ───────────────────────────────

  r('pci-11-2-1', {
    name: 'Analyse de vulnérabilités — Windows Update dernière analyse récente (Req 11.2.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1 | Select-Object -ExpandProperty InstalledOn).ToString("yyyy-MM-dd")',
    expected: (new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)).toISOString().substring(0, 10),
    operator: 'gt',
    severity: 'high',
  }),
  r('pci-11-4-1', {
    name: 'Détection d\'intrusion — Windows Defender IDS activé (Req 11.4.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).BehaviorMonitorEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableBehaviorMonitoring $false',
  }),
  r('pci-11-5-1', {
    name: 'Détection de changements — Windows Defender IOAV activé (Req 11.5.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IoavProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -DisableIOAVProtection $false',
  }),
  r('pci-11-6-1', {
    name: 'Détection falsification HTTP — SmartScreen activé (Req 11.6.1)',
    category: 'Security Testing',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Name \'EnableSmartScreen\' -Value 1 -Type DWord',
  }),

  // ─── EXIGENCE 12 — Politiques de sécurité organisationnelles ─────────────────

  r('pci-12-1-1', {
    name: 'Notice de sécurité — message légal configuré à la connexion (Req 12.1.1)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('pci-12-1-2', {
    name: 'Titre de notice de sécurité — configuré (Req 12.1.2)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('pci-12-3-1', {
    name: 'Chiffrement RDP — niveau de chiffrement élevé (Req 12.3.1)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp\' -Name \'SecurityLayer\' -Value 2 -Type DWord',
  }),
  r('pci-12-3-3', {
    name: 'Chiffrement — FIPS activé (algorithmes approuvés) (Req 12.3.3)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy\' -Name \'Enabled\' -Value 1 -Type DWord',
  }),
  r('pci-12-5-1', {
    name: 'Inventaire — service de gestion d\'actifs (WMI) actif (Req 12.5.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Winmgmt',
    expected: 'Running',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Set-Service -Name Winmgmt -StartupType Automatic; Start-Service -Name Winmgmt',
  }),
  r('pci-12-6-1', {
    name: 'Formation sécurité — App Locker ou WDAC configuré (Req 12.6.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AppIDSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name AppIDSvc -StartupType Automatic; Start-Service -Name AppIDSvc',
  }),
  r('pci-12-10-1', {
    name: 'Réponse aux incidents — journal d\'événements système conservé (Req 12.10.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog System).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: '$log = Get-WinEvent -ListLog System; $log.MaximumSizeInBytes = 104857600; $log.SaveChanges()',
  }),

  // ─── EXIGENCE 1 (complément) — Pare-feu et sécurité réseau ───────────────────

  r('pci-1-net-01', {
    name: 'Pare-feu — action par défaut trafic sortant Public: bloquer (Req 1.2.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).DefaultOutboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -DefaultOutboundAction Block',
  }),
  r('pci-1-net-02', {
    name: 'Pare-feu — journalisation des paquets refusés (domaine) activée (Req 1.3.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-NetFirewallProfile -Profile Private -LogBlocked True',
  }),
  r('pci-1-net-03', {
    name: 'Pare-feu — journalisation des connexions réussies activée (Req 1.3.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogAllowed',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -LogAllowed True',
  }),
  r('pci-1-net-04', {
    name: 'IPv6 — désactivé si non utilisé dans le CDE (Req 1.2.5)',
    category: 'Network Security Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters|DisabledComponents',
    expected: '255',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters\' -Name \'DisabledComponents\' -Value 255 -Type DWord',
  }),
  r('pci-1-net-05', {
    name: 'Partage de connexion Internet (ICS) — service désactivé (Req 1.4.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service SharedAccess -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service -Name SharedAccess -Force -ErrorAction SilentlyContinue; Set-Service -Name SharedAccess -StartupType Disabled',
  }),
  r('pci-1-net-06', {
    name: 'Accès réseau — restriction des accès anonymes aux partages (Req 1.4.4)',
    category: 'Network Security Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|RestrictNullSessAccess',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters\' -Name \'RestrictNullSessAccess\' -Value 1 -Type DWord',
  }),
  r('pci-1-net-07', {
    name: 'NetBIOS sur TCP/IP — désactivé (Req 1.2.5)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters" -Name "NodeType" -ErrorAction SilentlyContinue).NodeType',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\NetBT\\Parameters\' -Name \'NodeType\' -Value 2 -Type DWord',
  }),
  r('pci-1-net-08', {
    name: 'LLMNR — désactivé (Req 1.2.5)',
    category: 'Network Security Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient|EnableMulticast',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient\' -Name \'EnableMulticast\' -Value 0 -Type DWord',
  }),
  r('pci-1-net-09', {
    name: 'Service Routing and Remote Access — désactivé si inutilisé (Req 1.4.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service RemoteAccess -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service -Name RemoteAccess -Force -ErrorAction SilentlyContinue; Set-Service -Name RemoteAccess -StartupType Disabled',
  }),
  r('pci-1-net-10', {
    name: 'Taille du journal de pare-feu — ≥ 16 Mo (Req 10.2.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogMaxSizeKilobytes',
    expected: '16384',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain,Private,Public -LogMaxSizeKilobytes 16384',
  }),

  // ─── EXIGENCE 2 (complément) — Configurations sécurisées ─────────────────────

  r('pci-2-cfg-01', {
    name: 'Windows Defender Credential Guard — activé (Req 2.2.7)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\CredentialGuard|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\CredentialGuard\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard\\Scenarios\\CredentialGuard\' -Name \'Enabled\' -Value 1 -Type DWord',
  }),
  r('pci-2-cfg-02', {
    name: 'Secure Boot — activé (Req 2.2.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Confirm-SecureBootUEFI -ErrorAction SilentlyContinue)',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-cfg-03', {
    name: 'Protocole NTLM v1 — désactivé (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '5',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'LmCompatibilityLevel\' -Value 5 -Type DWord',
  }),
  r('pci-2-cfg-04', {
    name: 'NTLMv2 — niveau de compatibilité LAN Manager (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '3',
    operator: 'gt',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'LmCompatibilityLevel\' -Value 5 -Type DWord',
  }),
  r('pci-2-cfg-05', {
    name: 'Windows Script Host — désactivé si inutilisé (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings\' -Name \'Enabled\' -Value 0 -Type DWord',
  }),
  r('pci-2-cfg-06', {
    name: 'Recherche dans le registre LSA — protection activée (Req 2.2.6)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'RunAsPPL\' -Value 1 -Type DWord',
  }),
  r('pci-2-cfg-07', {
    name: 'WDigest — authentification désactivée (Req 2.2.6)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest|UseLogonCredential',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest\' -Name \'UseLogonCredential\' -Value 0 -Type DWord',
  }),
  r('pci-2-cfg-08', {
    name: 'RC4 128/128 — chiffrement faible désactivé dans SCHANNEL (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128\' -Name \'Enabled\' -Value 0 -Type DWord',
  }),
  r('pci-2-cfg-09', {
    name: 'DES — chiffrement faible désactivé dans SCHANNEL (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\DES 56/56|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\DES 56/56\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\DES 56/56\' -Name \'Enabled\' -Value 0 -Type DWord',
  }),
  r('pci-2-cfg-10', {
    name: 'PowerShell — version 2 désactivée (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root -ErrorAction SilentlyContinue).State',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Disable-WindowsOptionalFeature -Online -FeatureName MicrosoftWindowsPowerShellV2Root -NoRestart',
  }),
  r('pci-2-cfg-11', {
    name: 'Service d\'impression (Print Spooler) — désactivé sur les serveurs non imprimeurs (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service Spooler -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service -Name Spooler -Force -ErrorAction SilentlyContinue; Set-Service -Name Spooler -StartupType Disabled',
  }),
  r('pci-2-cfg-12', {
    name: 'Remote Registry — service désactivé (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service RemoteRegistry -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service -Name RemoteRegistry -Force -ErrorAction SilentlyContinue; Set-Service -Name RemoteRegistry -StartupType Disabled',
  }),

  // ─── EXIGENCE 3 (complément) — Protection des données stockées ───────────────

  r('pci-3-data-01', {
    name: 'BitLocker — clé de récupération stockée dans AD ou Azure AD (Req 3.7.3)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).KeyProtector | Where-Object { $_.KeyProtectorType -eq "RecoveryPassword" } | Measure-Object).Count',
    expected: '1',
    operator: 'gt',
    severity: 'high',
  }),
  r('pci-3-data-02', {
    name: 'Service de protection des données — DPAPI actif (Req 3.7.3)',
    category: 'Stored Account Data Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'DPAPI',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Start-Service -Name DPAPI -ErrorAction SilentlyContinue',
  }),
  r('pci-3-data-03', {
    name: 'BitLocker — lecteur de données secondaire chiffré (Req 3.5.1)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume | Where-Object { $_.ProtectionStatus -eq "Off" } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 4 (complément) — Chiffrement des transmissions ─────────────────

  r('pci-4-tls-01', {
    name: 'TLS 1.0 — désactivé côté client (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-tls-02', {
    name: 'TLS 1.1 — désactivé côté client (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-tls-03', {
    name: 'SSL 2.0 — désactivé côté client (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Client\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Client\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Client\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-tls-04', {
    name: 'SSL 3.0 — désactivé côté client (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Client\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Client\' -Name \'Enabled\' -Value 0 -Type DWord; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Client\' -Name \'DisabledByDefault\' -Value 1 -Type DWord',
  }),
  r('pci-4-tls-05', {
    name: 'AES 256 — chiffrement fort activé dans SCHANNEL (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\AES 256/256|Enabled',
    expected: '4294967295',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\AES 256/256\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\AES 256/256\' -Name \'Enabled\' -Value 0xFFFFFFFF -Type DWord',
  }),
  r('pci-4-tls-06', {
    name: 'SHA-256 — algorithme de hachage fort activé (Req 3.5.1.2)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\SHA256|Enabled',
    expected: '4294967295',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\SHA256\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\SHA256\' -Name \'Enabled\' -Value 0xFFFFFFFF -Type DWord',
  }),
  r('pci-4-tls-07', {
    name: 'MD5 — algorithme de hachage faible désactivé (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\MD5|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\MD5\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Hashes\\MD5\' -Name \'Enabled\' -Value 0 -Type DWord',
  }),

  // ─── EXIGENCE 5 (complément) — Protection contre les malwares ────────────────

  r('pci-5-av-01', {
    name: 'Windows Defender — signatures antivirus âge ≤ 3 jours (Req 5.3.1)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '3',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Update-MpSignature -ErrorAction SilentlyContinue',
  }),
  r('pci-5-av-02', {
    name: 'Windows Defender — protection anti-spyware activée (Req 5.2.1)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntispywareEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('pci-5-av-03', {
    name: 'Windows Defender — protection IOAV activée (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IoavProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableIOAVProtection $false',
  }),
  r('pci-5-av-04', {
    name: 'Windows Defender — surveillance comportementale activée (Req 5.2.2)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).BehaviorMonitorEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableBehaviorMonitoring $false',
  }),
  r('pci-5-av-05', {
    name: 'Windows Defender — protection anti-ransomware (Controlled Folder Access) (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableControlledFolderAccess',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -EnableControlledFolderAccess Enabled',
  }),
  r('pci-5-av-06', {
    name: 'Windows Defender — scan des archives activé (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).DisableArchiveScanning',
    expected: 'False',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -DisableArchiveScanning $false',
  }),
  r('pci-5-av-07', {
    name: 'Windows Defender — scan des scripts activé (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).DisableScriptScanning',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableScriptScanning $false',
  }),

  // ─── EXIGENCE 6 (complément) — Développement et maintenance sécurisés ────────

  r('pci-6-dev-01', {
    name: 'Windows Defender Application Guard — activé (Req 6.4.1)',
    category: 'Secure Development',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WindowsOptionalFeature -Online -FeatureName Windows-Defender-ApplicationGuard -ErrorAction SilentlyContinue).State',
    expected: 'Enabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Enable-WindowsOptionalFeature -Online -FeatureName Windows-Defender-ApplicationGuard -NoRestart',
  }),
  r('pci-6-dev-02', {
    name: 'Stratégie d\'exécution PowerShell — restreinte (Req 6.2.4)',
    category: 'Secure Development',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ExecutionPolicy -Scope LocalMachine)',
    expected: 'Unrestricted',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force',
  }),
  r('pci-6-dev-03', {
    name: 'Windows Defender Exploit Protection — activé (Req 6.2.4)',
    category: 'Secure Development',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ProcessMitigation -System).Dep.Enable',
    expected: 'ON',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ProcessMitigation -System -Enable DEP',
  }),
  r('pci-6-dev-04', {
    name: 'DEP — Data Execution Prevention activée (Req 6.2.4)',
    category: 'Secure Development',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(bcdedit /enum {current} | Select-String "nx").ToString()',
    expected: 'AlwaysOn',
    operator: 'contains',
    severity: 'high',
    remediationScript: 'bcdedit /set {current} nx AlwaysOn',
  }),

  // ─── EXIGENCE 7 (complément) — Restriction d\'accès ──────────────────────────

  r('pci-7-acc-01', {
    name: 'Accès aux clés de registre sensibles — audit activé (Req 7.2.1)',
    category: 'Access Restriction',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921E-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921E-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-7-acc-02', {
    name: 'Accès aux objets sensibles — audit du système de fichiers activé (Req 7.2.1)',
    category: 'Access Restriction',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921D-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-7-acc-03', {
    name: 'Accès au réseau — restriction des comptes anonymes (Req 7.2.2)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|EveryoneIncludesAnonymous',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\' -Name \'EveryoneIncludesAnonymous\' -Value 0 -Type DWord',
  }),
  r('pci-7-acc-04', {
    name: 'Élévation de privilèges — détection d\'utilisation de privilèges sensibles (Req 7.2.3)',
    category: 'Access Restriction',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),

  // ─── EXIGENCE 8 (complément) — Authentification ───────────────────────────────

  r('pci-8-auth-01', {
    name: 'Stratégie de verrouillage — durée de verrouillage ≥ 30 minutes (Req 8.3.4)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^LockoutDuration\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '30',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'net accounts /lockoutduration:30',
  }),
  r('pci-8-auth-02', {
    name: 'Stratégie de verrouillage — fenêtre d\'observation ≥ 30 minutes (Req 8.3.4)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^ResetLockoutCount\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '30',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'net accounts /lockoutwindow:30',
  }),
  r('pci-8-auth-03', {
    name: 'Compte invité — désactivé (Req 8.2.2)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Disable-LocalUser -Name "Guest"',
  }),
  r('pci-8-auth-04', {
    name: 'Stratégie de mot de passe — historique minimum 5 (Req 8.3.7)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f = "$env:TEMP\\secpol_$PID.cfg"; try { secedit /export /cfg $f /quiet; (Select-String -Path $f -Pattern "^PasswordHistorySize\\s*=").ToString() -replace ".*=\\s*","" } finally { Remove-Item $f -Force -EA SilentlyContinue }',
    expected: '5',
    operator: 'gt',
    severity: 'high',
    remediationScript: 'net accounts /uniquepw:6',
  }),
  r('pci-8-auth-05', {
    name: 'Audit des créations de sessions — activé (Req 8.2.8)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE921B-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE921B-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('pci-8-auth-06', {
    name: 'Audit des déconnexions — activé (Req 8.2.8)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9216-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9216-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('pci-8-auth-07', {
    name: 'Audit des verrouillages de compte — activé (Req 8.3.4)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9217-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9217-69AE-11D9-BED3-505054503030}" /failure:enable',
  }),
  r('pci-8-auth-08', {
    name: 'RDP — couche de sécurité TLS obligatoire (Req 8.3.1)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp\' -Name \'SecurityLayer\' -Value 2 -Type DWord',
  }),

  // ─── EXIGENCE 10 (complément) — Journalisation ────────────────────────────────

  r('pci-10-log-01', {
    name: 'Audit de l\'utilisation des privilèges — activé (Req 10.2.1.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9229-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9229-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-log-02', {
    name: 'Audit de démarrage du système — activé (Req 10.2.1.6)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9214-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9214-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-10-log-03', {
    name: 'Journal des événements d\'application — taille ≥ 100 Mo (Req 10.5.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Application).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: '$log = Get-WinEvent -ListLog Application; $log.MaximumSizeInBytes = 104857600; $log.SaveChanges()',
  }),
  r('pci-10-log-04', {
    name: 'PowerShell Module Logging — activé (Req 10.2.2)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging|EnableModuleLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging\' -Name \'EnableModuleLogging\' -Value 1 -Type DWord',
  }),
  r('pci-10-log-05', {
    name: 'Transcription PowerShell — activée (Req 10.2.2)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription|EnableTranscripting',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription\' -Name \'EnableTranscripting\' -Value 1 -Type DWord',
  }),
  r('pci-10-log-06', {
    name: 'Audit d\'utilisation des handles — activé (Req 10.2.1.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9223-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9223-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('pci-10-log-07', {
    name: 'NTP — synchronisation avec le serveur de temps configuré (Req 10.6.1)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\W32Time\\Parameters|Type',
    expected: 'NTP',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\W32Time\\Parameters\' -Name \'Type\' -Value \'NTP\' -Type String',
  }),
  r('pci-10-log-08', {
    name: 'Audit des événements de plateforme — activé (Req 10.2.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9210-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9210-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),

  // ─── EXIGENCE 11 (complément) — Tests de sécurité ────────────────────────────

  r('pci-11-test-01', {
    name: 'Windows Defender — surveillance réseau (IDS) active (Req 11.4.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).NISEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableIntrusionPreventionSystem $false',
  }),
  r('pci-11-test-02', {
    name: 'Windows Defender — définitions NIS à jour (Req 11.2.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).NISSignatureAge',
    expected: '7',
    operator: 'lt',
    severity: 'high',
    remediationScript: 'Update-MpSignature -ErrorAction SilentlyContinue',
  }),
  r('pci-11-test-03', {
    name: 'Windows Defender — protection des applications contre les exploits activée (Req 11.3.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IsTamperProtected',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-11-test-04', {
    name: 'ASR (Attack Surface Reduction) — règles activées (Req 11.4.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).AttackSurfaceReductionRules_Actions | Where-Object { $_ -ne 0 } | Measure-Object).Count',
    expected: '1',
    operator: 'gt',
    severity: 'high',
  }),

  // ─── EXIGENCE 12 (complément) — Politiques de sécurité ───────────────────────

  r('pci-12-pol-01', {
    name: 'AppLocker — service d\'identité des applications actif (Req 12.6.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AppIDSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-Service -Name AppIDSvc -StartupType Automatic; Start-Service -Name AppIDSvc',
  }),
  r('pci-12-pol-02', {
    name: 'Audit de stratégie globale de changement — activé (Req 12.1.2)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9231-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9231-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-12-pol-03', {
    name: 'Inventaire des composants — service WMI actif (Req 12.5.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Winmgmt',
    expected: 'Running',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Set-Service -Name Winmgmt -StartupType Automatic; Start-Service -Name Winmgmt',
  }),
  r('pci-12-pol-04', {
    name: 'Plan de réponse aux incidents — service de journalisation des événements actif (Req 12.10.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-Service -Name EventLog -StartupType Automatic; Start-Service -Name EventLog',
  }),
  r('pci-12-pol-05', {
    name: 'Gestion des identités — audit des modifications de groupe activé (Req 12.4.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9237-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9237-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-12-pol-06', {
    name: 'Gestion des objets informatiques — audit de gestion des ordinateurs activé (Req 12.4.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"{0CCE9236-69AE-11D9-BED3-505054503030}" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9236-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('pci-12-pol-07', {
    name: 'Chiffrement FIPS 140 — algorithmes validés activés (Req 12.3.3)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy\' -Name \'Enabled\' -Value 1 -Type DWord',
  }),
  r('pci-12-pol-08', {
    name: 'Gestion à distance sécurisée — WinRM avec HTTPS seulement (Req 12.3.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Item WSMan:\\localhost\\Service\\AllowUnencrypted -ErrorAction SilentlyContinue).Value',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Item WSMan:\\localhost\\Service\\AllowUnencrypted -Value $false -Force',
  }),
  r('pci-12-pol-09', {
    name: 'WinRM — authentification de base désactivée (Req 12.3.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Item WSMan:\\localhost\\Service\\Auth\\Basic -ErrorAction SilentlyContinue).Value',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Item WSMan:\\localhost\\Service\\Auth\\Basic -Value $false -Force',
  }),

];
