import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const pciDSSv4Rules: ComplianceRule[] = [

  // ─── EXIGENCE 1 — Contrôles de sécurité réseau ───────────────────────────────

  r('pci-1-1-1', {
    name: 'Pare-feu — Profil Domain activé (Req 1.1.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-1-2', {
    name: 'Pare-feu — Profil Private activé (Req 1.1.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-1-3', {
    name: 'Pare-feu — Profil Public activé (Req 1.1.3)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-2-1', {
    name: 'Pare-feu — Action par défaut trafic entrant Domain: bloquer (Req 1.2.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).DefaultInboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-2-2', {
    name: 'Pare-feu — Action par défaut trafic entrant Public: bloquer (Req 1.2.1)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).DefaultInboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-2-3', {
    name: 'Pare-feu — Action par défaut trafic sortant Domain: autoriser (Req 1.2.2)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).DefaultOutboundAction',
    expected: 'Allow',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-1-2-4', {
    name: 'Pare-feu — Nombre de profils actifs (tous les profils couverts) (Req 1.2.3)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -All | Where-Object { $_.Enabled -eq $true }).Count',
    expected: '3',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-2-5', {
    name: 'Pare-feu — Journalisation des connexions refusées activée (Req 1.2.5)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-1-3-1', {
    name: 'Service pare-feu Windows — actif (Req 1.3.1)',
    category: 'Network Security Controls',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'MpsSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-1-4-1', {
    name: 'IPSec — service agent activé (NSC entre réseaux) (Req 1.4.1)',
    category: 'Network Security Controls',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'PolicyAgent',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-1-4-4', {
    name: 'Partage réseau — découverte réseau désactivée sur profil public (Req 1.4.4)',
    category: 'Network Security Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).NotifyOnListen',
    expected: 'False',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-1-5-1', {
    name: 'Accès distant (RDP) — NLA requis pour contrôles dispositifs distants (Req 1.5.1)',
    category: 'Network Security Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 2 — Configurations sécurisées ──────────────────────────────────

  r('pci-2-1-1', {
    name: 'Compte Administrateur local — désactivé ou renommé (Req 2.1.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-1-2', {
    name: 'Compte Invité local — désactivé (Req 2.1.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-2-1', {
    name: 'UAC — Contrôle de compte d\'utilisateur activé (Req 2.2.1)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-2-2-2', {
    name: 'UAC — Niveau d\'invite pour administrateurs (Req 2.2.2)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '0',
    operator: 'neq',
    severity: 'high',
  }),
  r('pci-2-2-3', {
    name: 'SMBv1 — protocole non sécurisé désactivé (Req 2.2.3)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-2-2-4', {
    name: 'SMBv2 — protocole sécurisé activé (Req 2.2.4)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB2Protocol',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-2-5', {
    name: 'Telnet — service désactivé (protocole non sécurisé) (Req 2.2.5)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WindowsOptionalFeature -Online -FeatureName TelnetClient -ErrorAction SilentlyContinue).State',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-2-6', {
    name: 'AutoRun — désactivé pour les supports amovibles (Req 2.2.6)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-2-7', {
    name: 'Chiffrement des accès non-console — RDP chiffrement fort (Req 2.2.7)',
    category: 'Secure Configurations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|MinEncryptionLevel',
    expected: '3',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-2-3-1', {
    name: 'SNMP — service désactivé si inutilisé (Req 2.3.1)',
    category: 'Secure Configurations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service SNMP -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── EXIGENCE 3 — Protection des données de compte stockées ──────────────────

  r('pci-3-5-1', {
    name: 'BitLocker — chiffrement du lecteur système activé (Req 3.5.1)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-3-5-1-1', {
    name: 'BitLocker — méthode de chiffrement AES 256 bits (Req 3.5.1.1)',
    category: 'Stored Account Data Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).EncryptionMethod',
    expected: 'Aes256',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-3-7-1', {
    name: 'Service de cryptographie Windows — actif (gestion des clés) (Req 3.7.1)',
    category: 'Stored Account Data Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'CryptSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-3-7-3', {
    name: 'Magasin de certificats — service de stockage sécurisé des clés actif (Req 3.7.3)',
    category: 'Stored Account Data Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'KeyIso',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── EXIGENCE 4 — Chiffrement des transmissions ───────────────────────────────

  r('pci-4-2-1-tls10', {
    name: 'TLS 1.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-tls11', {
    name: 'TLS 1.1 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-tls12', {
    name: 'TLS 1.2 — activé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-ssl2', {
    name: 'SSL 2.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-ssl3', {
    name: 'SSL 3.0 — désactivé côté serveur (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-rc4', {
    name: 'RC4 — chiffrement faible désactivé (Req 4.2.1)',
    category: 'Transmission Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-4-2-1-1', {
    name: 'Service HTTP.sys — certificats TLS valides requis (Req 4.2.1.1)',
    category: 'Transmission Encryption',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'HTTP',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── EXIGENCE 5 — Protection contre les malwares ──────────────────────────────

  r('pci-5-2-1', {
    name: 'Windows Defender Antivirus — service actif (Req 5.2.1)',
    category: 'Malware Protection',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WinDefend',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-2-2', {
    name: 'Windows Defender — antivirus activé (Req 5.2.2)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-2-3', {
    name: 'Windows Defender — protection en temps réel activée (Req 5.2.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-3-1', {
    name: 'Windows Defender — définitions à jour (Req 5.3.1)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '7',
    operator: 'lt',
    severity: 'high',
  }),
  r('pci-5-3-2', {
    name: 'Windows Defender — protection contre altération activée (Req 5.3.2)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender\\Features|TamperProtection',
    expected: '5',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-3-3', {
    name: 'Windows Defender — antivirus non désactivé (Req 5.3.2)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender|DisableAntiSpyware',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-5-3-4', {
    name: 'Windows Defender — protection réseau activée (Req 5.3.3)',
    category: 'Malware Protection',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableNetworkProtection',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-5-4-1', {
    name: 'Windows Defender SmartScreen — activé (anti-phishing) (Req 5.4.1)',
    category: 'Malware Protection',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 6 — Développement et maintenance sécurisés ─────────────────────

  r('pci-6-3-3', {
    name: 'Windows Update — correctifs automatiques activés (Req 6.3.3)',
    category: 'Secure Development',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-6-3-3-b', {
    name: 'Windows Update — options de mise à jour automatique configurées (Req 6.3.3)',
    category: 'Secure Development',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '3',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-6-5-1', {
    name: 'Service Windows Update — actif (Req 6.5.1)',
    category: 'Secure Development',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'wuauserv',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 7 — Restriction de l\'accès aux composants système ──────────────

  r('pci-7-2-1', {
    name: 'UAC — accès basé sur le besoin d\'en connaître appliqué (Req 7.2.1)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-7-2-2', {
    name: 'Moindre privilège — membres du groupe Administrators limités (Req 7.2.2)',
    category: 'Access Restriction',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group "Administrators" | Measure-Object).Count',
    expected: '3',
    operator: 'lt',
    severity: 'medium',
  }),
  r('pci-7-2-3', {
    name: 'UAC — élévation de privilèges requiert consentement (Req 7.2.3)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '2',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-7-3-1', {
    name: 'Credential Guard — protection des secrets d\'accès (Req 7.3.1)',
    category: 'Access Restriction',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 8 — Identification et authentification des utilisateurs ─────────

  r('pci-8-2-5', {
    name: 'Comptes inactifs — désactivés (contrôle via stratégie) (Req 8.2.5)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-8-2-6', {
    name: 'Délai d\'inactivité — verrouillage écran ≤ 15 minutes (Req 8.2.6)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
  }),
  r('pci-8-2-6-b', {
    name: 'Économiseur d\'écran — protégé par mot de passe (Req 8.2.6)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-8-3-4', {
    name: 'Stratégie de verrouillage — seuil de tentatives invalides (Req 8.3.4)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Lockout threshold").ToString().Split(":")[-1].Trim()',
    expected: '10',
    operator: 'lt',
    severity: 'critical',
  }),
  r('pci-8-3-5', {
    name: 'Stratégie de mot de passe — longueur minimum 12 caractères (Req 8.3.5)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Minimum password length").ToString().Split(":")[-1].Trim()',
    expected: '12',
    operator: 'gt',
    severity: 'critical',
  }),
  r('pci-8-3-6', {
    name: 'Stratégie de mot de passe — complexité requise activée (Req 8.3.6)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-ItemProperty -Path "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa" -Name "PasswordComplexity" -ErrorAction SilentlyContinue).PasswordComplexity',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-8-3-7', {
    name: 'Stratégie de mot de passe — historique (4 derniers minimum) (Req 8.3.7)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Length of password history maintained").ToString().Split(":")[-1].Trim()',
    expected: '4',
    operator: 'gt',
    severity: 'high',
  }),
  r('pci-8-3-9', {
    name: 'Stratégie de mot de passe — expiration max 90 jours (Req 8.3.9)',
    category: 'User Authentication',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Maximum password age").ToString().Split(":")[-1].Trim()',
    expected: '90',
    operator: 'lt',
    severity: 'high',
  }),
  r('pci-8-4-1', {
    name: 'NLA (MFA réseau) — requis pour RDP (Req 8.4.1)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-8-6-2', {
    name: 'PowerShell Script Block Logging — mots de passe hardcodés détectables (Req 8.6.2)',
    category: 'User Authentication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 9 — Restriction de l\'accès physique ───────────────────────────

  r('pci-9-5-1', {
    name: 'Verrouillage physique — verrouillage de session requis (protection POS) (Req 9.5.1)',
    category: 'Physical Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-9-4-2', {
    name: 'Journal des accès physiques — audit d\'ouverture de session activé (Req 9.4.2)',
    category: 'Physical Access',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── EXIGENCE 10 — Journalisation et surveillance ────────────────────────────

  r('pci-10-2-1', {
    name: 'Journal de sécurité Windows — activé (Req 10.2.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-10-2-1-1', {
    name: 'Audit — accès aux données (Object Access) activé (Req 10.2.1.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"File System" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-2-1-2', {
    name: 'Audit — actions administratives (Privilege Use) activé (Req 10.2.1.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Sensitive Privilege Use" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-2-1-3', {
    name: 'Audit — accès au journal d\'audit activé (Req 10.2.1.3)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Audit Policy Change" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-2-1-4', {
    name: 'Audit — tentatives d\'accès invalides activé (Req 10.2.1.4)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-10-2-1-5', {
    name: 'Audit — utilisation des mécanismes d\'identification (Req 10.2.1.5)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-2-1-6', {
    name: 'Audit — démarrage/arrêt des journaux d\'audit (Req 10.2.1.6)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Security System Extension" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-2-1-7', {
    name: 'Audit — création et suppression d\'objets système (Req 10.2.1.7)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Process Creation" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-10-3-1', {
    name: 'Journal de sécurité — taille minimale 192 Mo (Req 10.3.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
  }),
  r('pci-10-3-2', {
    name: 'Journal des événements — politique de rétention configurée (Req 10.3.2)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).LogMode',
    expected: 'Circular',
    operator: 'neq',
    severity: 'medium',
  }),
  r('pci-10-5-1', {
    name: 'Journal des applications — taille minimale 100 Mo (Req 10.5.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Application).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'medium',
  }),
  r('pci-10-6-1', {
    name: 'Synchronisation NTP — service de temps Windows actif (Req 10.6.1)',
    category: 'Logging and Monitoring',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'W32Time',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-6-1-b', {
    name: 'Synchronisation NTP — source de temps configurée (Req 10.6.1)',
    category: 'Logging and Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(w32tm /query /source)',
    expected: 'Local CMOS Clock',
    operator: 'neq',
    severity: 'medium',
  }),
  r('pci-10-7-1', {
    name: 'Windows Event Log — service actif (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('pci-10-7-1-b', {
    name: 'PowerShell Script Block Logging — activé (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-10-7-1-c', {
    name: 'Audit — modification de stratégie d\'audit activé (Req 10.7.1)',
    category: 'Logging and Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── EXIGENCE 11 — Tests de sécurité réguliers ───────────────────────────────

  r('pci-11-2-1', {
    name: 'Analyse de vulnérabilités — Windows Update dernière analyse récente (Req 11.2.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1 | Select-Object -ExpandProperty InstalledOn).ToString("yyyy-MM-dd")',
    expected: (new Date(Date.now() - 90 * 24 * 60 * 60 * 1000)).toISOString().substring(0, 10),
    operator: 'gt',
    severity: 'high',
  }),
  r('pci-11-4-1', {
    name: 'Détection d\'intrusion — Windows Defender IDS activé (Req 11.4.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).BehaviorMonitorEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-11-5-1', {
    name: 'Détection de changements — Windows Defender IOAV activé (Req 11.5.1)',
    category: 'Security Testing',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IoavProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-11-6-1', {
    name: 'Détection falsification HTTP — SmartScreen activé (Req 11.6.1)',
    category: 'Security Testing',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── EXIGENCE 12 — Politiques de sécurité organisationnelles ─────────────────

  r('pci-12-1-1', {
    name: 'Notice de sécurité — message légal configuré à la connexion (Req 12.1.1)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('pci-12-1-2', {
    name: 'Titre de notice de sécurité — configuré (Req 12.1.2)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('pci-12-3-1', {
    name: 'Chiffrement RDP — niveau de chiffrement élevé (Req 12.3.1)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'high',
  }),
  r('pci-12-3-3', {
    name: 'Chiffrement — FIPS activé (algorithmes approuvés) (Req 12.3.3)',
    category: 'Security Policy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\FipsAlgorithmPolicy|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-12-5-1', {
    name: 'Inventaire — service de gestion d\'actifs (WMI) actif (Req 12.5.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Winmgmt',
    expected: 'Running',
    operator: 'eq',
    severity: 'low',
  }),
  r('pci-12-6-1', {
    name: 'Formation sécurité — App Locker ou WDAC configuré (Req 12.6.1)',
    category: 'Security Policy',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AppIDSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('pci-12-10-1', {
    name: 'Réponse aux incidents — journal d\'événements système conservé (Req 12.10.1)',
    category: 'Security Policy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog System).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'medium',
  }),

];
