import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const soc2Rules: ComplianceRule[] = [

  // ─── CC1 — Environnement de contrôle ─────────────────────────────────────────

  r('soc2-CC1-001', {
    name: 'Notice légale configurée (engagement de la direction) [CC1]',
    category: 'Control Environment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-CC1-002', {
    name: 'Titre de notice légale configuré [CC1]',
    category: 'Control Environment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-CC1-003', {
    name: 'Journalisation des événements activée (surveillance) [CC1]',
    category: 'Control Environment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service EventLog).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC1-004', {
    name: 'Defender — Surveillance de sécurité active [CC1]',
    category: 'Control Environment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC1-005', {
    name: 'Defender — Protection anti-manipulation (intégrité) [CC1]',
    category: 'Control Environment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IsTamperProtected',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC2 — Communication et information ──────────────────────────────────────

  r('soc2-CC2-001', {
    name: 'Windows Update — Notifications de sécurité activées [CC2]',
    category: 'Communication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC2-002', {
    name: 'Journal de sécurité — Taille suffisante [CC2]',
    category: 'Communication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security|MaxSize',
    expected: '196607',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC2-003', {
    name: 'Avertissement de connexion utilisateur [CC2]',
    category: 'Communication',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),

  // ─── CC3 — Évaluation des risques ────────────────────────────────────────────

  r('soc2-CC3-001', {
    name: 'Signatures Defender à jour (≤ 7 jours) [CC3]',
    category: 'Risk Assessment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '8',
    operator: 'lt',
    severity: 'critical',
  }),
  r('soc2-CC3-002', {
    name: 'AppLocker / WDAC — Contrôle des applications [CC3]',
    category: 'Risk Assessment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service AppIDSvc -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-CC3-003', {
    name: 'Règles ASR — Réduction de la surface d\'attaque [CC3]',
    category: 'Risk Assessment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR|ExploitGuard_ASR_Rules',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC3-004', {
    name: 'Defender — Renseignements sur les menaces cloud [CC3]',
    category: 'Risk Assessment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).MAPSReporting',
    expected: '0',
    operator: 'neq',
    severity: 'high',
  }),

  // ─── CC4 — Activités de surveillance ─────────────────────────────────────────

  r('soc2-CC4-001', {
    name: 'Defender — Protection temps réel continue [CC4]',
    category: 'Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC4-002', {
    name: 'Journal de sécurité — Capacité de surveillance suffisante [CC4]',
    category: 'Monitoring',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\Security|MaxSize',
    expected: '196607',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC4-003', {
    name: 'Audit — Ouvertures de session surveillées [CC4]',
    category: 'Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-CC4-004', {
    name: 'Service de journalisation des événements actif [CC4]',
    category: 'Monitoring',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service EventLog).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC5 — Activités de contrôle ─────────────────────────────────────────────

  r('soc2-CC5-001', {
    name: 'Gestion des changements — Windows Update auto [CC5]',
    category: 'Control Activities',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC5-002', {
    name: 'Gestion des correctifs — Historique de patches [CC5]',
    category: 'Control Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 1).InstalledOn',
    expected: '',
    operator: 'exists',
    severity: 'high',
  }),
  r('soc2-CC5-003', {
    name: 'SMBv1 désactivé (baseline de configuration) [CC5]',
    category: 'Control Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC5-004', {
    name: 'UAC — Contrôles de base activés [CC5]',
    category: 'Control Activities',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC5-005', {
    name: 'Séparation des responsabilités — Mode approbation admin [CC5]',
    category: 'Control Activities',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|FilterAdministratorToken',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC6 — Contrôles d'accès logiques et physiques ───────────────────────────

  r('soc2-CC6-001', {
    name: 'Identifiants uniques — Compte Invité désactivé [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name Guest).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-002', {
    name: 'Révocation des accès — Compte Administrateur désactivé [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name Administrator).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-003', {
    name: 'Complexité des mots de passe activée [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(secedit /export /cfg "$env:TEMP\\secpol.cfg" | Out-Null); (Get-Content "$env:TEMP\\secpol.cfg" | Where-Object {$_ -match "PasswordComplexity"}).Split("=")[1].Trim()',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-004', {
    name: 'Longueur minimale du mot de passe ≥ 12 [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "((([adsi]'WinNT://localhost').minPasswordLength.Value)",
    expected: '11',
    operator: 'gt',
    severity: 'critical',
  }),
  r('soc2-CC6-005', {
    name: 'Historique des mots de passe ≥ 12 [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "((([adsi]'WinNT://localhost').PasswordHistoryLength.Value)",
    expected: '11',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC6-006', {
    name: 'Âge maximal du mot de passe ≤ 90 jours [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "((([adsi]'WinNT://localhost').maxPasswordAge.Value) / 86400)",
    expected: '91',
    operator: 'lt',
    severity: 'high',
  }),
  r('soc2-CC6-007', {
    name: 'Verrouillage de compte ≤ 5 tentatives [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "((([adsi]'WinNT://localhost').MaxBadPasswordsAllowed.Value)",
    expected: '6',
    operator: 'lt',
    severity: 'critical',
  }),
  r('soc2-CC6-008', {
    name: 'Durée de verrouillage ≥ 30 minutes [CC6]',
    category: 'Access Control',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "((([adsi]'WinNT://localhost').LockoutObservationInterval.Value) / 60)",
    expected: '29',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC6-009', {
    name: 'Authentification multi-facteur — Credential Guard [CC6]',
    category: 'Access Control',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-010', {
    name: 'NTLMv2 uniquement [CC6]',
    category: 'Access Control',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '5',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-011', {
    name: 'WDigest — Identifiants en mémoire désactivés [CC6]',
    category: 'Access Control',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest|UseLogonCredential',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-012', {
    name: 'LSA — Processus protégé activé [CC6]',
    category: 'Access Control',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-013', {
    name: 'Délai d\'inactivité de session RDP [CC6]',
    category: 'Session Management',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MaxIdleTime',
    expected: '900001',
    operator: 'lt',
    severity: 'high',
  }),
  r('soc2-CC6-014', {
    name: 'Verrouillage d\'écran protégé par mot de passe [CC6]',
    category: 'Access Control',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-015', {
    name: 'Chiffrement au repos — BitLocker OS [CC6]',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint C:).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-016', {
    name: 'Chiffrement en transit — TLS 1.0 désactivé [CC6]',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-017', {
    name: 'RDP — NLA requis [CC6]',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-018', {
    name: 'Pare-feu actif sur tous les profils [CC6]',
    category: 'Network Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: "(Get-NetFirewallProfile | Where-Object {$_.Enabled -ne $true} | Measure-Object).Count",
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-019', {
    name: 'Stockage USB restreint [CC6]',
    category: 'Physical Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR|Start',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-020', {
    name: 'Accès réseau anonyme restreint [CC6]',
    category: 'Network Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymous',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC7 — Opérations système ─────────────────────────────────────────────────

  r('soc2-CC7-001', {
    name: 'Defender — Surveillance système temps réel [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-002', {
    name: 'Defender — Détection d\'anomalies comportementales [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).DisableBehaviorMonitoring',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-003', {
    name: 'Centre de sécurité Windows — Alertes actives [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wscsvc).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-004', {
    name: 'Defender — Analyses planifiées configurées [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).ScanScheduleDay',
    expected: '8',
    operator: 'neq',
    severity: 'high',
  }),
  r('soc2-CC7-005', {
    name: 'Réponse aux incidents — Journalisation PowerShell [CC7]',
    category: 'System Operations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-006', {
    name: 'Disponibilité — Service Journal des événements actif [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service EventLog).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-007', {
    name: 'Sauvegarde — Volume Shadow Copy actif [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service VSS).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-008', {
    name: 'Surveillance des correctifs — Windows Update configuré [CC7]',
    category: 'System Operations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-009', {
    name: 'Surveillance des processus — Audit création de processus [CC7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Process Creation" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-CC7-010', {
    name: 'Surveillance réseau — Journalisation pare-feu [CC7]',
    category: 'System Operations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\WindowsFirewall\\DomainProfile\\Logging|LogDroppedPackets',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── CC8 — Gestion des changements ───────────────────────────────────────────

  r('soc2-CC8-001', {
    name: 'Détection des changements — Audit modification de stratégie [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Audit Policy Change" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-CC8-002', {
    name: 'Changements non autorisés — Protection anti-manipulation [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).IsTamperProtected',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC8-003', {
    name: 'Contrôle des changements logiciels — Windows Update [CC8]',
    category: 'Change Management',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC8-004', {
    name: 'Audit registre Windows [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Registry" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'medium',
  }),
  r('soc2-CC8-005', {
    name: 'Audit des modifications de comptes utilisateurs [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-CC8-006', {
    name: 'Vérification d\'intégrité système [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC8-007', {
    name: 'Baseline de configuration — SMBv1 désactivé [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC8-008', {
    name: 'Capacité de retour arrière — VSS/Sauvegarde [CC8]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service VSS).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── CC9 — Atténuation des risques ───────────────────────────────────────────

  r('soc2-CC9-001', {
    name: 'Atténuation des menaces — Règles ASR activées [CC9]',
    category: 'Risk Mitigation',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR|ExploitGuard_ASR_Rules',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC9-002', {
    name: 'Risque fournisseur — Mises à jour automatiques [CC9]',
    category: 'Risk Mitigation',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC9-003', {
    name: 'Continuité d\'activité — Sauvegarde VSS active [CC9]',
    category: 'Risk Mitigation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service VSS).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC9-004', {
    name: 'Sécurité réseau — Pare-feu Domain actif [CC9]',
    category: 'Risk Mitigation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC9-005', {
    name: 'Chiffrement — BitLocker OS actif [CC9]',
    category: 'Risk Mitigation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint C:).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),

  // ─── A1 — Disponibilité ───────────────────────────────────────────────────────

  r('soc2-A1-001', {
    name: 'Disponibilité système — Windows Update activé [A1]',
    category: 'Availability',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-A1-002', {
    name: 'Sauvegarde — VSS actif [A1]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service VSS).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-A1-003', {
    name: 'Espace disque disponible sur C: [A1]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-PSDrive C | Select-Object -ExpandProperty Free)',
    expected: '0',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-A1-004', {
    name: 'Redondance — Service Sauvegarde Windows actif [A1]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service -Name SDRSVC -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-A1-005', {
    name: 'Récupération — Clé de récupération BitLocker configurée [A1]',
    category: 'Availability',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\FVE|OSRecovery',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── PI1 — Intégrité du traitement ───────────────────────────────────────────

  r('soc2-PI1-001', {
    name: 'Intégrité des données — Defender temps réel [PI1]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-PI1-002', {
    name: 'Audit de création de processus [PI1]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Process Creation" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-PI1-003', {
    name: 'Audit d\'accès aux objets système de fichiers [PI1]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"File System" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Failure',
    operator: 'contains',
    severity: 'high',
  }),
  r('soc2-PI1-004', {
    name: 'Journalisation des transactions — Autres accès objets [PI1]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Other Object Access Events" /r | ConvertFrom-Csv)."Inclusion Setting"',
    expected: 'Success',
    operator: 'contains',
    severity: 'medium',
  }),

  // ─── C1 — Confidentialité ─────────────────────────────────────────────────────

  r('soc2-C1-001', {
    name: 'Chiffrement au repos — BitLocker OS [C1]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint C:).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-C1-002', {
    name: 'TLS 1.0 serveur désactivé [C1]',
    category: 'Confidentiality',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-C1-003', {
    name: 'WDigest — Identifiants en clair désactivés [C1]',
    category: 'Confidentiality',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest|UseLogonCredential',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-C1-004', {
    name: 'Stockage USB restreint (prévention de fuite de données) [C1]',
    category: 'Confidentiality',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USBSTOR|Start',
    expected: '4',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-C1-005', {
    name: 'Accès contrôlé aux dossiers (DLP) activé [C1]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableControlledFolderAccess',
    expected: '0',
    operator: 'neq',
    severity: 'high',
  }),

  // ─── P1 — Vie privée ─────────────────────────────────────────────────────────

  r('soc2-P1-001', {
    name: 'Télémétrie Windows restreinte [P1]',
    category: 'Privacy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|AllowTelemetry',
    expected: '0',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-P1-002', {
    name: 'Données de diagnostic minimisées [P1]',
    category: 'Privacy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|DoNotShowFeedbackNotifications',
    expected: '1',
    operator: 'eq',
    severity: 'low',
  }),
  r('soc2-P1-003', {
    name: 'OneDrive — Synchronisation désactivée [P1]',
    category: 'Privacy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive|DisableFileSyncNGSC',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-P1-004', {
    name: 'Notifications de retour Microsoft désactivées [P1]',
    category: 'Privacy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|DoNotShowFeedbackNotifications',
    expected: '1',
    operator: 'eq',
    severity: 'low',
  }),

];
