import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const soc2Rules: ComplianceRule[] = [

  // ─── CC1 — Environnement de contrôle ─────────────────────────────────────────

  r('soc2-CC1-1', {
    name: 'Engagement valeurs éthiques — message légal de connexion configuré [CC1.1]',
    category: 'Control Environment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-CC1-2', {
    name: 'Titre de notice légale — titre du message de connexion configuré [CC1.1]',
    category: 'Control Environment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-CC1-3', {
    name: 'Structure organisationnelle — UAC applique la hiérarchie d\'autorité [CC1.3]',
    category: 'Control Environment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC1-4', {
    name: 'Compétences requises — groupe Administrators limité aux comptes nécessaires [CC1.4]',
    category: 'Control Environment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalGroupMember -Group "Administrators" | Measure-Object).Count',
    expected: '3',
    operator: 'lt',
    severity: 'medium',
  }),
  r('soc2-CC1-5', {
    name: 'Responsabilités et sanctions — audit de gestion des comptes activé [CC1.5]',
    category: 'Control Environment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC2 — Communication et information ──────────────────────────────────────

  r('soc2-CC2-1', {
    name: 'Informations pertinentes capturées — journal des événements actif [CC2.1]',
    category: 'Communication and Information',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'EventLog',
    expected: 'Running',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC2-2', {
    name: 'Politiques communiquées — message légal affiché aux utilisateurs [CC2.2]',
    category: 'Communication and Information',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-CC2-3', {
    name: 'Communication externe — NTP configuré pour horodatage cohérent [CC2.3]',
    category: 'Communication and Information',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'W32Time',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── CC3 — Évaluation des risques ────────────────────────────────────────────

  r('soc2-CC3-1', {
    name: 'Objectifs définis — Windows Defender actif (objectif de sécurité) [CC3.1]',
    category: 'Risk Assessment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC3-2', {
    name: 'Gestion des risques — mises à jour automatiques activées [CC3.2]',
    category: 'Risk Assessment',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC3-3', {
    name: 'Analyse des fraudes — audit des changements de stratégie activé [CC3.3]',
    category: 'Risk Assessment',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Audit Policy Change" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC3-4', {
    name: 'Changements significatifs — service Windows Update actif (détection des patchs) [CC3.4]',
    category: 'Risk Assessment',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'wuauserv',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC4 — Activités de surveillance ─────────────────────────────────────────

  r('soc2-CC4-1', {
    name: 'Évaluations continues — taille du journal de sécurité ≥ 192 Mo [CC4.1]',
    category: 'Monitoring Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC4-2', {
    name: 'Déficiences communiquées — audit des modifications de comptes activé [CC4.2]',
    category: 'Monitoring Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC5 — Activités de contrôle ─────────────────────────────────────────────

  r('soc2-CC5-1', {
    name: 'Contrôles sélectionnés — protection en temps réel Defender active [CC5.1]',
    category: 'Control Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC5-2', {
    name: 'Contrôles généraux IT — pare-feu actif sur tous les profils [CC5.2]',
    category: 'Control Activities',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile | Where-Object { $_.Enabled -ne $true }).Count',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC5-3', {
    name: 'Procédures déployées — SmartScreen activé (protection applicative) [CC5.3]',
    category: 'Control Activities',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC6 — Contrôles d\'accès logique et physique ─────────────────────────────

  r('soc2-CC6-1', {
    name: 'Politiques d\'accès logique — UAC activé [CC6.1]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-2', {
    name: 'Accès privilégié géré — compte Administrateur intégré désactivé [CC6.2]',
    category: 'Logical and Physical Access Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Administrator" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-3', {
    name: 'Accès révoqué — comptes inactifs (>90 jours) désactivés [CC6.3]',
    category: 'Logical and Physical Access Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser | Where-Object { $_.Enabled -eq $true -and $_.LastLogon -lt (Get-Date).AddDays(-90) -and $_.LastLogon -ne $null } | Measure-Object).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-4', {
    name: 'Accès physique — verrouillage de session automatique configuré [CC6.4]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaveTimeOut',
    expected: '900',
    operator: 'lt',
    severity: 'high',
  }),
  r('soc2-CC6-4-b', {
    name: 'Accès physique — économiseur d\'écran protégé par mot de passe [CC6.4]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-5', {
    name: 'Authentification multifacteur — NLA requis pour RDP [CC6.5]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-6', {
    name: 'Connexions réseau filtrées — pare-feu actif (3 profils) [CC6.6]',
    category: 'Logical and Physical Access Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain,Private,Public | Where-Object { $_.Enabled -eq $true }).Count',
    expected: '3',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-7', {
    name: 'Transmissions restreintes — TLS 1.0 désactivé [CC6.7]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-7-b', {
    name: 'Transmissions restreintes — TLS 1.1 désactivé [CC6.7]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-7-c', {
    name: 'Transmissions restreintes — TLS 1.2 activé [CC6.7]',
    category: 'Logical and Physical Access Controls',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.2\\Server|Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC6-8', {
    name: 'Logiciels non autorisés prévenus — AppLocker/WDAC configuré [CC6.8]',
    category: 'Logical and Physical Access Controls',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AppIDSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC6-8-b', {
    name: 'Logiciels non autorisés prévenus — SMBv1 désactivé [CC6.8]',
    category: 'Logical and Physical Access Controls',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),

  // ─── CC7 — Opérations système ─────────────────────────────────────────────────

  r('soc2-CC7-1', {
    name: 'Vulnérabilités surveillées — Defender antivirus actif [CC7.1]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-2', {
    name: 'Menaces surveillées — protection en temps réel Defender active [CC7.2]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).RealTimeProtectionEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-3', {
    name: 'Réponse aux incidents — journal des événements de sécurité actif [CC7.3]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-4', {
    name: 'Incidents enregistrés — audit des connexions activé (Success and Failure) [CC7.4]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-5', {
    name: 'Journaux d\'événements — taille du journal de sécurité ≥ 192 Mo [CC7.5]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes',
    expected: '196608',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-CC7-6', {
    name: 'Journalisation des événements de sécurité — activée [CC7.6]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).IsEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-7', {
    name: 'Audit de connexion — réussies et échouées activé [CC7.7]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Logon" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-CC7-8', {
    name: 'Audit de gestion des comptes — activé [CC7.8]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"User Account Management" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC7-9', {
    name: 'Windows Event Forwarding — service WecSvc actif (centralisation des logs) [CC7.9]',
    category: 'System Operations',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service WecSvc -ErrorAction SilentlyContinue).Status',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-CC7-9-b', {
    name: 'PowerShell Script Block Logging — activé pour audit des scripts [CC7.9]',
    category: 'System Operations',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC8 — Gestion des changements ───────────────────────────────────────────

  r('soc2-CC8-1', {
    name: 'Processus de changement — Windows Update configure les correctifs [CC8.1]',
    category: 'Change Management',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'wuauserv',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC8-2', {
    name: 'Modifications autorisées — signature de pilotes imposée [CC8.2]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(bcdedit /enum {current} | Select-String "nointegritychecks").Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC8-3', {
    name: 'Tests de sécurité avant déploiement — Defender à jour (signatures récentes) [CC8.3]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusSignatureAge',
    expected: '7',
    operator: 'lt',
    severity: 'high',
  }),
  r('soc2-CC8-4', {
    name: 'Changements d\'urgence documentés — audit de stratégie activé [CC8.4]',
    category: 'Change Management',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Audit Policy Change" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── CC9 — Atténuation des risques ───────────────────────────────────────────

  r('soc2-CC9-1', {
    name: 'Stratégies de mitigation — protection réseau Defender activée [CC9.1]',
    category: 'Risk Mitigation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).EnableNetworkProtection',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-CC9-2', {
    name: 'Risques fournisseurs gérés — pare-feu profil Public bloque le trafic entrant [CC9.2]',
    category: 'Risk Mitigation',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).DefaultInboundAction',
    expected: 'Block',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── A1 — Disponibilité ───────────────────────────────────────────────────────

  r('soc2-A1-1', {
    name: 'Monitoring de disponibilité — service WMI actif [A1.1]',
    category: 'Availability',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Winmgmt',
    expected: 'Running',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-A1-2', {
    name: 'Plan de reprise — service de sauvegarde Windows Engine configuré [A1.2]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wbengine -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
  }),
  r('soc2-A1-3', {
    name: 'Sauvegardes planifiées — service Volume Shadow Copy actif [A1.3]',
    category: 'Availability',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'VSS',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-A1-4', {
    name: 'Capacité système surveillée — espace disque système ≥ 20% libre [A1.4]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '[math]::Round((Get-PSDrive C | Select-Object -ExpandProperty Free) / ((Get-PSDrive C).Used + (Get-PSDrive C).Free) * 100)',
    expected: '20',
    operator: 'gt',
    severity: 'medium',
  }),
  r('soc2-A1-5', {
    name: 'Service de pare-feu — protection DDoS de base (MpsSvc actif) [A1.5]',
    category: 'Availability',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'MpsSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-A1-6', {
    name: 'Service de sauvegarde Windows — type de démarrage automatique [A1.6]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wbengine -ErrorAction SilentlyContinue).StartType',
    expected: 'Automatic',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-A1-7', {
    name: 'Espace disque disponible — ≥ 20% du disque système [A1.7]',
    category: 'Availability',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '[math]::Round((Get-PSDrive C | Select-Object -ExpandProperty Free) / ((Get-PSDrive C).Used + (Get-PSDrive C).Free) * 100)',
    expected: '20',
    operator: 'gt',
    severity: 'medium',
  }),

  // ─── PI1 — Intégrité du traitement ───────────────────────────────────────────

  r('soc2-PI1-1', {
    name: 'Intégrité du traitement — audit des accès aux objets activé [PI1.1]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"File System" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-PI1-2', {
    name: 'Traitement complet et exact — service de cryptographie actif (intégrité des données) [PI1.2]',
    category: 'Processing Integrity',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'CryptSvc',
    expected: 'Running',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-PI1-3', {
    name: 'Sorties système revues — audit des créations de processus activé [PI1.3]',
    category: 'Processing Integrity',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"Process Creation" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── C1 — Confidentialité ─────────────────────────────────────────────────────

  r('soc2-C1-1', {
    name: 'Données confidentielles classifiées — base d\'audit LSA activée [C1.1]',
    category: 'Confidentiality',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-C1-2', {
    name: 'Données confidentielles chiffrées au repos — BitLocker actif [C1.2]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-C1-2-b', {
    name: 'Chiffrement BitLocker — méthode AES 256 bits [C1.2]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).EncryptionMethod',
    expected: 'Aes256',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-C1-3', {
    name: 'Suppression sécurisée — AutoRun désactivé (prévention exfiltration) [C1.3]',
    category: 'Confidentiality',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'medium',
  }),
  r('soc2-C1-4', {
    name: 'Accès données confidentielles restreint — compte Invité désactivé [C1.4]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-C1-5', {
    name: 'Accords de confidentialité — audit de partage de fichiers activé [C1.5]',
    category: 'Confidentiality',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(auditpol /get /subcategory:"File Share" /r | ConvertFrom-Csv | Select-Object -ExpandProperty "Inclusion Setting")',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'medium',
  }),

  // ─── P1 — Confidentialité des données personnelles ───────────────────────────

  r('soc2-P1-1', {
    name: 'Notice de confidentialité — message légal de connexion affiché [P1.1]',
    category: 'Privacy',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeText',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('soc2-P1-3', {
    name: 'Données personnelles protégées — pare-feu Windows actif [P1.3]',
    category: 'Privacy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile | Where-Object { $_.Enabled -ne $true }).Count',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-P1-6', {
    name: 'Violations de confidentialité détectées — Defender surveillance comportementale [P1.6]',
    category: 'Privacy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).BehaviorMonitorEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-P1-7', {
    name: 'Politique de rétention des données — taille du journal système ≥ 100 Mo [P1.7]',
    category: 'Privacy',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog System).MaximumSizeInBytes',
    expected: '102400',
    operator: 'gt',
    severity: 'medium',
  }),

  // ─── Contrôles de sécurité Windows additionnels SOC2 ─────────────────────────

  r('soc2-sec-1', {
    name: 'Chiffrement BitLocker — activé [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive -ErrorAction SilentlyContinue).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-sec-2', {
    name: 'Antivirus Defender — activé [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpComputerStatus).AntivirusEnabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-sec-3', {
    name: 'Mises à jour automatiques — activées [SOC2 Security]',
    category: 'Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '3',
    operator: 'gt',
    severity: 'high',
  }),
  r('soc2-sec-4', {
    name: 'Compte invité — désactivé [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-LocalUser -Name "Guest" -ErrorAction SilentlyContinue).Enabled',
    expected: 'False',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-sec-5', {
    name: 'Durée de vie maximale du mot de passe — ≤ 90 jours [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Maximum password age").ToString().Split(":")[-1].Trim()',
    expected: '90',
    operator: 'lt',
    severity: 'high',
  }),
  r('soc2-sec-6', {
    name: 'Complexité du mot de passe — activée [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(net accounts | Select-String "Password must meet complexity requirements").ToString()',
    expected: 'Yes',
    operator: 'contains',
    severity: 'critical',
  }),
  r('soc2-sec-7', {
    name: 'NLA requis pour RDP [SOC2 Security]',
    category: 'Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-sec-8', {
    name: 'SMBv1 — désactivé [SOC2 Security]',
    category: 'Security',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-SmbServerConfiguration).EnableSMB1Protocol',
    expected: 'False',
    operator: 'eq',
    severity: 'critical',
  }),
  r('soc2-sec-9', {
    name: 'PowerShell Script Block Logging — activé [SOC2 Security]',
    category: 'Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('soc2-sec-10', {
    name: 'Accès distant sécurisé — connexion RDP chiffrée niveau élevé [SOC2 Security]',
    category: 'Security',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp|MinEncryptionLevel',
    expected: '3',
    operator: 'eq',
    severity: 'high',
  }),

];
