import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const windowsBaselineRules: ComplianceRule[] = [

  // ─── FIREWALL (10) ──────────────────────────────────────────────────────────

  r('wsb-001', {
    name: 'Pare-feu — Profil Domain activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -Enabled True',
  }),
  r('wsb-002', {
    name: 'Pare-feu — Profil Private activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Private -Enabled True',
  }),
  r('wsb-003', {
    name: 'Pare-feu — Profil Public activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -Enabled True',
  }),
  r('wsb-004', {
    name: 'Pare-feu — Trafic entrant Domain bloqué par défaut',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-NetFirewallProfile -Profile Domain).DefaultInboundAction -ne "Allow"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-NetFirewallProfile -Profile Domain -DefaultInboundAction Block',
  }),
  r('wsb-005', {
    name: 'Pare-feu — Trafic entrant Public bloqué par défaut',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-NetFirewallProfile -Profile Public).DefaultInboundAction -ne "Allow"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-NetFirewallProfile -Profile Public -DefaultInboundAction Block',
  }),
  r('wsb-006', {
    name: 'Pare-feu — Journalisation Domain activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=netsh advfirewall show domainprofile logging 2>&1; if($r -match 'LogDroppedConnections\s+Enable'){'PASS'}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'netsh advfirewall set domainprofile logging droppedconnections enable',
  }),
  r('wsb-007', {
    name: 'Pare-feu — Journalisation Private activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=netsh advfirewall show privateprofile logging 2>&1; if($r -match 'LogDroppedConnections\\s+Enable'){'PASS'}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'netsh advfirewall set privateprofile logging droppedconnections enable',
  }),
  r('wsb-008', {
    name: 'Pare-feu — Journalisation Public activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=netsh advfirewall show publicprofile logging 2>&1; if($r -match 'LogDroppedConnections\\s+Enable'){'PASS'}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'netsh advfirewall set publicprofile logging droppedconnections enable',
  }),
  r('wsb-009', {
    name: 'Pare-feu — Taille log Domain ≥ 16384 Ko',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=netsh advfirewall show domainprofile logging 2>&1; if($r -match 'MaxFileSize\\s+(\\d+)'){$v=[int]$Matches[1]; if($v -ge 16384){'PASS'}else{'FAIL'}}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'netsh advfirewall set domainprofile logging maxfilesize 16384',
  }),
  r('wsb-010', {
    name: 'Pare-feu — Taille log Public ≥ 16384 Ko',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=netsh advfirewall show publicprofile logging 2>&1; if($r -match 'MaxFileSize\\s+(\\d+)'){$v=[int]$Matches[1]; if($v -ge 16384){'PASS'}else{'FAIL'}}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'netsh advfirewall set publicprofile logging maxfilesize 16384',
  }),

  // ─── ANTIVIRUS / DEFENDER (15) ──────────────────────────────────────────────

  r('wsb-011', {
    name: 'Defender — Protection en temps réel activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableRealtimeMonitoring -EA SilentlyContinue).DisableRealtimeMonitoring -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-MpPreference -DisableRealtimeMonitoring $false',
  }),
  r('wsb-012', {
    name: 'Defender — Protection cloud activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SpynetReporting -EA 0).SpynetReporting; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -MAPSReporting Advanced',
  }),
  r('wsb-013', {
    name: 'Defender — Surveillance comportementale activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableBehaviorMonitoring -EA SilentlyContinue).DisableBehaviorMonitoring -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableBehaviorMonitoring $false',
  }),
  r('wsb-014', {
    name: 'Defender — Protection IOAV activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableIOAVProtection -EA SilentlyContinue).DisableIOAVProtection -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableIOAVProtection $false',
  }),
  r('wsb-015', {
    name: 'Defender — Protection réseau activée',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Network Protection|EnableNetworkProtection',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -EnableNetworkProtection Enabled',
  }),
  r('wsb-016', {
    name: 'Defender — Tamper Protection activée',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender|TamperProtection',
    expected: '4',
    operator: 'gt',
    severity: 'critical',
  }),
  r('wsb-017', {
    name: 'Defender — Signatures à jour (≤ 7 jours)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `try{$d=Get-MpComputerStatus -EA Stop; if($d.AntivirusSignatureLastUpdated -and ((Get-Date)-$d.AntivirusSignatureLastUpdated).TotalDays -le 7){'PASS'}else{'FAIL'}}catch{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-018', {
    name: 'Defender — Protection PUA activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender' -Name PUAProtection -EA 0).PUAProtection; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -PUAProtection Enabled',
  }),
  r('wsb-019', {
    name: 'Defender — Analyse des scripts activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableScriptScanning -EA SilentlyContinue).DisableScriptScanning -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -DisableScriptScanning $false',
  }),
  r('wsb-020', {
    name: 'Defender — Accès contrôlé aux dossiers activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Controlled Folder Access' -Name EnableControlledFolderAccess -EA 0).EnableControlledFolderAccess; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-MpPreference -EnableControlledFolderAccess Enabled',
  }),
  r('wsb-021', {
    name: 'Defender — Règles ASR activées',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR' -Name ExploitGuard_ASR_Rules -EA 0).ExploitGuard_ASR_Rules; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR' -Name ExploitGuard_ASR_Rules -Value 1 -Type DWord`,
  }),
  r('wsb-022', {
    name: 'Defender — Rapport MAPS activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SpynetReporting -EA 0).SpynetReporting; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -MAPSReporting Advanced',
  }),
  r('wsb-023', {
    name: 'Defender — Soumission d\'échantillons automatique',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SubmitSamplesConsent -EA 0).SubmitSamplesConsent; if($v -eq $null -or $v -eq 1 -or $v -eq 3){'PASS'}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Set-MpPreference -SubmitSamplesConsent SendAllSamples',
  }),
  r('wsb-024', {
    name: 'Defender — Analyse complète planifiée activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).ScanScheduleDay',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'Set-MpPreference -ScanScheduleDay 1',
  }),
  r('wsb-025', {
    name: 'Defender — Désactivation par stratégie absente',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender|DisableAntiSpyware',
    expected: '1',
    operator: 'neq',
    severity: 'critical',
    remediationScript: `Remove-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender' -Name DisableAntiSpyware -EA SilentlyContinue`,
  }),

  // ─── ACCOUNTS (10) ──────────────────────────────────────────────────────────

  r('wsb-026', {
    name: 'Comptes — Compte Invité désactivé',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$u=Get-LocalUser -ErrorAction SilentlyContinue|Where-Object{$_.SID -like "S-1-5-*-501"}; if($u -and !$u.Enabled){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Get-LocalUser | Where-Object{$_.SID -like "S-1-5-*-501"} | Disable-LocalUser',
  }),
  r('wsb-027', {
    name: 'Comptes — Compte Administrateur intégré désactivé',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$u=Get-LocalUser -ErrorAction SilentlyContinue|Where-Object{$_.SID -like "S-1-5-*-500"}; if($u -and !$u.Enabled){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Get-LocalUser | Where-Object{$_.SID -like "S-1-5-*-500"} | Disable-LocalUser',
  }),
  r('wsb-028', {
    name: 'Comptes — Mots de passe vides interdits (hors console)',
    category: 'Accounts',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LimitBlankPasswordUse',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LimitBlankPasswordUse -Value 1 -Type DWord`,
  }),
  r('wsb-029', {
    name: 'Comptes — Seuil de verrouillage ≤ 10 tentatives',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "LockoutBadCount\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -gt 0 -and $v -le 10){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'net accounts /lockoutthreshold:5',
  }),
  r('wsb-030', {
    name: 'Comptes — Durée de verrouillage ≥ 15 minutes',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "LockoutDuration\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 15){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'net accounts /lockoutduration:15',
  }),
  r('wsb-031', {
    name: 'Comptes — Réinitialisation compteur ≥ 15 minutes',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "ResetLockoutCount\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 15){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'net accounts /lockoutwindow:15',
  }),
  r('wsb-032', {
    name: 'Comptes — Complexité du mot de passe activée',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=(Select-String "PasswordComplexity\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value; Remove-Item $f -Force -EA 0; $v',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: '$f="$env:TEMP\\secpol$(Get-Random).cfg"; secedit /export /cfg $f /quiet; (Get-Content $f) -replace "PasswordComplexity\\s*=\\s*\\d+","PasswordComplexity = 1" | Set-Content $f; secedit /configure /db "$env:TEMP\\secpol.sdb" /cfg $f /quiet; Remove-Item $f,"$env:TEMP\\secpol.sdb" -Force -EA 0',
  }),
  r('wsb-033', {
    name: 'Comptes — Longueur minimale du mot de passe ≥ 14',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MinimumPasswordLength\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 14){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'net accounts /minpwlen:14',
  }),
  r('wsb-034', {
    name: 'Comptes — Durée maximale du mot de passe ≤ 60 jours',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MaximumPasswordAge\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -gt 0 -and $v -le 60){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'net accounts /maxpwage:60',
  }),
  r('wsb-035', {
    name: 'Comptes — Durée minimale du mot de passe ≥ 1 jour',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MinimumPasswordAge\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 1){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'net accounts /minpwage:1',
  }),

  // ─── CREDENTIALS (8) ────────────────────────────────────────────────────────

  r('wsb-036', {
    name: 'Identifiants — WDigest désactivé',
    category: 'Credentials',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest" -Name UseLogonCredential -EA SilentlyContinue).UseLogonCredential -eq 1){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest' -Name UseLogonCredential -Value 0 -Type DWord`,
  }),
  r('wsb-037', {
    name: 'Identifiants — LSA RunAsPPL activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '0',
    operator: 'gt',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RunAsPPL -Value 1 -Type DWord`,
  }),
  r('wsb-038', {
    name: 'Identifiants — LAPS activé (BackupDirectory)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\LAPS|BackupDirectory',
    expected: '0',
    operator: 'gt',
    severity: 'high',
  }),
  r('wsb-039', {
    name: 'Identifiants — Credential Guard activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1607',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard' -Name EnableVirtualizationBasedSecurity -Value 1 -Type DWord`,
  }),
  r('wsb-040', {
    name: 'Identifiants — Audit LSA activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name AuditBaseObjects -Value 1 -Type DWord`,
  }),
  r('wsb-041', {
    name: 'Identifiants — Connexions en cache ≤ 4',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon|CachedLogonsCount',
    expected: '5',
    operator: 'lt',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon' -Name CachedLogonsCount -Value '4' -Type String`,
  }),
  r('wsb-042', {
    name: 'Identifiants — Hash LM non stocké',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|NoLMHash',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name NoLMHash -Value 1 -Type DWord`,
  }),
  r('wsb-043', {
    name: 'Identifiants — Niveau d\'authentification LAN ≥ NTLMv2 (5)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '4',
    operator: 'gt',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name LmCompatibilityLevel -Value 5 -Type DWord`,
  }),

  // ─── NETWORK (12) ───────────────────────────────────────────────────────────

  r('wsb-044', {
    name: 'Réseau — SMBv1 client désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-SmbClientConfiguration -ErrorAction SilentlyContinue).EnableSMB1Protocol){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-SmbClientConfiguration -EnableSMB1Protocol $false -Force',
  }),
  r('wsb-045', {
    name: 'Réseau — SMBv1 serveur désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-SmbServerConfiguration -ErrorAction SilentlyContinue).EnableSMB1Protocol){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Set-SmbServerConfiguration -EnableSMB1Protocol $false -Force',
  }),
  r('wsb-046', {
    name: 'Réseau — LLMNR désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient|EnableMulticast',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient' -Name EnableMulticast -Value 0 -Type DWord`,
  }),
  r('wsb-047', {
    name: 'Réseau — Routage source IPv4 désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters|DisableIPSourceRouting',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters' -Name DisableIPSourceRouting -Value 2 -Type DWord`,
  }),
  r('wsb-048', {
    name: 'Réseau — Routage source IPv6 désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters|DisableIPSourceRouting',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters' -Name DisableIPSourceRouting -Value 2 -Type DWord`,
  }),
  r('wsb-049', {
    name: 'Réseau — Redirections ICMP désactivées',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters|EnableICMPRedirect',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters' -Name EnableICMPRedirect -Value 0 -Type DWord`,
  }),
  r('wsb-050', {
    name: 'Réseau — Énumération anonyme SAM désactivée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymousSAM',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RestrictAnonymousSAM -Value 1 -Type DWord`,
  }),
  r('wsb-051', {
    name: 'Réseau — Accès anonyme aux partages désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymous',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name RestrictAnonymous -Value 1 -Type DWord`,
  }),
  r('wsb-052', {
    name: 'Réseau — Signature SMB client requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters|RequireSecuritySignature',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters' -Name RequireSecuritySignature -Value 1 -Type DWord`,
  }),
  r('wsb-053', {
    name: 'Réseau — Signature SMB serveur requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|RequireSecuritySignature',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters' -Name RequireSecuritySignature -Value 1 -Type DWord`,
  }),
  r('wsb-054', {
    name: 'Réseau — Sessions nulles désactivées',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|RestrictNullSessAccess',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters' -Name RestrictNullSessAccess -Value 1 -Type DWord`,
  }),
  r('wsb-055', {
    name: 'Réseau — WPAD désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Wpad|WpadOverride',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Wpad' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Wpad' -Name WpadOverride -Value 1 -Type DWord`,
  }),

  // ─── SERVICES (15) ──────────────────────────────────────────────────────────

  r('wsb-056', {
    name: 'Services — Base de registre distante désactivée',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'RemoteRegistry',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service RemoteRegistry -Force -EA SilentlyContinue; Set-Service RemoteRegistry -StartupType Disabled',
  }),
  r('wsb-057', {
    name: 'Services — Telnet désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'TlntSvr',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Stop-Service TlntSvr -Force -EA SilentlyContinue; Set-Service TlntSvr -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-058', {
    name: 'Services — Moniteur infrarouge désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'irmon',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service irmon -Force -EA SilentlyContinue; Set-Service irmon -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-059', {
    name: 'Services — Partage de connexion Internet désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'SharedAccess',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service SharedAccess -Force -EA SilentlyContinue; Set-Service SharedAccess -StartupType Disabled',
  }),
  r('wsb-060', {
    name: 'Services — Routage et accès distant désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'RemoteAccess',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service RemoteAccess -Force -EA SilentlyContinue; Set-Service RemoteAccess -StartupType Disabled',
  }),
  r('wsb-061', {
    name: 'Services — NetTcpPortSharing désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'NetTcpPortSharing',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service NetTcpPortSharing -Force -EA SilentlyContinue; Set-Service NetTcpPortSharing -StartupType Disabled',
  }),
  r('wsb-062', {
    name: 'Services — SSDP Discovery désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'SSDPSRV',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service SSDPSRV -Force -EA SilentlyContinue; Set-Service SSDPSRV -StartupType Disabled',
  }),
  r('wsb-063', {
    name: 'Services — Hôte de périphériques UPnP désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'upnphost',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service upnphost -Force -EA SilentlyContinue; Set-Service upnphost -StartupType Disabled',
  }),
  r('wsb-064', {
    name: 'Services — AllJoyn Router désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AJRouter',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service AJRouter -Force -EA SilentlyContinue; Set-Service AJRouter -StartupType Disabled',
  }),
  r('wsb-065', {
    name: 'Services — Service de télécopie désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Fax',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service Fax -Force -EA SilentlyContinue; Set-Service Fax -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-066', {
    name: 'Services — Connexion secondaire désactivée',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'seclogon',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service seclogon -Force -EA SilentlyContinue; Set-Service seclogon -StartupType Disabled',
  }),
  r('wsb-067', {
    name: 'Services — W3SVC (IIS) désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'W3SVC',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service W3SVC -Force -EA SilentlyContinue; Set-Service W3SVC -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-068', {
    name: 'Services — Xbox Live Networking désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'XboxNetApiSvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service XboxNetApiSvc -Force -EA SilentlyContinue; Set-Service XboxNetApiSvc -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-069', {
    name: 'Services — Bluetooth Support désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'bthserv',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service bthserv -Force -EA SilentlyContinue; Set-Service bthserv -StartupType Disabled',
  }),
  r('wsb-070', {
    name: 'Services — Peer Name Resolution Protocol désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'PNRPsvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service PNRPsvc -Force -EA SilentlyContinue; Set-Service PNRPsvc -StartupType Disabled',
  }),

  // ─── UPDATES (5) ────────────────────────────────────────────────────────────

  r('wsb-071', {
    name: 'Mises à jour — Windows Update non désactivé',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '1',
    operator: 'neq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoUpdate -Value 0 -Type DWord`,
  }),
  r('wsb-072', {
    name: 'Mises à jour — Mises à jour automatiques configurées',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '1',
    operator: 'gt',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name AUOptions -Value 4 -Type DWord`,
  }),
  r('wsb-073', {
    name: 'Mises à jour — Service Windows Update actif',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$s=Get-Service wuauserv -EA SilentlyContinue; if($s -and $s.StartType -ne "Disabled"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-Service wuauserv -StartupType Manual; Start-Service wuauserv',
  }),
  r('wsb-074', {
    name: 'Mises à jour — Service Windows Defender Update actif',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service WdNisSvc -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'Set-Service WdNisSvc -StartupType Manual; Start-Service WdNisSvc -EA SilentlyContinue',
  }),
  r('wsb-075', {
    name: 'Mises à jour — Builds preview désactivées',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate|ManagePreviewBuilds',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate' -Name ManagePreviewBuilds -Value 1 -Type DWord`,
  }),

  // ─── REMOTE ACCESS (8) ──────────────────────────────────────────────────────

  r('wsb-076', {
    name: 'Accès distant — NLA requis pour RDP',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name UserAuthentication -Value 1 -Type DWord`,
  }),
  r('wsb-077', {
    name: 'Accès distant — Timeout session RDP ≤ 15 min',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MaxIdleTime',
    expected: '900001',
    operator: 'lt',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MaxIdleTime -Value 900000 -Type DWord`,
  }),
  r('wsb-078', {
    name: 'Accès distant — Chiffrement RDP niveau High',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MinEncryptionLevel',
    expected: '3',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name MinEncryptionLevel -Value 3 -Type DWord`,
  }),
  r('wsb-079', {
    name: 'Accès distant — Assistance à distance désactivée',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|fAllowToGetHelp',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name fAllowToGetHelp -Value 0 -Type DWord`,
  }),
  r('wsb-080', {
    name: 'Accès distant — Offre d\'assistance à distance désactivée',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|fAllowUnsolicited',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name fAllowUnsolicited -Value 0 -Type DWord`,
  }),
  r('wsb-081', {
    name: 'Accès distant — Trafic WinRM non chiffré interdit (client)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowUnencryptedTraffic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client' -Name AllowUnencryptedTraffic -Value 0 -Type DWord`,
  }),
  r('wsb-082', {
    name: 'Accès distant — Trafic WinRM non chiffré interdit (service)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|AllowUnencryptedTraffic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service' -Name AllowUnencryptedTraffic -Value 0 -Type DWord`,
  }),
  r('wsb-083', {
    name: 'Accès distant — Couche sécurité RDP = TLS (2)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services' -Name SecurityLayer -Value 2 -Type DWord`,
  }),

  // ─── AUDIT (10) ─────────────────────────────────────────────────────────────

  r('wsb-084', {
    name: 'Audit — Événements d\'ouverture de session (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec|Erfolg und Fehler'){'Success and Failure'}else{''}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9215-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-085', {
    name: 'Audit — Gestion des comptes (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec|Erfolg und Fehler'){'Success and Failure'}else{''}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9235-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-086', {
    name: 'Audit — Changement de stratégie (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec|Erfolg und Fehler'){'Success and Failure'}else{''}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922F-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-087', {
    name: 'Audit — Utilisation de privilèges sensibles (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec|Erfolg und Fehler'){'Success and Failure'}else{''}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9228-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-088', {
    name: 'Audit — Événements système (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE9210-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec|Erfolg und Fehler'){'Success and Failure'}else{''}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9210-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-089', {
    name: 'Audit — Journalisation ScriptBlock PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging' -Name EnableScriptBlockLogging -Value 1 -Type DWord`,
  }),
  r('wsb-090', {
    name: 'Audit — Transcription PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription|EnableTranscripting',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription' -Name EnableTranscripting -Value 1 -Type DWord`,
  }),
  r('wsb-091', {
    name: 'Audit — Journalisation de modules PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging|EnableModuleLogging',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging' -Name EnableModuleLogging -Value 1 -Type DWord`,
  }),
  r('wsb-092', {
    name: 'Audit — Taille journal Sécurité ≥ 196608 Ko',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes / 1KB',
    expected: '196607',
    operator: 'gt',
    severity: 'moderate',
    remediationScript: 'wevtutil sl Security /ms:201326592',
  }),
  r('wsb-093', {
    name: 'Audit — Ligne de commande dans les événements de création de processus',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit|ProcessCreationIncludeCmdLine_Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit' -Name ProcessCreationIncludeCmdLine_Enabled -Value 1 -Type DWord`,
  }),

  // ─── ENCRYPTION (8) ─────────────────────────────────────────────────────────

  r('wsb-094', {
    name: 'Chiffrement — BitLocker activé sur le lecteur OS',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
    remediationScript: 'Enable-BitLocker -MountPoint $env:SystemDrive -EncryptionMethod XtsAes256 -RecoveryPasswordProtector -SkipHardwareTest',
  }),
  r('wsb-095', {
    name: 'Chiffrement — TLS 1.0 client désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-096', {
    name: 'Chiffrement — TLS 1.0 serveur désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-097', {
    name: 'Chiffrement — TLS 1.1 client désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-098', {
    name: 'Chiffrement — TLS 1.1 serveur désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-099', {
    name: 'Chiffrement — SSL 3.0 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-100', {
    name: 'Chiffrement — RC4 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128' -Name Enabled -Value 0 -Type DWord`,
  }),
  r('wsb-101', {
    name: 'Chiffrement — Secure Boot activé',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'Confirm-SecureBootUEFI',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1507',
  }),

  // ─── SYSTEM (15) ────────────────────────────────────────────────────────────

  r('wsb-102', {
    name: 'Système — UAC activé (EnableLUA)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name EnableLUA -Value 1 -Type DWord`,
  }),
  r('wsb-103', {
    name: 'Système — UAC élévation admin = consentement (2)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '1',
    operator: 'gt',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name ConsentPromptBehaviorAdmin -Value 2 -Type DWord`,
  }),
  r('wsb-104', {
    name: 'Système — Exécution automatique des médias désactivée',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoDriveTypeAutoRun -Value 255 -Type DWord`,
  }),
  r('wsb-105', {
    name: 'Système — AutoRun désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoAutorun',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer' -Name NoAutorun -Value 1 -Type DWord`,
  }),
  r('wsb-106', {
    name: 'Système — Ctrl+Alt+Suppr requis à la connexion',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|DisableCAD',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name DisableCAD -Value 0 -Type DWord`,
  }),
  r('wsb-107', {
    name: 'Système — Dernier utilisateur non affiché',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|DontDisplayLastUserName',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name DontDisplayLastUserName -Value 1 -Type DWord`,
  }),
  r('wsb-108', {
    name: 'Système — Message légal à la connexion configuré',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('wsb-109', {
    name: 'Système — Économiseur avec mot de passe activé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' -Force | Out-Null; Set-ItemProperty -Path 'HKCU:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop' -Name ScreenSaverIsSecure -Value '1' -Type String`,
  }),
  r('wsb-110', {
    name: 'Système — Windows Script Host désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings' -Name Enabled -Value 0 -Type DWord`,
  }),
  r('wsb-111', {
    name: 'Système — Mode SafeDLL Search activé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager|SafeDllSearchMode',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager' -Name SafeDllSearchMode -Value 1 -Type DWord`,
  }),
  r('wsb-112', {
    name: 'Système — Protection des objets internes du système',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager|ProtectionMode',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager' -Name ProtectionMode -Value 1 -Type DWord`,
  }),
  r('wsb-113', {
    name: 'Système — AutoAdminLogon désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon|AutoAdminLogon',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon' -Name AutoAdminLogon -Value '0' -Type String`,
  }),
  r('wsb-114', {
    name: 'Système — SEHOP activé (ExceptionChainValidation)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel|DisableExceptionChainValidation',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel' -Name DisableExceptionChainValidation -Value 0 -Type DWord`,
  }),
  r('wsb-115', {
    name: 'Système — Stratégie chargement driver au démarrage = Bon+Inconnu',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Policies\\EarlyLaunch|DriverLoadPolicy',
    expected: '3',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 8',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Policies\\EarlyLaunch' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Policies\\EarlyLaunch' -Name DriverLoadPolicy -Value 3 -Type DWord`,
  }),
  r('wsb-116', {
    name: 'Système — UAC bureau sécurisé pour élévation',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|PromptOnSecureDesktop',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name PromptOnSecureDesktop -Value 1 -Type DWord`,
  }),

  // ─── ADDITIONAL RULES to reach 120+ ─────────────────────────────────────────

  r('wsb-117', {
    name: 'Réseau — Découverte LLTD désactivée',
    category: 'Network',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'lltdsvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service lltdsvc -Force -EA SilentlyContinue; Set-Service lltdsvc -StartupType Disabled -EA SilentlyContinue',
  }),
  r('wsb-118', {
    name: 'Réseau — Accès anonyme aux pipes nommés interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|NullSessionPipes',
    expected: '',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters' -Name NullSessionPipes -Value @() -Type MultiString`,
  }),
  r('wsb-119', {
    name: 'Réseau — Accès anonyme aux partages interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|NullSessionShares',
    expected: '',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters' -Name NullSessionShares -Value @() -Type MultiString`,
  }),
  r('wsb-120', {
    name: 'Réseau — Appels RPC distants à SAM restreints',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictRemoteSAM',
    expected: '',
    operator: 'exists',
    severity: 'high',
    minOsVersion: 'Windows 10 1607',
  }),
  r('wsb-121', {
    name: 'Chiffrement — SSL 2.0 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server' -Name Enabled -Value 0 -Type DWord; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server' -Name DisabledByDefault -Value 1 -Type DWord`,
  }),
  r('wsb-122', {
    name: 'Système — Politiques d\'audit forcées (sous-catégories)',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|SCENoApplyLegacyAuditPolicy',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa' -Name SCENoApplyLegacyAuditPolicy -Value 1 -Type DWord`,
  }),
  r('wsb-123', {
    name: 'Réseau — Minimum sécurité session NTLM client = 537395200',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if(((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0" -Name NTLMMinClientSec -EA 0).NTLMMinClientSec -band 536870912) -eq 536870912){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0' -Name NTLMMinClientSec -Value 537395200 -Type DWord`,
  }),
  r('wsb-124', {
    name: 'Réseau — Minimum sécurité session NTLM serveur = 537395200',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if(((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0" -Name NTLMMinServerSec -EA 0).NTLMMinServerSec -band 536870912) -eq 536870912){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0' -Name NTLMMinServerSec -Value 537395200 -Type DWord`,
  }),
  r('wsb-125', {
    name: 'Accès distant — WinRM Basic auth client désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowBasic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client' -Name AllowBasic -Value 0 -Type DWord`,
  }),
  r('wsb-126', {
    name: 'Accès distant — WinRM Basic auth service désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|AllowBasic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service' -Name AllowBasic -Value 0 -Type DWord`,
  }),
  r('wsb-127', {
    name: 'Accès distant — WinRM Digest auth désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowDigest',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client' -Name AllowDigest -Value 0 -Type DWord`,
  }),
  r('wsb-128', {
    name: 'Accès distant — WinRM RunAs credentials non stockés',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|DisableRunAs',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service' -Name DisableRunAs -Value 1 -Type DWord`,
  }),
  r('wsb-129', {
    name: 'Système — OneDrive désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive|DisableFileSyncNGSC',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive' -Name DisableFileSyncNGSC -Value 1 -Type DWord`,
  }),
  r('wsb-130', {
    name: 'Système — Téléchargement pilotes d\'impression par utilisateurs interdit',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Print\\Providers\\LanMan Print Services\\Servers|AddPrinterDrivers',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Print\\Providers\\LanMan Print Services\\Servers' -Name AddPrinterDrivers -Value 1 -Type DWord`,
  }),
  r('wsb-131', {
    name: 'Réseau — Canal sécurisé Netlogon chiffré et signé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters|RequireSignOrSeal',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters' -Name RequireSignOrSeal -Value 1 -Type DWord`,
  }),
  r('wsb-132', {
    name: 'Réseau — Clé de session Netlogon renforcée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters|RequireStrongKey',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters' -Name RequireStrongKey -Value 1 -Type DWord`,
  }),
  r('wsb-133', {
    name: 'Réseau — Signature LDAP client requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LDAP|LDAPClientIntegrity',
    expected: '0',
    operator: 'gt',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\LDAP' -Name LDAPClientIntegrity -Value 1 -Type DWord`,
  }),
  r('wsb-134', {
    name: 'Système — Rapport d\'erreurs Windows désactivé',
    category: 'System',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WerSvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
    remediationScript: 'Stop-Service WerSvc -Force -EA SilentlyContinue; Set-Service WerSvc -StartupType Disabled',
  }),
  r('wsb-135', {
    name: 'Audit — Validation d\'identifiants (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE923F-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec'){'Success and Failure'}elseif($r -match 'Success|succ.s'){'Success'}elseif($r -match 'Failure|.chec'){'Failure'}else{'No Auditing'}`,
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE923F-69AE-11D9-BED3-505054503030}" /success:enable /failure:enable',
  }),
  r('wsb-136', {
    name: 'Audit — Création de processus (succès)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec'){'Success and Failure'}elseif($r -match 'Success|succ.s'){'Success'}elseif($r -match 'Failure|.chec'){'Failure'}else{'No Auditing'}`,
    expected: 'No Auditing',
    operator: 'neq',
    severity: 'moderate',
    remediationScript: 'auditpol /set /subcategory:"{0CCE922B-69AE-11D9-BED3-505054503030}" /success:enable',
  }),
  r('wsb-137', {
    name: 'Audit — Verrouillage de compte (échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$r=auditpol /get /subcategory:"{0CCE9217-69AE-11D9-BED3-505054503030}" 2>&1; if($r -match 'Success and Failure|succ.s et .chec'){'Success and Failure'}elseif($r -match 'Success|succ.s'){'Success'}elseif($r -match 'Failure|.chec'){'Failure'}else{'No Auditing'}`,
    expected: 'No Auditing',
    operator: 'neq',
    severity: 'high',
    remediationScript: 'auditpol /set /subcategory:"{0CCE9217-69AE-11D9-BED3-505054503030}" /failure:enable',
  }),
  r('wsb-138', {
    name: 'Réseau — Authentification PKU2U désactivée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\pku2u|AllowOnlineID',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\pku2u' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\pku2u' -Name AllowOnlineID -Value 0 -Type DWord`,
  }),
  r('wsb-139', {
    name: 'Système — Accès restreint aux chemins UNC (SYSVOL)',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths|\\\\*\\SYSVOL',
    expected: '',
    operator: 'exists',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths' -Name '\\\\*\\SYSVOL' -Value 'RequireMutualAuthentication=1,RequireIntegrity=1' -Type String`,
  }),
  r('wsb-140', {
    name: 'Système — Accès restreint aux chemins UNC (NETLOGON)',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths|\\\\*\\NETLOGON',
    expected: '',
    operator: 'exists',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths' -Name '\\\\*\\NETLOGON' -Value 'RequireMutualAuthentication=1,RequireIntegrity=1' -Type String`,
  }),
  r('wsb-141', {
    name: 'Système — SmartScreen activé (Explorateur)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System' -Name EnableSmartScreen -Value 1 -Type DWord`,
  }),
  r('wsb-142', {
    name: 'Système — Délégation non exportable des identifiants (CredSSP)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CredentialsDelegation|AllowProtectedCreds',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1703',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CredentialsDelegation' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\CredentialsDelegation' -Name AllowProtectedCreds -Value 1 -Type DWord`,
  }),
  r('wsb-143', {
    name: 'Système — Oracle de chiffrement CredSSP = Forcer mise à jour (0)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\CredSSP\\Parameters|AllowEncryptionOracle',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\CredSSP\\Parameters' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\CredSSP\\Parameters' -Name AllowEncryptionOracle -Value 0 -Type DWord`,
  }),
  r('wsb-144', {
    name: 'Système — Télémétrie Windows = Désactivée ou Sécurité (0)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|AllowTelemetry',
    expected: '1',
    operator: 'lt',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection' -Name AllowTelemetry -Value 0 -Type DWord`,
  }),
  r('wsb-145', {
    name: 'Système — Compte Administrateur intégré en mode approbation Admin',
    category: 'Accounts',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|FilterAdministratorToken',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System' -Name FilterAdministratorToken -Value 1 -Type DWord`,
  }),
  r('wsb-146', {
    name: 'Services — Spouleur d\'impression désactivé (si non requis)',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Spooler',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service Spooler -Force -EA SilentlyContinue; Set-Service Spooler -StartupType Disabled',
  }),
  r('wsb-147', {
    name: 'Réseau — Passerelle par défaut SSDP Discovery sans service actif',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'upnphost',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service upnphost -Force -EA SilentlyContinue; Set-Service upnphost -StartupType Disabled',
  }),
  r('wsb-148', {
    name: 'Mises à jour — Redémarrage automatique sans utilisateur connecté',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoRebootWithLoggedOnUsers',
    expected: '1',
    operator: 'neq',
    severity: 'low',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU' -Name NoAutoRebootWithLoggedOnUsers -Value 0 -Type DWord`,
  }),
  r('wsb-149', {
    name: 'Système — Pont réseau interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections|NC_AllowNetBridge_NLA',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `New-Item -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections' -Force | Out-Null; Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections' -Name NC_AllowNetBridge_NLA -Value 0 -Type DWord`,
  }),
  r('wsb-150', {
    name: 'Système — Partage de connexion Internet via interface interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections|NC_ShowSharedAccessUI',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: `Set-ItemProperty -Path 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections' -Name NC_ShowSharedAccessUI -Value 0 -Type DWord`,
  }),
];
