import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const windowsBaselineRules: ComplianceRule[] = [

  // ─── FIREWALL (10) ──────────────────────────────────────────────────────────

  r('wsb-001', {
    name: 'Pare-feu — Profil Domain activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-002', {
    name: 'Pare-feu — Profil Private activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-003', {
    name: 'Pare-feu — Profil Public activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).Enabled',
    expected: 'True',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-004', {
    name: 'Pare-feu — Trafic entrant Domain bloqué par défaut',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-NetFirewallProfile -Profile Domain).DefaultInboundAction -ne "Allow"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-005', {
    name: 'Pare-feu — Trafic entrant Public bloqué par défaut',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-NetFirewallProfile -Profile Public).DefaultInboundAction -ne "Allow"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-006', {
    name: 'Pare-feu — Journalisation Domain activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-007', {
    name: 'Pare-feu — Journalisation Private activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Private).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-008', {
    name: 'Pare-feu — Journalisation Public activée (paquets rejetés)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).LogBlocked',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-009', {
    name: 'Pare-feu — Taille log Domain ≥ 16384 Ko',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Domain).LogMaxSizeKilobytes',
    expected: '16383',
    operator: 'gt',
    severity: 'low',
  }),
  r('wsb-010', {
    name: 'Pare-feu — Taille log Public ≥ 16384 Ko',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-NetFirewallProfile -Profile Public).LogMaxSizeKilobytes',
    expected: '16383',
    operator: 'gt',
    severity: 'low',
  }),

  // ─── ANTIVIRUS / DEFENDER (15) ──────────────────────────────────────────────

  r('wsb-011', {
    name: 'Defender — Protection en temps réel activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableRealtimeMonitoring -EA SilentlyContinue).DisableRealtimeMonitoring -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-012', {
    name: 'Defender — Protection cloud activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SpynetReporting -EA 0).SpynetReporting; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-013', {
    name: 'Defender — Surveillance comportementale activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableBehaviorMonitoring -EA SilentlyContinue).DisableBehaviorMonitoring -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-014', {
    name: 'Defender — Protection IOAV activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableIOAVProtection -EA SilentlyContinue).DisableIOAVProtection -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-015', {
    name: 'Defender — Protection réseau activée',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Network Protection|EnableNetworkProtection',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-016', {
    name: 'Defender — Tamper Protection activée',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Defender|TamperProtection',
    expected: '4',
    operator: 'gt',
    severity: 'critical',
  }),
  r('wsb-017', {
    name: 'Defender — Signatures à jour (≤ 7 jours)',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$s=(Get-MpComputerStatus -ErrorAction SilentlyContinue).AntivirusSignatureLastUpdated; if($s -and ((Get-Date)-$s).TotalDays -le 7){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-018', {
    name: 'Defender — Protection PUA activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender' -Name PUAProtection -EA 0).PUAProtection; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-019', {
    name: 'Defender — Analyse des scripts activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Real-Time Protection" -Name DisableScriptScanning -EA SilentlyContinue).DisableScriptScanning -eq 1){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-020', {
    name: 'Defender — Accès contrôlé aux dossiers activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\Controlled Folder Access' -Name EnableControlledFolderAccess -EA 0).EnableControlledFolderAccess; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-021', {
    name: 'Defender — Règles ASR activées',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows Defender\\Windows Defender Exploit Guard\\ASR' -Name ExploitGuard_ASR_Rules -EA 0).ExploitGuard_ASR_Rules; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-022', {
    name: 'Defender — Rapport MAPS activé',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SpynetReporting -EA 0).SpynetReporting; if($v -eq 0){'FAIL'}else{'PASS'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-023', {
    name: 'Defender — Soumission d\'échantillons automatique',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `$v=(Get-ItemProperty 'HKLM:\\SOFTWARE\\Microsoft\\Windows Defender\\Spynet' -Name SubmitSamplesConsent -EA 0).SubmitSamplesConsent; if($v -eq $null -or $v -eq 1 -or $v -eq 3){'PASS'}else{'FAIL'}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-024', {
    name: 'Defender — Analyse complète planifiée activée',
    category: 'Firewall',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-MpPreference).ScanScheduleDay',
    expected: '0',
    operator: 'neq',
    severity: 'moderate',
  }),
  r('wsb-025', {
    name: 'Defender — Désactivation par stratégie absente',
    category: 'Firewall',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows Defender|DisableAntiSpyware',
    expected: '1',
    operator: 'neq',
    severity: 'critical',
  }),

  // ─── ACCOUNTS (10) ──────────────────────────────────────────────────────────

  r('wsb-026', {
    name: 'Comptes — Compte Invité désactivé',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$u=Get-LocalUser -ErrorAction SilentlyContinue|Where-Object{$_.SID -like "S-1-5-*-501"}; if($u -and !$u.Enabled){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-027', {
    name: 'Comptes — Compte Administrateur intégré désactivé',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$u=Get-LocalUser -ErrorAction SilentlyContinue|Where-Object{$_.SID -like "S-1-5-*-500"}; if($u -and !$u.Enabled){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-028', {
    name: 'Comptes — Mots de passe vides interdits (hors console)',
    category: 'Accounts',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LimitBlankPasswordUse',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-029', {
    name: 'Comptes — Seuil de verrouillage ≤ 10 tentatives',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "LockoutBadCount\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -gt 0 -and $v -le 10){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-030', {
    name: 'Comptes — Durée de verrouillage ≥ 15 minutes',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "LockoutDuration\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 15){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-031', {
    name: 'Comptes — Réinitialisation compteur ≥ 15 minutes',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "ResetLockoutCount\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 15){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-032', {
    name: 'Comptes — Complexité du mot de passe activée',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=(Select-String "PasswordComplexity\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value; Remove-Item $f -Force -EA 0; $v',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-033', {
    name: 'Comptes — Longueur minimale du mot de passe ≥ 14',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MinimumPasswordLength\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 14){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-034', {
    name: 'Comptes — Durée maximale du mot de passe ≤ 60 jours',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MaximumPasswordAge\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -gt 0 -and $v -le 60){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-035', {
    name: 'Comptes — Durée minimale du mot de passe ≥ 1 jour',
    category: 'Accounts',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$f="$env:TEMP\\sb$(Get-Random).cfg"; secedit /export /cfg $f /quiet; $v=[int]((Select-String "MinimumPasswordAge\\s*=\\s*(\\d+)" $f -EA 0).Matches[0].Groups[1].Value); Remove-Item $f -Force -EA 0; if($v -ge 1){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ─── CREDENTIALS (8) ────────────────────────────────────────────────────────

  r('wsb-036', {
    name: 'Identifiants — WDigest désactivé',
    category: 'Credentials',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\WDigest" -Name UseLogonCredential -EA SilentlyContinue).UseLogonCredential -eq 1){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-037', {
    name: 'Identifiants — LSA RunAsPPL activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RunAsPPL',
    expected: '0',
    operator: 'gt',
    severity: 'critical',
  }),
  r('wsb-038', {
    name: 'Identifiants — LAPS activé (BackupDirectory)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\LAPS|BackupDirectory',
    expected: '0',
    operator: 'gt',
    severity: 'high',
  }),
  r('wsb-039', {
    name: 'Identifiants — Credential Guard activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\DeviceGuard|EnableVirtualizationBasedSecurity',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1607',
  }),
  r('wsb-040', {
    name: 'Identifiants — Audit LSA activé',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|AuditBaseObjects',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-041', {
    name: 'Identifiants — Connexions en cache ≤ 4',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon|CachedLogonsCount',
    expected: '5',
    operator: 'lt',
    severity: 'high',
  }),
  r('wsb-042', {
    name: 'Identifiants — Hash LM non stocké',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|NoLMHash',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-043', {
    name: 'Identifiants — Niveau d\'authentification LAN ≥ NTLMv2 (5)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|LmCompatibilityLevel',
    expected: '4',
    operator: 'gt',
    severity: 'critical',
  }),

  // ─── NETWORK (12) ───────────────────────────────────────────────────────────

  r('wsb-044', {
    name: 'Réseau — SMBv1 client désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-SmbClientConfiguration -ErrorAction SilentlyContinue).EnableSMB1Protocol){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-045', {
    name: 'Réseau — SMBv1 serveur désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: `if((Get-SmbServerConfiguration -ErrorAction SilentlyContinue).EnableSMB1Protocol){"FAIL"}else{"PASS"}`,
    expected: 'PASS',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-046', {
    name: 'Réseau — LLMNR désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\DNSClient|EnableMulticast',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-047', {
    name: 'Réseau — Routage source IPv4 désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters|DisableIPSourceRouting',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-048', {
    name: 'Réseau — Routage source IPv6 désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip6\\Parameters|DisableIPSourceRouting',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-049', {
    name: 'Réseau — Redirections ICMP désactivées',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters|EnableICMPRedirect',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-050', {
    name: 'Réseau — Énumération anonyme SAM désactivée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymousSAM',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-051', {
    name: 'Réseau — Accès anonyme aux partages désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictAnonymous',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-052', {
    name: 'Réseau — Signature SMB client requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters|RequireSecuritySignature',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-053', {
    name: 'Réseau — Signature SMB serveur requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|RequireSecuritySignature',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-054', {
    name: 'Réseau — Sessions nulles désactivées',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|RestrictNullSessAccess',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-055', {
    name: 'Réseau — WPAD désactivé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\Wpad|WpadOverride',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ─── SERVICES (15) ──────────────────────────────────────────────────────────

  r('wsb-056', {
    name: 'Services — Base de registre distante désactivée',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'RemoteRegistry',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-057', {
    name: 'Services — Telnet désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'TlntSvr',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-058', {
    name: 'Services — Moniteur infrarouge désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'irmon',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-059', {
    name: 'Services — Partage de connexion Internet désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'SharedAccess',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-060', {
    name: 'Services — Routage et accès distant désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'RemoteAccess',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-061', {
    name: 'Services — NetTcpPortSharing désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'NetTcpPortSharing',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-062', {
    name: 'Services — SSDP Discovery désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'SSDPSRV',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-063', {
    name: 'Services — Hôte de périphériques UPnP désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'upnphost',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-064', {
    name: 'Services — AllJoyn Router désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'AJRouter',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-065', {
    name: 'Services — Service de télécopie désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Fax',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-066', {
    name: 'Services — Connexion secondaire désactivée',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'seclogon',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-067', {
    name: 'Services — W3SVC (IIS) désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'W3SVC',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-068', {
    name: 'Services — Xbox Live Networking désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'XboxNetApiSvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-069', {
    name: 'Services — Bluetooth Support désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'bthserv',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-070', {
    name: 'Services — Peer Name Resolution Protocol désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'PNRPsvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),

  // ─── UPDATES (5) ────────────────────────────────────────────────────────────

  r('wsb-071', {
    name: 'Mises à jour — Windows Update non désactivé',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoUpdate',
    expected: '1',
    operator: 'neq',
    severity: 'critical',
  }),
  r('wsb-072', {
    name: 'Mises à jour — Mises à jour automatiques configurées',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|AUOptions',
    expected: '1',
    operator: 'gt',
    severity: 'high',
  }),
  r('wsb-073', {
    name: 'Mises à jour — Service Windows Update actif',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service wuauserv -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
  }),
  r('wsb-074', {
    name: 'Mises à jour — Service Windows Defender Update actif',
    category: 'Updates',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-Service WdNisSvc -ErrorAction SilentlyContinue).StartType',
    expected: 'Disabled',
    operator: 'neq',
    severity: 'high',
  }),
  r('wsb-075', {
    name: 'Mises à jour — Builds preview désactivées',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate|ManagePreviewBuilds',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ─── REMOTE ACCESS (8) ──────────────────────────────────────────────────────

  r('wsb-076', {
    name: 'Accès distant — NLA requis pour RDP',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|UserAuthentication',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-077', {
    name: 'Accès distant — Timeout session RDP ≤ 15 min',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MaxIdleTime',
    expected: '900001',
    operator: 'lt',
    severity: 'high',
  }),
  r('wsb-078', {
    name: 'Accès distant — Chiffrement RDP niveau High',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|MinEncryptionLevel',
    expected: '3',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-079', {
    name: 'Accès distant — Assistance à distance désactivée',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|fAllowToGetHelp',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-080', {
    name: 'Accès distant — Offre d\'assistance à distance désactivée',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|fAllowUnsolicited',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-081', {
    name: 'Accès distant — Trafic WinRM non chiffré interdit (client)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowUnencryptedTraffic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-082', {
    name: 'Accès distant — Trafic WinRM non chiffré interdit (service)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|AllowUnencryptedTraffic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-083', {
    name: 'Accès distant — Couche sécurité RDP = TLS (2)',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services|SecurityLayer',
    expected: '2',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── AUDIT (10) ─────────────────────────────────────────────────────────────

  r('wsb-084', {
    name: 'Audit — Événements d\'ouverture de session (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Logon" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-085', {
    name: 'Audit — Gestion des comptes (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"User Account Management" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-086', {
    name: 'Audit — Changement de stratégie (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Audit Policy Change" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-087', {
    name: 'Audit — Utilisation de privilèges sensibles (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Sensitive Privilege Use" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-088', {
    name: 'Audit — Événements système (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Security System Extension" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-089', {
    name: 'Audit — Journalisation ScriptBlock PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ScriptBlockLogging|EnableScriptBlockLogging',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-090', {
    name: 'Audit — Transcription PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\Transcription|EnableTranscripting',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-091', {
    name: 'Audit — Journalisation de modules PowerShell activée',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\PowerShell\\ModuleLogging|EnableModuleLogging',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-092', {
    name: 'Audit — Taille journal Sécurité ≥ 196608 Ko',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WinEvent -ListLog Security).MaximumSizeInBytes / 1KB',
    expected: '196607',
    operator: 'gt',
    severity: 'moderate',
  }),
  r('wsb-093', {
    name: 'Audit — Ligne de commande dans les événements de création de processus',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Audit|ProcessCreationIncludeCmdLine_Enabled',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),

  // ─── ENCRYPTION (8) ─────────────────────────────────────────────────────────

  r('wsb-094', {
    name: 'Chiffrement — BitLocker activé sur le lecteur OS',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-BitLockerVolume -MountPoint $env:SystemDrive).ProtectionStatus',
    expected: 'On',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-095', {
    name: 'Chiffrement — TLS 1.0 client désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-096', {
    name: 'Chiffrement — TLS 1.0 serveur désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-097', {
    name: 'Chiffrement — TLS 1.1 client désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Client|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-098', {
    name: 'Chiffrement — TLS 1.1 serveur désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\TLS 1.1\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-099', {
    name: 'Chiffrement — SSL 3.0 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 3.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-100', {
    name: 'Chiffrement — RC4 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Ciphers\\RC4 128/128|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-101', {
    name: 'Chiffrement — Secure Boot activé',
    category: 'Encryption',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'Confirm-SecureBootUEFI',
    expected: 'True',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1507',
  }),

  // ─── SYSTEM (15) ────────────────────────────────────────────────────────────

  r('wsb-102', {
    name: 'Système — UAC activé (EnableLUA)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|EnableLUA',
    expected: '1',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-103', {
    name: 'Système — UAC élévation admin = consentement (2)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|ConsentPromptBehaviorAdmin',
    expected: '1',
    operator: 'gt',
    severity: 'high',
  }),
  r('wsb-104', {
    name: 'Système — Exécution automatique des médias désactivée',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoDriveTypeAutoRun',
    expected: '255',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-105', {
    name: 'Système — AutoRun désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer|NoAutorun',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-106', {
    name: 'Système — Ctrl+Alt+Suppr requis à la connexion',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|DisableCAD',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-107', {
    name: 'Système — Dernier utilisateur non affiché',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|DontDisplayLastUserName',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-108', {
    name: 'Système — Message légal à la connexion configuré',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|LegalNoticeCaption',
    expected: '',
    operator: 'exists',
    severity: 'low',
  }),
  r('wsb-109', {
    name: 'Système — Économiseur avec mot de passe activé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop|ScreenSaverIsSecure',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-110', {
    name: 'Système — Windows Script Host désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows Script Host\\Settings|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-111', {
    name: 'Système — Mode SafeDLL Search activé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager|SafeDllSearchMode',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-112', {
    name: 'Système — Protection des objets internes du système',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager|ProtectionMode',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-113', {
    name: 'Système — AutoAdminLogon désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon|AutoAdminLogon',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-114', {
    name: 'Système — SEHOP activé (ExceptionChainValidation)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\kernel|DisableExceptionChainValidation',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-115', {
    name: 'Système — Stratégie chargement driver au démarrage = Bon+Inconnu',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Policies\\EarlyLaunch|DriverLoadPolicy',
    expected: '3',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 8',
  }),
  r('wsb-116', {
    name: 'Système — UAC bureau sécurisé pour élévation',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|PromptOnSecureDesktop',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),

  // ─── ADDITIONAL RULES to reach 120+ ─────────────────────────────────────────

  r('wsb-117', {
    name: 'Réseau — Découverte LLTD désactivée',
    category: 'Network',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'lltdsvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-118', {
    name: 'Réseau — Accès anonyme aux pipes nommés interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|NullSessionPipes',
    expected: '',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-119', {
    name: 'Réseau — Accès anonyme aux partages interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LanManServer\\Parameters|NullSessionShares',
    expected: '',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-120', {
    name: 'Réseau — Appels RPC distants à SAM restreints',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|RestrictRemoteSAM',
    expected: '',
    operator: 'exists',
    severity: 'high',
    minOsVersion: 'Windows 10 1607',
  }),
  r('wsb-121', {
    name: 'Chiffrement — SSL 2.0 désactivé',
    category: 'Encryption',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SCHANNEL\\Protocols\\SSL 2.0\\Server|Enabled',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-122', {
    name: 'Système — Politiques d\'audit forcées (sous-catégories)',
    category: 'Audit',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa|SCENoApplyLegacyAuditPolicy',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-123', {
    name: 'Réseau — Minimum sécurité session NTLM client = 537395200',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if(((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0" -Name NTLMMinClientSec -EA 0).NTLMMinClientSec -band 536870912) -eq 536870912){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-124', {
    name: 'Réseau — Minimum sécurité session NTLM serveur = 537395200',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if(((Get-ItemProperty "HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\MSV1_0" -Name NTLMMinServerSec -EA 0).NTLMMinServerSec -band 536870912) -eq 536870912){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-125', {
    name: 'Accès distant — WinRM Basic auth client désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowBasic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-126', {
    name: 'Accès distant — WinRM Basic auth service désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|AllowBasic',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-127', {
    name: 'Accès distant — WinRM Digest auth désactivé',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Client|AllowDigest',
    expected: '0',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-128', {
    name: 'Accès distant — WinRM RunAs credentials non stockés',
    category: 'Remote Access',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WinRM\\Service|DisableRunAs',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-129', {
    name: 'Système — OneDrive désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\OneDrive|DisableFileSyncNGSC',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-130', {
    name: 'Système — Téléchargement pilotes d\'impression par utilisateurs interdit',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Print\\Providers\\LanMan Print Services\\Servers|AddPrinterDrivers',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-131', {
    name: 'Réseau — Canal sécurisé Netlogon chiffré et signé',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters|RequireSignOrSeal',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-132', {
    name: 'Réseau — Clé de session Netlogon renforcée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\Netlogon\\Parameters|RequireStrongKey',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-133', {
    name: 'Réseau — Signature LDAP client requise',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\LDAP|LDAPClientIntegrity',
    expected: '0',
    operator: 'gt',
    severity: 'high',
  }),
  r('wsb-134', {
    name: 'Système — Rapport d\'erreurs Windows désactivé',
    category: 'System',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WerSvc',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'low',
  }),
  r('wsb-135', {
    name: 'Audit — Validation d\'identifiants (succès+échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Credential Validation" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'Success and Failure',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-136', {
    name: 'Audit — Création de processus (succès)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Process Creation" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'No Auditing',
    operator: 'neq',
    severity: 'moderate',
  }),
  r('wsb-137', {
    name: 'Audit — Verrouillage de compte (échec)',
    category: 'Audit',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$r=(auditpol /get /subcategory:"Account Lockout" /r|ConvertFrom-Csv); ($r.PSObject.Properties)[4].Value',
    expected: 'No Auditing',
    operator: 'neq',
    severity: 'high',
  }),
  r('wsb-138', {
    name: 'Réseau — Authentification PKU2U désactivée',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\pku2u|AllowOnlineID',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-139', {
    name: 'Système — Accès restreint aux chemins UNC (SYSVOL)',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths|\\\\*\\SYSVOL',
    expected: '',
    operator: 'exists',
    severity: 'high',
  }),
  r('wsb-140', {
    name: 'Système — Accès restreint aux chemins UNC (NETLOGON)',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkProvider\\HardenedPaths|\\\\*\\NETLOGON',
    expected: '',
    operator: 'exists',
    severity: 'high',
  }),
  r('wsb-141', {
    name: 'Système — SmartScreen activé (Explorateur)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableSmartScreen',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-142', {
    name: 'Système — Délégation non exportable des identifiants (CredSSP)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\CredentialsDelegation|AllowProtectedCreds',
    expected: '1',
    operator: 'eq',
    severity: 'high',
    minOsVersion: 'Windows 10 1703',
  }),
  r('wsb-143', {
    name: 'Système — Oracle de chiffrement CredSSP = Forcer mise à jour (0)',
    category: 'Credentials',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\CredSSP\\Parameters|AllowEncryptionOracle',
    expected: '0',
    operator: 'eq',
    severity: 'critical',
  }),
  r('wsb-144', {
    name: 'Système — Télémétrie Windows = Désactivée ou Sécurité (0)',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|AllowTelemetry',
    expected: '1',
    operator: 'lt',
    severity: 'moderate',
  }),
  r('wsb-145', {
    name: 'Système — Compte Administrateur intégré en mode approbation Admin',
    category: 'Accounts',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System|FilterAdministratorToken',
    expected: '1',
    operator: 'eq',
    severity: 'high',
  }),
  r('wsb-146', {
    name: 'Services — Spouleur d\'impression désactivé (si non requis)',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Spooler',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-147', {
    name: 'Réseau — Passerelle par défaut SSDP Discovery sans service actif',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'upnphost',
    expected: 'Disabled',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-148', {
    name: 'Mises à jour — Redémarrage automatique sans utilisateur connecté',
    category: 'Updates',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU|NoAutoRebootWithLoggedOnUsers',
    expected: '1',
    operator: 'neq',
    severity: 'low',
  }),
  r('wsb-149', {
    name: 'Système — Pont réseau interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections|NC_AllowNetBridge_NLA',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),
  r('wsb-150', {
    name: 'Système — Partage de connexion Internet via interface interdit',
    category: 'Network',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Network Connections|NC_ShowSharedAccessUI',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
  }),
];
