import type { ComplianceRule } from '@obliance/shared';

const r = (id: string, opts: Omit<ComplianceRule, 'id' | 'autoRemediateScriptId'>): ComplianceRule =>
  ({ id, autoRemediateScriptId: null, ...opts });

export const windowsPerformanceRules: ComplianceRule[] = [

  // ─── POWER PLAN (5) ───────────────────────────────────────────────────────

  r('perf-001', {
    name: 'Plan d\'alimentation — Haute performance actif',
    category: 'Power',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((powercfg /getactivescheme) -match "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c|e9a42b02-d5df-448d-aa00-03f14749eb61"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c',
  }),
  r('perf-002', {
    name: 'Plan d\'alimentation — Mise en veille désactivée (secteur)',
    category: 'Power',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(powercfg /query SCHEME_CURRENT SUB_SLEEP STANDBYIDLE | Select-String "Current AC Power Setting Index" | ForEach-Object { if($_ -match "0x([0-9a-f]+)"){[uint32]"0x$($Matches[1])"}}).ToString()',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'powercfg /change standby-timeout-ac 0',
  }),
  r('perf-003', {
    name: 'Plan d\'alimentation — Extinction écran ≤ 15 min (secteur)',
    category: 'Power',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'powercfg /query SCHEME_CURRENT SUB_VIDEO VIDEOIDLE | Select-String "Current AC Power Setting Index" | ForEach-Object { if($_ -match "0x([0-9a-f]+)"){[uint32]"0x$($Matches[1])"}};$v=[uint32]"0x$($Matches[1])";if($v -le 900 -and $v -gt 0){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'powercfg /change monitor-timeout-ac 15',
  }),
  r('perf-004', {
    name: 'Plan d\'alimentation — Disque dur jamais éteint (secteur)',
    category: 'Power',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'powercfg /query SCHEME_CURRENT SUB_DISK DISKIDLE | Select-String "Current AC Power Setting Index" | ForEach-Object { if($_ -match "0x([0-9a-f]+)"){[uint32]"0x$($Matches[1])"}};if([uint32]"0x$($Matches[1])" -eq 0){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'powercfg /change disk-timeout-ac 0',
  }),
  r('perf-005', {
    name: 'Plan d\'alimentation — USB Selective Suspend désactivé',
    category: 'Power',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Services\\USB\\DisableSelectiveSuspend',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\USB\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\USB\' -Name \'DisableSelectiveSuspend\' -Value 1 -Type DWord',
  }),

  // ─── TELEMETRY & TRACKING (12) ────────────────────────────────────────────

  r('perf-010', {
    name: 'Télémétrie — DiagTrack service désactivé',
    category: 'Telemetry',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'DiagTrack',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service DiagTrack -Force -ErrorAction SilentlyContinue; Set-Service DiagTrack -StartupType Disabled',
  }),
  r('perf-011', {
    name: 'Télémétrie — Niveau à Security (0)',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection|AllowTelemetry',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\DataCollection\' -Name \'AllowTelemetry\' -Value 0 -Type DWord',
  }),
  r('perf-012', {
    name: 'Télémétrie — dmwappushservice désactivé',
    category: 'Telemetry',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'dmwappushservice',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service dmwappushservice -Force -ErrorAction SilentlyContinue; Set-Service dmwappushservice -StartupType Disabled',
  }),
  r('perf-013', {
    name: 'Télémétrie — Connected User Experiences désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection|AllowTelemetry',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection\' -Name \'AllowTelemetry\' -Value 0 -Type DWord',
  }),
  r('perf-014', {
    name: 'Télémétrie — Advertising ID désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo|DisabledByGroupPolicy',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\AdvertisingInfo\' -Name \'DisabledByGroupPolicy\' -Value 1 -Type DWord',
  }),
  r('perf-015', {
    name: 'Télémétrie — Feedback désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Microsoft\\Siuf\\Rules|NumberOfSIUFInPeriod',
    expected: '0',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'New-Item -Path \'HKCU:\\SOFTWARE\\Microsoft\\Siuf\\Rules\' -Force | Out-Null; Set-ItemProperty -Path \'HKCU:\\SOFTWARE\\Microsoft\\Siuf\\Rules\' -Name \'NumberOfSIUFInPeriod\' -Value 0 -Type DWord',
  }),
  r('perf-016', {
    name: 'Télémétrie — Activity History désactivée',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\System|EnableActivityFeed',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System\' -Name \'EnableActivityFeed\' -Value 0 -Type DWord',
  }),
  r('perf-017', {
    name: 'Télémétrie — Location tracking désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors|DisableLocation',
    expected: '1',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\LocationAndSensors\' -Name \'DisableLocation\' -Value 1 -Type DWord',
  }),
  r('perf-018', {
    name: 'Télémétrie — Handwriting data sharing désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\TabletPC|PreventHandwritingDataSharing',
    expected: '1',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\TabletPC\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\TabletPC\' -Name \'PreventHandwritingDataSharing\' -Value 1 -Type DWord',
  }),
  r('perf-019', {
    name: 'Télémétrie — Customer Experience Improvement désactivé',
    category: 'Telemetry',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows|CEIPEnable',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\SQMClient\\Windows\' -Name \'CEIPEnable\' -Value 0 -Type DWord',
  }),
  r('perf-020', {
    name: 'Télémétrie — Application Compatibility PCA désactivé',
    category: 'Telemetry',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'PcaSvc',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service PcaSvc -Force -ErrorAction SilentlyContinue; Set-Service PcaSvc -StartupType Disabled',
  }),
  r('perf-021', {
    name: 'Télémétrie — Compatibility Telemetry (CompatTelRunner) désactivé',
    category: 'Telemetry',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$t=Get-ScheduledTask "\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser" -ErrorAction SilentlyContinue; if($t -and $t.State -ne "Disabled"){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Disable-ScheduledTask -TaskName "\\Microsoft\\Windows\\Application Experience\\Microsoft Compatibility Appraiser" -ErrorAction SilentlyContinue',
  }),

  // ─── VISUAL EFFECTS & UI (6) ──────────────────────────────────────────────

  r('perf-030', {
    name: 'Effets visuels — Ajuster pour performances',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects|VisualFXSetting',
    expected: '2',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\VisualEffects\' -Name \'VisualFXSetting\' -Value 2 -Type DWord',
  }),
  r('perf-031', {
    name: 'Effets visuels — Transparence désactivée',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize|EnableTransparency',
    expected: '0',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize\' -Name \'EnableTransparency\' -Value 0 -Type DWord',
  }),
  r('perf-032', {
    name: 'Effets visuels — Animations de fenêtres désactivées',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop\\WindowMetrics|MinAnimate',
    expected: '0',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\Control Panel\\Desktop\\WindowMetrics\' -Name \'MinAnimate\' -Value \'0\' -Type String',
  }),
  r('perf-033', {
    name: 'Effets visuels — Menu Start animation désactivée',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\Control Panel\\Desktop|MenuShowDelay',
    expected: '0',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Set-ItemProperty -Path \'HKCU:\\Control Panel\\Desktop\' -Name \'MenuShowDelay\' -Value \'0\' -Type String',
  }),
  r('perf-034', {
    name: 'Game Bar — Désactivée',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR|AppCaptureEnabled',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR\' -Force | Out-Null; Set-ItemProperty -Path \'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\GameDVR\' -Name \'AppCaptureEnabled\' -Value 0 -Type DWord',
  }),
  r('perf-035', {
    name: 'Game DVR — Background recording désactivé',
    category: 'Visual',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR|AllowGameDVR',
    expected: '0',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\GameDVR\' -Name \'AllowGameDVR\' -Value 0 -Type DWord',
  }),

  // ─── SERVICES INUTILES (10) ───────────────────────────────────────────────

  r('perf-040', {
    name: 'Service SysMain (Superfetch) désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'SysMain',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Stop-Service SysMain -Force -ErrorAction SilentlyContinue; Set-Service SysMain -StartupType Disabled',
  }),
  r('perf-041', {
    name: 'Service Windows Search (WSearch) désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'WSearch',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service WSearch -Force -ErrorAction SilentlyContinue; Set-Service WSearch -StartupType Disabled',
  }),
  r('perf-042', {
    name: 'Service Windows Update Medic désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$s=Get-Service WaaSMedicSvc -ErrorAction SilentlyContinue; if($s -and $s.Status -eq "Running"){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service WaaSMedicSvc -Force -ErrorAction SilentlyContinue; Set-Service WaaSMedicSvc -StartupType Disabled -ErrorAction SilentlyContinue',
  }),
  r('perf-043', {
    name: 'Service Fax désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Fax',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service Fax -Force -ErrorAction SilentlyContinue; Set-Service Fax -StartupType Disabled',
  }),
  r('perf-044', {
    name: 'Service Print Spooler désactivé (si pas d\'imprimante)',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'Spooler',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service Spooler -Force -ErrorAction SilentlyContinue; Set-Service Spooler -StartupType Disabled',
  }),
  r('perf-045', {
    name: 'Service Bluetooth Support désactivé (si pas de BT)',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'bthserv',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service bthserv -Force -ErrorAction SilentlyContinue; Set-Service bthserv -StartupType Disabled',
  }),
  r('perf-046', {
    name: 'Service Remote Registry désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'RemoteRegistry',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Stop-Service RemoteRegistry -Force -ErrorAction SilentlyContinue; Set-Service RemoteRegistry -StartupType Disabled',
  }),
  r('perf-047', {
    name: 'Service Xbox services désactivés',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$svcs=@("XblAuthManager","XblGameSave","XboxGipSvc","XboxNetApiSvc"); $running=$svcs|ForEach-Object{Get-Service $_ -EA SilentlyContinue}|Where-Object{$_.Status -eq "Running"}; if($running){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: '@("XblAuthManager","XblGameSave","XboxGipSvc","XboxNetApiSvc") | ForEach-Object { Stop-Service $_ -Force -ErrorAction SilentlyContinue; Set-Service $_ -StartupType Disabled -ErrorAction SilentlyContinue }',
  }),
  r('perf-048', {
    name: 'Service Maps Broker désactivé',
    category: 'Services',
    checkType: 'service',
    targetPlatform: 'windows',
    target: 'MapsBroker',
    expected: 'Stopped',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service MapsBroker -Force -ErrorAction SilentlyContinue; Set-Service MapsBroker -StartupType Disabled',
  }),
  r('perf-049', {
    name: 'Service AllJoyn Router désactivé',
    category: 'Services',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$s=Get-Service AJRouter -ErrorAction SilentlyContinue; if($s -and $s.Status -eq "Running"){"FAIL"}else{"PASS"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'Stop-Service AJRouter -Force -ErrorAction SilentlyContinue; Set-Service AJRouter -StartupType Disabled',
  }),

  // ─── SYSTEM OPTIMIZATION (8) ──────────────────────────────────────────────

  r('perf-060', {
    name: 'HPET — High Precision Event Timer désactivé',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((bcdedit /enum | Select-String "useplatformclock") -match "No"){"PASS"}elseif(-not(bcdedit /enum | Select-String "useplatformclock")){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'bcdedit /deletevalue useplatformclock',
  }),
  r('perf-061', {
    name: 'Mémoire virtuelle — Pagefile géré automatiquement',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '(Get-WmiObject Win32_ComputerSystem).AutomaticManagedPagefile',
    expected: 'True',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: '$cs = Get-WmiObject Win32_ComputerSystem; $cs.AutomaticManagedPagefile = $true; $cs.Put() | Out-Null',
  }),
  r('perf-062', {
    name: 'Priorité GPU — Hardware-accelerated GPU scheduling activé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers|HwSchMode',
    expected: '2',
    operator: 'eq',
    severity: 'high',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers\' -Name \'HwSchMode\' -Value 2 -Type DWord',
  }),
  r('perf-063', {
    name: 'Nagle Algorithm — TCP désactivé (low latency)',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'windows',
    target: '$ifaces=Get-ChildItem "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces"; $bad=$ifaces|Where-Object{(Get-ItemProperty $_.PSPath -Name TcpAckFrequency -EA SilentlyContinue).TcpAckFrequency -ne 1}; if($bad.Count -eq 0 -and $ifaces.Count -gt 0){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Get-ChildItem \'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters\\Interfaces\' | ForEach-Object { Set-ItemProperty -Path $_.PSPath -Name \'TcpAckFrequency\' -Value 1 -Type DWord; Set-ItemProperty -Path $_.PSPath -Name \'TCPNoDelay\' -Value 1 -Type DWord }',
  }),
  r('perf-064', {
    name: 'Prefetch — Désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters|EnablePrefetcher',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Set-ItemProperty -Path \'HKLM:\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Memory Management\\PrefetchParameters\' -Name \'EnablePrefetcher\' -Value 0 -Type DWord',
  }),
  r('perf-065', {
    name: 'Cortana — Désactivée',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKLM\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search|AllowCortana',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\' -Force | Out-Null; Set-ItemProperty -Path \'HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Search\' -Name \'AllowCortana\' -Value 0 -Type DWord',
  }),
  r('perf-066', {
    name: 'Startup delay — Désactivé',
    category: 'System',
    checkType: 'registry',
    targetPlatform: 'windows',
    target: 'HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize|StartupDelayInMSec',
    expected: '0',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'New-Item -Path \'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize\' -Force | Out-Null; Set-ItemProperty -Path \'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Serialize\' -Name \'StartupDelayInMSec\' -Value 0 -Type DWord',
  }),
  r('perf-067', {
    name: 'Dernière heure d\'accès NTFS — Désactivée',
    category: 'System',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((fsutil behavior query disablelastaccess) -match "1"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'fsutil behavior set disablelastaccess 1',
  }),

  // ─── NETWORK OPTIMIZATION (4) ─────────────────────────────────────────────

  r('perf-070', {
    name: 'Réseau — RSS (Receive Side Scaling) activé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((Get-NetAdapterRss -ErrorAction SilentlyContinue | Where-Object Enabled -eq $true).Count -gt 0){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'Get-NetAdapter | Where-Object Status -eq \'Up\' | Enable-NetAdapterRss -ErrorAction SilentlyContinue',
  }),
  r('perf-071', {
    name: 'Réseau — Autotuning Level normal',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((netsh int tcp show global | Select-String "Receive Window Auto-Tuning Level") -match "normal"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'moderate',
    remediationScript: 'netsh int tcp set global autotuninglevel=normal',
  }),
  r('perf-072', {
    name: 'Réseau — ECN désactivé',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((netsh int tcp show global | Select-String "ECN Capability") -match "disabled"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'netsh int tcp set global ecncapability=disabled',
  }),
  r('perf-073', {
    name: 'Réseau — Timestamps RFC 1323 désactivés',
    category: 'Network',
    checkType: 'command',
    targetPlatform: 'windows',
    target: 'if((netsh int tcp show global | Select-String "Timestamps") -match "disabled"){"PASS"}else{"FAIL"}',
    expected: 'PASS',
    operator: 'eq',
    severity: 'optional',
    remediationScript: 'netsh int tcp set global timestamps=disabled',
  }),

];
