//go:build !windows

package main

import (
	"os"
	"os/exec"

	"github.com/creack/pty"
)

type unixShell struct {
	ptmx *os.File
	cmd  *exec.Cmd
}

// newShellSession spawns a login shell attached to a pseudo-terminal.
// cols/rows set the initial terminal dimensions so the first paint is correct.
//
// `sessionToken` is the unique identifier of the remote session as
// generated by the Obliance server. When tmux is available on the
// host we wrap the shell in `tmux new-session -A -s obliance-{token}`
// so that:
//   1. If the Obliance server reboots and the agent reconnects, the
//      next `open_remote_tunnel` carrying the same token re-runs the
//      same `tmux new-session -A` which ATTACHES to the existing
//      detached tmux instead of creating a fresh one. The user's
//      shell, scrollback, running processes and cwd all survive.
//   2. Each session keeps its own tmux instance (one per token), so
//      multiple parallel terminals on the same machine don't share
//      state.
//   3. When the user types `exit`, the shell process terminates,
//      tmux sees its sole window close and the tmux session ends
//      naturally — no orphan to clean up in the happy case.
//
// If tmux is not on PATH we fall back to spawning the shell directly
// (no resume support — the existing behaviour). The agent logs a
// startup hint so admins know how to enable it.
func newShellSession(cols, rows uint16, shellCmd string, sessionToken string, _ int) (shellSession, error) {
	var sh string
	var shArgs []string
	if shellCmd == "powershell" {
		if _, err := exec.LookPath("pwsh"); err == nil {
			sh = "pwsh"
			shArgs = []string{"-NoLogo", "-NoExit"}
		}
	}
	if sh == "" {
		sh = "/bin/bash"
		if _, err := exec.LookPath(sh); err != nil {
			sh = "/bin/sh"
			// /bin/sh on FreeBSD does not support --login, use -l
			shArgs = []string{"-l"}
		} else {
			shArgs = []string{"--login"}
		}
	}

	// tmux wrap when both: (a) tmux is installed, (b) we have a non-
	// empty session token to name with. Token is a 64-hex-char value
	// from crypto.randomBytes — we use it raw inside the session name
	// (tmux accepts wide alphanumerics).
	tmuxPath, tmuxErr := exec.LookPath("tmux")
	wrapInTmux := tmuxErr == nil && sessionToken != ""

	var cmd *exec.Cmd
	if wrapInTmux {
		// `new-session -A` attaches if the named session exists, else
		// creates it. `-D` would force-detach existing clients; we
		// don't use it because two tabs intentionally pointed at the
		// same token (e.g. observer + driver) would fight otherwise.
		// `-s name` is the persistent identifier. `--` separates tmux
		// args from the command args. We bound history-limit to keep
		// memory in check on long-running sessions.
		tmuxArgs := []string{
			"new-session", "-A",
			"-s", "obliance-" + sessionToken,
			"--",
			sh,
		}
		tmuxArgs = append(tmuxArgs, shArgs...)
		cmd = newCmd(tmuxPath, tmuxArgs...)
	} else {
		cmd = newCmd(sh, shArgs...)
	}
	// Build env: inherit parent, strip any TMOUT (bash idle-logout) that would
	// silently kill the session after N seconds of inactivity, then append ours.
	baseEnv := os.Environ()
	env := make([]string, 0, len(baseEnv)+2)
	for _, e := range baseEnv {
		if len(e) >= 6 && e[:6] == "TMOUT=" {
			continue
		}
		env = append(env, e)
	}
	env = append(env, "TERM=xterm-256color", "TMOUT=0")
	cmd.Env = env

	ws := &pty.Winsize{Cols: cols, Rows: rows}
	ptmx, err := pty.StartWithSize(cmd, ws)
	if err != nil {
		return nil, err
	}
	return &unixShell{ptmx: ptmx, cmd: cmd}, nil
}

func (s *unixShell) Read(p []byte) (int, error)  { return s.ptmx.Read(p) }
func (s *unixShell) Write(p []byte) (int, error) { return s.ptmx.Write(p) }

func (s *unixShell) Resize(cols, rows uint16) error {
	return pty.Setsize(s.ptmx, &pty.Winsize{Cols: cols, Rows: rows})
}

func (s *unixShell) Close() error {
	s.ptmx.Close()
	if s.cmd.Process != nil {
		_ = s.cmd.Process.Kill()
	}
	return nil
}
